/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSBundle.h"

@interface NSBundle (TSBundleAdditions_Deprecated)
+ (id)libraryExtrasFallbackDirectoryName;
+ (id)libraryExtrasDirectoryName;
+ (void)setLibraryExtrasFallbackDirectoryName:(id)arg1;
+ (void)setLibraryExtrasDirectoryName:(id)arg1;
@end

