/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEEditor.h"

#import "DVTFindBarFindable-Protocol.h"
#import "NSLayoutManagerDelegate-Protocol.h"
#import "NSTextDelegate-Protocol.h"
#import "NSTextViewDelegate-Protocol.h"

@class IDERichTextEditorScalingScrollView, NSLayoutManager;

@interface IDERichTextEditorViewController : IDEEditor <NSLayoutManagerDelegate, NSTextViewDelegate, NSTextDelegate, DVTFindBarFindable>
{
    IDERichTextEditorScalingScrollView *_scrollView;
    BOOL hasMultiplePages;
    BOOL rulerIsBeingDisplayed;
    BOOL isSettingSize;
    NSLayoutManager *_layoutManager;
    id _didSaveNotifToken;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (void)initialize;
@property(retain) NSLayoutManager *layoutManager; // @synthesize layoutManager=_layoutManager;
- (void).cxx_destruct;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (void)didEndToggleRichSheet:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)toggleRich:(id)arg1;
- (void)doToggleRichWithNewURL:(id)arg1;
- (void)doForegroundLayoutToCharacterIndex:(unsigned long long)arg1;
- (void)setHasMultiplePages:(BOOL)arg1 force:(BOOL)arg2;
- (id)documentView;
- (void)removePage;
- (void)addPage;
- (unsigned long long)numberOfPages;
- (void)convertTextForRichTextStateRemoveAttachments:(BOOL)arg1;
- (void)updateForRichTextAndRulerState;
- (void)removeAttachments;
- (BOOL)isHyphenationAllowed;
- (BOOL)isRulerVisible;
- (void)showRuler:(id)arg1;
- (void)showRulerDelayed:(BOOL)arg1;
- (void)setupTextViewForDocument;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setupInitialTextViewSharedState;
- (id)firstTextView;
- (void)breakUndoCoalescing;
- (id)document;
- (void)takeFocus;
- (void)loadView;
- (struct _NSRange)visibleCharacterRange;
- (void)primitiveInvalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
- (void)printDocument:(id)arg1;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)useSelectionForReplace:(id)arg1;
- (void)useSelectionForFind:(id)arg1;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
- (void)layoutManager:(id)arg1 didCompleteLayoutForTextContainer:(id)arg2 atEnd:(BOOL)arg3;
- (BOOL)textView:(id)arg1 writeCell:(id)arg2 atIndex:(unsigned long long)arg3 toPasteboard:(id)arg4 type:(id)arg5;
- (id)textView:(id)arg1 writablePasteboardTypesForCell:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)textView:(id)arg1 doubleClickedOnCell:(id)arg2 inRect:(struct CGRect)arg3;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)windowDidMove:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (struct CGRect)windowWillUseStandardFrame:(id)arg1 defaultFrame:(struct CGRect)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)jumpToSelection:(id)arg1;
- (void)rtf_toggleHyphenation:(id)arg1;
- (void)rtf_addLink:(id)arg1;
- (void)rtf_toggleRuler:(id)arg1;
- (void)rtf_insertParagraphBreak:(id)arg1;
- (void)rtf_insertLineBreak:(id)arg1;
- (void)rtf_insertPageBreak:(id)arg1;

@end

