/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEPlaygroundResult;

@interface _IDEPendingPlaygroundSessionResult : NSObject
{
    BOOL _createIfNeeded;
    IDEPlaygroundResult *_result;
    id _toyCreationBlock;
}

@property(copy) id toyCreationBlock; // @synthesize toyCreationBlock=_toyCreationBlock;
@property BOOL createIfNeeded; // @synthesize createIfNeeded=_createIfNeeded;
@property(retain) IDEPlaygroundResult *result; // @synthesize result=_result;
- (void).cxx_destruct;

@end

