/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDeviceService.h"

@interface IDEPlaygroundExecutionDeviceService : DVTDeviceService
{
}

+ (id)overridingPlaygroundSearchPath;
- (id)directoryForPlaygroundAppConstructionWithAppUniquingString:(id *)arg1 error:(id *)arg2;
- (id)defaultStubPathForSDK:(id)arg1;
- (id)sessionForExecutingPlaygroundWithParameters:(id)arg1;

@end

