/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface IDEStructurePresentationOptions : NSObject
{
    BOOL _showsNames;
    BOOL _pushOptionsToChildStructures;
    NSString *_leftContainerSymbol;
    NSString *_rightContainerSymbol;
    NSString *_separatorString;
}

@property BOOL pushOptionsToChildStructures; // @synthesize pushOptionsToChildStructures=_pushOptionsToChildStructures;
@property(readonly) BOOL showsNames; // @synthesize showsNames=_showsNames;
@property(readonly) NSString *separatorString; // @synthesize separatorString=_separatorString;
@property(readonly) NSString *rightContainerSymbol; // @synthesize rightContainerSymbol=_rightContainerSymbol;
@property(readonly) NSString *leftContainerSymbol; // @synthesize leftContainerSymbol=_leftContainerSymbol;
- (void).cxx_destruct;
- (id)initWithLeftContainerSymbol:(id)arg1 rightContainerSymbol:(id)arg2 separatorString:(id)arg3 showsNames:(BOOL)arg4;

@end

