/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, IDEToybox, NSError, NSMutableDictionary, NSString;

@interface IDEToy : NSObject <DVTInvalidation>
{
    NSMutableDictionary *_generationToDataDictionary;
    unsigned long long _currentGeneration;
    BOOL _liveToy;
    IDEToybox *_toybox;
}

+ (void)initialize;
@property(readonly, getter=isLiveToy) BOOL liveToy; // @synthesize liveToy=_liveToy;
@property(retain, nonatomic) IDEToybox *toybox; // @synthesize toybox=_toybox;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (BOOL)liveToy;
@property(readonly) NSError *unarchivingError;
@property(readonly) BOOL supportsArchiving;
- (void)processPlaygroundResult:(id)arg1;
- (void)executionGenerationDidEndAndCompleted:(BOOL)arg1;
- (void)executionGenerationWillEnd;
- (void)beginExecutionGeneration:(unsigned long long)arg1;
- (id)viewControllerForDisplayingToy;
- (id)init;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

