/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEUtilitySlice.h>

@class DVTExtension;

@interface _IDEUtilitySliceExtension : IDEUtilitySlice
{
    DVTExtension *_extension;
}

@property(retain, nonatomic) DVTExtension *extension; // @synthesize extension=_extension;
- (void).cxx_destruct;
- (id)description;
- (BOOL)wantsBottomPadding;
- (BOOL)wantsHeaderBottomBorder;
- (id)maximumAllowedRuntimeOSVersion;
- (id)minimumRequiredRuntimeOSVersion;
- (id)positionAnchor;
- (id)positionPriority;
- (BOOL)supportsDocumentInspection;
- (BOOL)supportsDocumentUndo;
- (id)inspectorTitleKeyPath;
- (id)sliceFile;
- (id)inspectorTitle;
- (id)categoryIdentifier;
- (id)contentType;
- (Class)controllerClass;
- (id)version;
- (id)name;
- (id)sliceDictionary;
- (id)bundle;
- (id)identifier;
- (id)valueForKey:(id)arg1;
- (id)initWithExtension:(id)arg1;

@end

