/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableCellView.h"

@class IDEAccountPrefsEntitlementsIconsView;

@interface IDEAccountPrefsDeveloperAccountProfileCellView : NSTableCellView
{
    IDEAccountPrefsEntitlementsIconsView *_iconsView;
}

@property(retain) IDEAccountPrefsEntitlementsIconsView *iconsView; // @synthesize iconsView=_iconsView;
- (void).cxx_destruct;
@property(retain) id <DVTProvisioningProfile> objectValue;

@end

