/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEDistributionStepViewController.h>

@class DVTStackView_AppKitAutolayout, NSArray;

@interface IDEDistributionEntitlementOptionsViewController : IDEDistributionStepViewController
{
    NSArray *_optionsViewControllers;
    DVTStackView_AppKitAutolayout *_optionsStackView;
}

+ (BOOL)skipStepForContext:(id)arg1 assistantDirection:(int)arg2;
+ (void)_createProcessorsForContext:(id)arg1;
@property(retain, nonatomic) DVTStackView_AppKitAutolayout *optionsStackView; // @synthesize optionsStackView=_optionsStackView;
@property(retain, nonatomic) NSArray *optionsViewControllers; // @synthesize optionsViewControllers=_optionsViewControllers;
- (void).cxx_destruct;
- (id)providedOutputContextPropetyNames;
- (id)requiredInputContextPropertyNames;
- (void)viewDidInstall;
- (id)title;
- (id)nibName;

@end

