/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDECapsuleViewController-Protocol.h"
#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class IDECombinedDownloadsPrefPaneController, IDEDownloadableContentTypeGroup, NSImage, NSString, NSTableView;

@interface IDEDownloadableCapsuleViewController : IDEViewController <NSTableViewDelegate, NSTableViewDataSource, IDECapsuleViewController>
{
    NSString *_downloadableTypeName;
    IDEDownloadableContentTypeGroup *_downloadablesGroup;
    IDECombinedDownloadsPrefPaneController *_prefPaneController;
    NSTableView *_tableView;
}

@property(retain) NSTableView *tableView; // @synthesize tableView=_tableView;
@property __weak IDECombinedDownloadsPrefPaneController *prefPaneController; // @synthesize prefPaneController=_prefPaneController;
@property(retain) IDEDownloadableContentTypeGroup *downloadablesGroup; // @synthesize downloadablesGroup=_downloadablesGroup;
@property(copy) NSString *downloadableTypeName; // @synthesize downloadableTypeName=_downloadableTypeName;
- (void).cxx_destruct;
- (void)_reloadDataForItem:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (id)downloadArrowDark;
- (id)downloadArrow;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
@property(readonly) NSString *titleForDisplay;
- (void)reloadData;
- (double)tableHeightWithContentRows;
- (void)primitiveInvalidate;
- (void)viewDidInstall;

// Remaining properties
@property BOOL canAddItems;
@property(readonly) BOOL canDrag;
@property(readonly) BOOL canRemove;
@property BOOL canRemoveItems;
@property(readonly) BOOL canRename;
@property(readonly) BOOL canSelect;
@property(readonly) BOOL canUndisclose;
@property(readonly) BOOL disclosedByDefault;
@property(readonly) NSString *footerLabel;
@property(readonly) NSImage *icon;

@end

