/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEKit/IDEImageMediaResource.h>

@interface IDEIconSetMediaResource : IDEImageMediaResource
{
}

- (id)mediaLibraryDetailControllerIdentifier;
- (id)generateContentForFilePath:(id)arg1 contentType:(id)arg2;
- (id)generateIconForFilePath:(id)arg1 contentType:(id)arg2;

@end

