/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSPasteboardReading-Protocol.h"
#import "NSPasteboardWriting-Protocol.h"

@class DVTDocumentLocation, DVTFileDataType, NSArray, NSString;

@interface IDENavigableItemArchivableRepresentation : NSObject <NSCopying, NSCoding, NSPasteboardWriting, NSPasteboardReading>
{
    NSString *_domainIdentifier;
    NSArray *_identifierPath;
    unsigned long long _indexOfDocumentIdentifier;
    DVTDocumentLocation *_documentLocation;
    DVTFileDataType *_contextualDocumentType;
    NSString *_geniusCategoryIdentifier;
}

+ (unsigned long long)readingOptionsForType:(id)arg1 pasteboard:(id)arg2;
+ (id)readableTypesForPasteboard:(id)arg1;
+ (void)initialize;
@property(copy) NSString *geniusCategoryIdentifier; // @synthesize geniusCategoryIdentifier=_geniusCategoryIdentifier;
@property(readonly) DVTDocumentLocation *documentLocation; // @synthesize documentLocation=_documentLocation;
@property(readonly) DVTFileDataType *contextualDocumentType; // @synthesize contextualDocumentType=_contextualDocumentType;
@property(readonly) unsigned long long indexOfDocumentIdentifier; // @synthesize indexOfDocumentIdentifier=_indexOfDocumentIdentifier;
@property(readonly) NSArray *identifierPath; // @synthesize identifierPath=_identifierPath;
@property(readonly) id domainIdentifier; // @synthesize domainIdentifier=_domainIdentifier;
- (void).cxx_destruct;
- (id)initWithPasteboardPropertyList:(id)arg1 ofType:(id)arg2;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqualToArchivableRepresentation:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithNavigableItem:(id)arg1;

@end

