/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol IDEStructureEditingGroupingTarget
- (id)actualNavigableItem;
- (long long)actualChildIndex;
- (BOOL)structureEditingGroupSubitemsAtIndexes:(id)arg1 groupIndex:(long long *)arg2;
- (BOOL)structureEditingCanGroupSubitemsAtIndexes:(id)arg1;
- (BOOL)structureEditingAddNewSubgroup;
- (BOOL)structureEditingCanAddNewSubgroup;
@end

