/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButton.h"

@class NSImage, NSTrackingArea;

@interface IDEWelcomeWindowHighlightButton : NSButton
{
    NSTrackingArea *_trackingArea;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSImage *pressedImage;
@property(retain, nonatomic) NSImage *rolloverImage;
- (id)hitTest:(struct CGPoint)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateTrackingAreas;

@end

