/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDocument.h"

@interface NSDocument (IDENSDocumentAdditions)
- (void)ide_canCloseAsynchronouslyUsingBlock:(id)arg1;
- (void)ideNSDocument:(id)arg1 shouldClose:(BOOL)arg2 contextInfo:(void *)arg3;
@end

