/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAbstractClassProvider.h>

#import "DVTInvalidation-Protocol.h"

@class DVTObservingToken, DVTStackBacktrace, IDEWorkspaceDocument, NSTimer;

@interface IBAbstractWorkspaceDocumentClassProvider : IBAbstractClassProvider <DVTInvalidation>
{
    DVTStackBacktrace *unregisterBacktrace;
    IDEWorkspaceDocument *workspaceDocument;
    int referenceCount;
    NSTimer *timeoutTimer;
    DVTObservingToken *workspaceObservingToken;
    BOOL ignoreTimeoutAndImmediatelyUnregister;
}

+ (double)timeout;
+ (void)initialize;
+ (void)unregisterWorkspaceDocumentClassProvider:(id)arg1;
+ (id)retainedClassProviderForWorkspaceDocument:(id)arg1;
+ (id)retainedClassProviderForReferenceKey:(id)arg1 initNewProviderBlock:(id)arg2;
@property(readonly) IDEWorkspaceDocument *workspaceDocument; // @synthesize workspaceDocument;
- (void).cxx_destruct;
- (void)releaseClassProvider;
- (id)retainClassProvider;
- (void)workspaceDidInvalidate;
- (void)markForInvalidation;
- (void)timeoutTimerDidFire:(id)arg1;
- (id)referenceKey;
- (void)primitiveInvalidate;
- (id)initWithWorkspaceDocument:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

