/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface IBAbstractDocumentUnarchiverGroupMember : NSObject <NSCopying>
{
}

- (id)unarchiveAsObjectReferenceWithReferenceType:(id)arg1;
- (id)unarchiveAsObject;
- (void)unarchiveContentWithBlock:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly) NSString *elementName; // @dynamic elementName;
@property(readonly) NSString *key; // @dynamic key;

@end

