/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IBAttributeSearchLocationIteratorDelegate <NSObject>
- (id)searchLocationIterator:(id)arg1 stringValueForAttributeSearchLocation:(id)arg2 memberID:(id)arg3;
- (long long)searchLocationIterator:(id)arg1 compareAttributeSearchLocation:(id)arg2 forMemberID:(id)arg3 toLocation:(id)arg4 forMemberID:(id)arg5;
- (id)searchLocationIterator:(id)arg1 attributeSearchLocationsForMemberID:(id)arg2 andKeyPath:(id)arg3;
- (id)searchLocationIterator:(id)arg1 attributeKeyPathsForMemberID:(id)arg2;
- (id)nextMemberIDForSearchLocationIterator:(id)arg1 afterMemberID:(id)arg2;
- (id)lastMemberIDForSearchLocationIterator:(id)arg1;
- (id)firstMemberIDForSearchLocationIterator:(id)arg1;
@end

