/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAutolayoutIssueOutlineItem.h>

@class IBAutolayoutContentSizePriorityChange;

@interface IBAutolayoutContentSizePriorityChangeOutlineItem : IBAutolayoutIssueOutlineItem
{
    IBAutolayoutContentSizePriorityChange *_change;
}

@property(readonly, nonatomic) IBAutolayoutContentSizePriorityChange *change; // @synthesize change=_change;
- (void).cxx_destruct;
- (id)initWithChange:(id)arg1;

@end

