/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAbstractPreviewDocumentEditor.h>

@class IDENotifyingLocalizedGroup, NSSegmentedControl;

@interface IBBasePreviewDocumentEditor : IBAbstractPreviewDocumentEditor
{
    NSSegmentedControl *_accessoryLocalizationControl;
    IDENotifyingLocalizedGroup *_localizedGroup;
}

+ (id)buildAccessoryLocalizationControlForLanguages:(id)arg1 developmentLanguage:(id)arg2 withTarget:(id)arg3;
+ (id)languageMenuForLanguages:(id)arg1 developmentLanguage:(id)arg2 withTarget:(id)arg3;
- (void).cxx_destruct;
- (id)displayNameForAppyingRecipe:(id)arg1 toObject:(id)arg2;
- (id)initialRecipe;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)changeLanguage:(id)arg1;
- (void)applySettingsToDocument:(id)arg1 forPreviewRecipe:(id)arg2 withPasteboardCloningContext:(id)arg3;
- (void)refreshSelectionState;
- (id)labelForLocale:(id)arg1;
- (id)selectedLanguages;
- (id)targetRecipes;
- (id)installControls;
- (id)installEditorObservations;
- (void)primitiveInvalidate;

@end

