/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBResourceManager.h>

@interface IBCocoaResourceManager : IBResourceManager
{
}

+ (id)systemMediaRepository;
+ (id)systemImageResources;
+ (id)systemSoundResources;
- (id)placeholderResourceIconForMediaType:(id)arg1;
- (id)placeholderResourceContentForMediaType:(id)arg1 originalValue:(id)arg2;
- (id)foldingStrategy;
- (id)typesForDefaultMediaRepositories;

@end

