/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface IBDocumentArchivingSchemaBitmask : NSObject
{
    CDStruct_6db0658e *map;
    long long mapCount;
    NSString *elementName;
    NSString *typeName;
}

+ (id)sharedInstance;
@property(readonly) NSString *elementName; // @synthesize elementName;
@property(readonly) NSString *typeName; // @synthesize typeName;
- (void).cxx_destruct;
- (id)allBitNames;
- (id)bitNamesForBitmask:(long long)arg1;
- (BOOL)decodeBitmask:(unsigned long long *)arg1 fromBits:(id)arg2;
- (id)initWithTypeName:(id)arg1 elementName:(id)arg2 bitmaskMap:(CDStruct_6db0658e *)arg3 count:(long long)arg4 copy:(BOOL)arg5;

@end

