/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBDocumentMemberWrapper.h>

@class IBConnection;

@interface IBDocumentConnectionMemberWrapper : IBDocumentMemberWrapper
{
}

+ (id)keyPathsForValuesAffectingImage;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
- (id)ideModelObjectTypeIdentifier;
- (BOOL)wrapsNormalDocumentObject;
- (id)image;
- (id)name;
- (id)childWrappers;
@property(readonly) IBConnection *connection;
- (id)initWithMember:(id)arg1 document:(id)arg2;

@end

