/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IBDocumentArchivingSchema, IBDocumentUnarchiverRecursionState, IBMutableIdentityDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSSet, NSXMLDocument, NSXMLElement;

@interface IBDocumentUnarchiver : NSObject
{
    IBDocumentUnarchiverRecursionState *recursionState;
    IBDocumentArchivingSchema *schema;
    NSMutableDictionary *context;
    NSXMLDocument *xmlDocument;
    id <IBUnarchivableDocument> unarchivedDocument;
    NSXMLElement *documentElement;
    NSMutableDictionary *referenceUnarchivingBlocksByType;
    long long unarchivedObjects;
    NSMutableSet *referenceTypesEnabledForUnarchiving;
    NSSet *allowedReferenceTypes;
    NSMutableArray *allUnarchivedObjects;
    NSMutableArray *softErrorMessages;
    IBMutableIdentityDictionary *postUnarchiveBlocksByObjectThenPriority;
}

@property(readonly) NSMutableDictionary *context; // @synthesize context;
@property(readonly) IBDocumentArchivingSchema *schema; // @synthesize schema;
@property(readonly) id <IBUnarchivableDocument> unarchivedDocument; // @synthesize unarchivedDocument;
- (void).cxx_destruct;
- (id)unarchiveTextWithBase64EncodingIndicatorAttributeName:(id)arg1;
- (id)unarchiveWrappedInsetForKey:(id)arg1;
- (id)unarchiveWrappedBitmaskFromBitmask:(id)arg1 forKey:(id)arg2;
- (id)unarchiveWrappedEnumeratedValueFromEnumeration:(id)arg1 forKey:(id)arg2;
- (id)unarchiveWrappedDoubleForKey:(id)arg1;
- (id)unarchiveWrappedIntegerForKey:(id)arg1;
- (id)unarchiveWrappedBoolForKey:(id)arg1;
- (unsigned long long)unarchiveBitmaskFromBitmask:(id)arg1 forKey:(id)arg2 defaultValue:(unsigned long long)arg3;
- (int)unarchiveEnumeratedIntValueFromEnumeration:(id)arg1 forKey:(id)arg2 defaultValue:(int)arg3;
- (long long)unarchiveEnumeratedValueFromEnumeration:(id)arg1 forKey:(id)arg2 defaultValue:(long long)arg3;
- (BOOL)unarchiveBoolForKey:(id)arg1 defaultValue:(BOOL)arg2;
- (double)unarchiveDoubleForKey:(id)arg1 defaultValue:(double)arg2;
- (float)unarchiveFloatForKey:(id)arg1 defaultValue:(float)arg2;
- (long long)unarchiveInt64ForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)unarchiveIntegerForKey:(id)arg1 defaultValue:(long long)arg2;
- (struct _NSRange)unarchiveRangeForKey:(id)arg1 defaultValue:(struct _NSRange)arg2;
- (CDStruct_79f57be0)unarchiveOffsetForKey:(id)arg1 defaultValue:(CDStruct_79f57be0)arg2;
- (CDStruct_c519178c)unarchiveEdgeInsetsForKey:(id)arg1 defaultValue:(CDStruct_c519178c)arg2;
- (CDStruct_c519178c)unarchiveInsetForKey:(id)arg1 defaultValue:(CDStruct_c519178c)arg2;
- (struct CGRect)unarchiveRectForKey:(id)arg1 defaultValue:(struct CGRect)arg2;
- (struct CGSize)unarchiveSizeForKey:(id)arg1 defaultValue:(struct CGSize)arg2;
- (struct CGPoint)unarchivePointForKey:(id)arg1 defaultValue:(struct CGPoint)arg2;
- (id)unarchiveStringForKey:(id)arg1 defaultValue:(id)arg2;
- (id)unarchiveDictionaryWithName:(id)arg1 forOptionalKey:(id)arg2 defaultValue:(id)arg3;
- (unsigned long long)numberOfElementsInArrayToUnarchiveWithName:(id)arg1 forOptionalKey:(id)arg2;
- (id)unarchiveArrayWithName:(id)arg1 forOptionalKey:(id)arg2 defaultValue:(id)arg3;
- (id)unarchiveObjectReferenceWithType:(id)arg1 forKey:(id)arg2 defaultValue:(id)arg3;
- (id)unarchiveObjectForKey:(id)arg1 defaultValue:(id)arg2;
- (BOOL)containsValueForKey:(id)arg1;
- (id)softErrorMessages;
- (void)addSoftErrorMessage:(id)arg1;
- (void)enumerateObjectMembers:(id)arg1;
- (void)enumerateGroupMembers:(id)arg1;
- (BOOL)enterGroupWithName:(id)arg1 optionalKey:(id)arg2 usingBlock:(id)arg3;
- (id)unarchiveObjectReferenceAssumingAlreadyUnarchivedWithType:(id)arg1 forKey:(id)arg2;
- (id)unarchiveObjectReferenceWithType:(id)arg1 forKey:(id)arg2;
- (id)unarchiveDictionaryWithName:(id)arg1 forOptionalKey:(id)arg2;
- (id)unarchiveArrayWithName:(id)arg1 forOptionalKey:(id)arg2;
- (id)unarchiveObjectReferenceArrayWithName:(id)arg1 referenceType:(id)arg2 forOptionalKey:(id)arg3;
- (id)unarchiveObjectForKey:(id)arg1;
- (id)unarchiveObjectArrayOrDictionaryFromElement:(id)arg1;
- (void)raiseForUnexpectedChildElement:(id)arg1 expected:(id)arg2 key:(id)arg3;
- (void)raiseForUnknownElement:(id)arg1;
- (id)unarchiveDictionaryFromElement:(id)arg1;
- (id)unarchiveArrayFromElement:(id)arg1;
- (id)unarchiveReferenceFromElement:(id)arg1 referenceType:(id)arg2;
- (id)unarchiveObjectFromElement:(id)arg1;
- (void)runPostUnarchiveBlocksForObject:(id)arg1;
- (void)registerPostUnarchiveBlockForPriority:(double)arg1 block:(id)arg2;
- (void)registerDelayedReferenceUnarchivingOfType:(id)arg1 withBlock:(id)arg2;
- (void)enableUnarchivingReferencesOfType:(id)arg1;
- (BOOL)isUnarchivingReferencesOfTypeEnabled:(id)arg1;
- (id)objectElementWithName:(id)arg1 optionalKey:(id)arg2;
- (id)elementWithName:(id)arg1 optionalKey:(id)arg2;
- (id)elementWithKey:(id)arg1 expectElementName:(id)arg2;
- (id)keyForCurrentlyUnarchivedObject;
- (void)unarchiveDocument:(id)arg1;
- (void)recurseWithElement:(id)arg1 kind:(long long)arg2 invokingBlock:(id)arg3;
- (id)initWithSchema:(id)arg1 data:(id)arg2 error:(id *)arg3;
- (id)unarchivedIBDocument;

@end

