/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class IBGroup, IBMemberID;

@interface IBGroupRecord : NSObject <NSCoding>
{
    IBGroup *group;
    IBMemberID *groupID;
}

@property(readonly) IBMemberID *groupID; // @synthesize groupID;
@property(readonly) IBGroup *group; // @synthesize group;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithGroup:(id)arg1 groupID:(id)arg2;

@end

