/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTLayoutView_ML.h"

#import "IBICImageSlicingViewDelegate-Protocol.h"
#import "IBICStartSlicingButtonDelegate-Protocol.h"

@class IBICImageResizingBehavior, IBICImageSlicingView, IBICStartSlicingButton, NSBitmapImageRep, NSString, NSTextField;

@interface IBICImageSlicingViewContainer : DVTLayoutView_ML <IBICImageSlicingViewDelegate, IBICStartSlicingButtonDelegate>
{
    NSTextField *_titleField;
    IBICImageSlicingView *_slicingView;
    IBICStartSlicingButton *_startSlicingButton;
    id <IBICImageSlicingViewContainerDelegate> _delegate;
}

+ (id)titleTextField;
@property __weak id <IBICImageSlicingViewContainerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)startSlicingButton:(id)arg1 userDidChooseResizingMode:(long long)arg2;
- (void)imageSlicingView:(id)arg1 userDidMouseDown:(id)arg2;
- (void)imageSlicingView:(id)arg1 userDidChangeResizingBehavior:(id)arg2;
- (void)layoutBottomUp;
- (void)layoutTopDown;
- (void)resetScale;
@property(nonatomic) long long scale;
- (BOOL)shouldShowStartSlicingButton;
- (BOOL)isFlipped;
@property BOOL drawsWithKeyAppearance;
@property(nonatomic) BOOL drawsSelected;
@property(retain, nonatomic) IBICImageResizingBehavior *resizingBehavior;
@property(retain, nonatomic) NSBitmapImageRep *bitmap;
@property(retain, nonatomic) id representedObject;
@property(copy, nonatomic) NSString *title;
- (id)initWithFrame:(struct CGRect)arg1;

@end

