/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBICFolder.h"

@interface IBICFolder (DisplayAdditions)
+ (id)keyPathsForValuesAffectingIbInspectedFileName;
- (void)setIbInspectedFileName:(id)arg1;
- (id)ibInspectedFileName;
- (id)validatedFileNameForSettingProposedDisplayName:(id)arg1;
- (BOOL)isDisplayNameEditable;
- (BOOL)displaysInOutlineView;
- (BOOL)displaysChildrenInOutlineView;
- (id)icon;
@end

