/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBViewDragDelegate-Protocol.h"

@protocol IBICMultipartImageViewDelegate <IBViewDragDelegate>
- (id)multipartImageView:(id)arg1 imageForImageRepIdentifier:(id)arg2;
- (id)multipartImageView:(id)arg1 titleForImageRepIdentifier:(id)arg2;
- (void)multipartImageViewWillLayout:(id)arg1;
- (BOOL)multipartImageView:(id)arg1 interceptMouseUp:(id)arg2;
- (BOOL)multipartImageView:(id)arg1 interceptMouseDragged:(id)arg2 withOriginalMouseDown:(id)arg3;
- (BOOL)multipartImageView:(id)arg1 interceptMouseDown:(id)arg2;
- (void)multipartImageView:(id)arg1 userDidEditTitle:(id)arg2;
- (void)multipartImageView:(id)arg1 performDelete:(id)arg2;
@end

