/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSArray, NSButton;

@interface IBICStartSlicingButton : NSView
{
    NSButton *_startSlicingButton;
    NSButton *_sliceVerticallyButton;
    NSButton *_sliceHorizontallyButton;
    NSButton *_sliceHorizontallyAndVerticallyButton;
    NSArray *_choiceButtons;
    NSArray *_choiceButtonWidthConstraints;
    NSArray *_choiceButtonHeightConstraints;
    id <IBICStartSlicingButtonDelegate> _delegate;
}

@property __weak id <IBICStartSlicingButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reset;
- (void)userChoseResizingMode:(id)arg1;
- (void)userPressedStartSlicing:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)buttonWithImageName:(id)arg1 title:(id)arg2 tag:(long long)arg3;

@end

