/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBViewDragDelegate-Protocol.h"

@protocol IBICDetailDocumentViewDelegate <IBViewDragDelegate>
- (void)detailDocumentViewLayoutDidComplete:(id)arg1;
- (void)detailDocumentViewWillLayoutTopDown:(id)arg1;
- (void)detailDocumentView:(id)arg1 cancelPreview:(id)arg2;
- (void)detailDocumentView:(id)arg1 togglePreview:(id)arg2;
- (void)detailDocumentView:(id)arg1 performDelete:(id)arg2;
- (void)detailDocumentViewDidFinishBandSelecting:(id)arg1;
- (void)detailDocumentView:(id)arg1 didUpdateBandSelectionRect:(struct CGRect)arg2 withEvent:(id)arg3 andInitialSelection:(id)arg4;
- (id)detailDocumentViewInitialSelectionForBandSelection:(id)arg1;
- (void)detailDocumentView:(id)arg1 didTrackContextMenuFromEvent:(id)arg2;
- (void)detailDocumentView:(id)arg1 willTrackContextMenuFromEvent:(id)arg2;
- (id)detailDocumentView:(id)arg1 menuForEvent:(id)arg2;
@end

