/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTLayoutView_ML.h"

#import "IBMouseMovedObservingView-Protocol.h"

@class NSImageView, NSPopUpButton, NSTextField;

@interface IBInspectorReferencingConstraintView : DVTLayoutView_ML <IBMouseMovedObservingView>
{
    BOOL highlighted;
    long long borderAttributes;
    id <IBInspectorReferencingConstraintViewDelegate> delegate;
    NSImageView *imageView;
    NSTextField *relatedViewTypeLabel;
    NSTextField *constantTypeLabel;
    NSTextField *relatedViewNameLabel;
    NSTextField *constantValueLabel;
    NSPopUpButton *popUpButton;
    long long layoutType;
}

@property(nonatomic) long long layoutType; // @synthesize layoutType;
@property(retain, nonatomic) NSPopUpButton *popUpButton; // @synthesize popUpButton;
@property(retain, nonatomic) NSTextField *constantValueLabel; // @synthesize constantValueLabel;
@property(retain, nonatomic) NSTextField *relatedViewNameLabel; // @synthesize relatedViewNameLabel;
@property(retain, nonatomic) NSTextField *constantTypeLabel; // @synthesize constantTypeLabel;
@property(retain, nonatomic) NSTextField *relatedViewTypeLabel; // @synthesize relatedViewTypeLabel;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak id <IBInspectorReferencingConstraintViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted;
@property(nonatomic) long long borderAttributes; // @synthesize borderAttributes;
- (void).cxx_destruct;
- (void)layoutBottomUp;
- (void)layoutConstantValueLabel;
- (void)layoutRelatedViewNameLabel;
- (void)layoutRightHandLabel:(id)arg1 alignedToLabel:(id)arg2 unlessInLayoutMode:(long long)arg3;
- (void)layoutConstantTypeLabel;
- (void)layoutRelatedViewTypeLabel;
- (void)layoutSubview:(id)arg1 unlessInLayoutMode:(long long)arg2 withBlock:(id)arg3;
- (double)baselineForLabel:(id)arg1;
- (double)yOriginForRightHandLabel:(id)arg1 alignedToLabel:(id)arg2;
- (double)widthForRightHandLabel;
- (double)widthForLeftHandLabel;
- (double)xOriginForRightHandLabel;
- (double)xOriginForLeftHandLabel;
- (struct CGRect)contentBounds;
- (BOOL)isFlipped;
- (void)drawRect:(struct CGRect)arg1;
- (id)borderPath;
- (struct CGRect)borderRect;
- (double)borderThickness;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)observeMouseMoved:(struct CGPoint)arg1 buttonState:(unsigned long long)arg2;

@end

