/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAbstractMemberConfigurationChooserController.h>

@class NSPopUpButton;

@interface IBMemberConfigurationChooserController : IBAbstractMemberConfigurationChooserController
{
    NSPopUpButton *_button;
}

- (void).cxx_destruct;
- (void)changeMemberConfiguration:(id)arg1;
- (void)refresh;
- (void)loadView;
- (id)managedButton;

@end

