/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSImageRep.h"

@interface IBMissingImageRep : NSImageRep
{
}

- (id)replacementObjectForCoder:(id)arg1;
- (BOOL)_drawFromRect:(struct CGRect)arg1 toRect:(struct CGRect)arg2 operation:(unsigned long long)arg3 alpha:(double)arg4 compositing:(BOOL)arg5 flipped:(BOOL)arg6 ignoreContext:(BOOL)arg7;
- (BOOL)drawInRect:(struct CGRect)arg1;
- (BOOL)draw;

@end

