/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBHUDConnectionInterfaceStyle.h>

@interface IBObjectWellConnectionInterfaceStyle : IBHUDConnectionInterfaceStyle
{
}

- (id)completionMenuPopUpTextColor;
- (id)completionMenuPopUpTextColorHighlighted;
- (id)completionMenuPopUpBackgroundColor;
- (id)completionMenuPopUpBackgroundColorHighlighted;
- (id)connectionWellPlusColor;
- (id)connectionWellPlusColorPressed;
- (id)connectionWellFillColorRolloverOrPreceeded;
- (id)connectionWellBorderColorWhenRolloverOrPreceeded;
- (id)connectionWellFillColor;
- (id)connectionWellBorderColor;
- (id)predecessorViewWarningPressedColor;
- (id)predecessorViewWarningTriangleColor;
- (id)predecessorViewWarningBangColor;
- (id)predecessorViewDisconnectButtonFillColor;
- (id)predecessorViewDisconnectButtonDisabledFillColor;
- (id)predecessorViewDisconnectButtonDisabledIconColor;
- (id)predecessorViewDisconnectButtonPressedStrokeColor;
- (id)predecessorViewDisconnectButtonRolledOverStrokeColor;
- (id)predecessorViewDisconnectButtonPressedFillColor;
- (id)predecessorViewDisconnectButtonRolledOverFillColor;
- (id)predecessorViewDisconnectButtonRolledOverIconColor;
- (id)predecessorViewDisconnectButtonIconColor;
- (id)predecessorViewDisconnectButtonPressedIconColor;
- (id)predecessorViewTextColorDisabled;
- (id)predecessorViewTextColor;
- (id)prototypeViewTextColor;
- (id)prototypeViewLinkBubbleBackgroundColorRolledOver;
- (id)prototypeViewLinkBubbleBorderColorRolledOver;
- (id)prototypeViewLinkBubbleBackgroundColor;
- (id)prototypeViewLinkBubbleBorderColor;
- (id)prototypeViewBackgroundColor;
- (id)prototypeViewBottomBorderColor;
- (id)prototypeViewFont;
- (id)disclosureView;
- (id)disclosureViewBottomBorderColor;
- (BOOL)fadesOutDragWindow;

@end

