/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAnnotationProvider.h>

@interface IBObjCAnnotationProvider : IBAnnotationProvider
{
}

- (id)updateAnnotationsByParsingDocument;
- (void)recordAnnotationUsingSourceModelItemInfo:(id)arg1 inClassNamed:(id)arg2;
- (struct _NSRange)itemRangeForAnnotationInParsedDocument:(id)arg1;
- (id)classNamesInParsedDocument;

@end

