/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IBMemberConfiguration, IBMemberPropertyValue, NSString;

@interface IBPropertyConfigurationValueRecord : NSObject
{
    NSString *_property;
    IBMemberConfiguration *_configuration;
    IBMemberPropertyValue *_value;
}

+ (id)recordWithProperty:(id)arg1 configuration:(id)arg2 value:(id)arg3;
@property(readonly) IBMemberPropertyValue *value; // @synthesize value=_value;
@property(readonly) IBMemberConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly) NSString *property; // @synthesize property=_property;
- (void).cxx_destruct;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToPropertyConfigurationValueRecord:(id)arg1;
- (unsigned long long)hash;
- (id)initWithProperty:(id)arg1 configuration:(id)arg2 value:(id)arg3;

@end

