/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IBPlatform, NSDictionary, NSSet;

@interface IBSourceCodeParserRegistry : NSObject
{
    IBPlatform *_platform;
    NSDictionary *_parserClassesByExtension;
    NSSet *_supportedFileExtensions;
    NSSet *_supportedFileTypeIdentifiers;
    NSSet *_primaryParsableFileTypeIdentifiers;
    NSSet *_secondaryParsableFileTypeIdentifiers;
}

+ (id)sourceCodeParserRegistryForPlatform:(id)arg1;
@property(readonly) NSSet *secondaryParsableFileTypeIdentifiers; // @synthesize secondaryParsableFileTypeIdentifiers=_secondaryParsableFileTypeIdentifiers;
@property(readonly) NSSet *primaryParsableFileTypeIdentifiers; // @synthesize primaryParsableFileTypeIdentifiers=_primaryParsableFileTypeIdentifiers;
@property(readonly) NSSet *supportedFileTypeIdentifiers; // @synthesize supportedFileTypeIdentifiers=_supportedFileTypeIdentifiers;
@property(readonly) NSSet *supportedFileExtensions; // @synthesize supportedFileExtensions=_supportedFileExtensions;
@property(readonly) IBPlatform *platform; // @synthesize platform=_platform;
- (void).cxx_destruct;
- (id)workItemsByParserClassForWorkItems:(id)arg1 limitedToParsersRequiringContext:(BOOL)arg2;
- (id)parserForFileExtension:(id)arg1;
- (id)initWithPlatform:(id)arg1;

@end

