/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEViewController.h"

@class DVTStackView_AppKitAutolayout, IBAbstractDocumentEditor, IBStructureAreaBackgroundView, IBStructureAreaDockLabelContainer, IDEViewController<IBSelectionProvider>, NSLayoutConstraint, NSMutableDictionary, NSOrderedSet, NSSegmentedControl, NSSet, NSString, NSView;

@interface IBStructureViewController : IDEViewController
{
    NSMutableDictionary *_cachedSelectionProvidersByStateSavingIdentifier;
    BOOL _isLoadingSelectionProviders;
    BOOL _drawsWithActiveLook;
    BOOL _shouldShowSelectionProviderSwitcher;
    NSOrderedSet *_structureAreaStructureProviders;
    NSSet *_selectionProviders;
    IBAbstractDocumentEditor *_documentEditor;
    IBStructureAreaDockLabelContainer *_dockItemLabelPopUpContainer;
    id <IBStructureViewControllerDelegate> _delegate;
    IDEViewController<IBSelectionProvider> *_currentStructureProvider;
    NSView *_contentView;
    IBStructureAreaBackgroundView *_backgroundView;
    IBStructureAreaBackgroundView *_structureSwitcherContainerView;
    NSSegmentedControl *_structureSwitcherSegmentedControl;
    NSLayoutConstraint *_stackViewConstraint;
    DVTStackView_AppKitAutolayout *_topStackView;
}

@property(nonatomic) BOOL shouldShowSelectionProviderSwitcher; // @synthesize shouldShowSelectionProviderSwitcher=_shouldShowSelectionProviderSwitcher;
@property __weak DVTStackView_AppKitAutolayout *topStackView; // @synthesize topStackView=_topStackView;
@property(retain, nonatomic) NSLayoutConstraint *stackViewConstraint; // @synthesize stackViewConstraint=_stackViewConstraint;
@property(nonatomic) __weak NSSegmentedControl *structureSwitcherSegmentedControl; // @synthesize structureSwitcherSegmentedControl=_structureSwitcherSegmentedControl;
@property(retain, nonatomic) IBStructureAreaBackgroundView *structureSwitcherContainerView; // @synthesize structureSwitcherContainerView=_structureSwitcherContainerView;
@property(retain, nonatomic) IBStructureAreaBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) IDEViewController<IBSelectionProvider> *currentStructureProvider; // @synthesize currentStructureProvider=_currentStructureProvider;
@property(nonatomic) __weak id <IBStructureViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IBStructureAreaDockLabelContainer *dockItemLabelPopUpContainer; // @synthesize dockItemLabelPopUpContainer=_dockItemLabelPopUpContainer;
@property(nonatomic) BOOL drawsWithActiveLook; // @synthesize drawsWithActiveLook=_drawsWithActiveLook;
@property(retain, nonatomic) IBAbstractDocumentEditor *documentEditor; // @synthesize documentEditor=_documentEditor;
- (void).cxx_destruct;
- (void)userSelectedStructureProviderFromSwitcher:(id)arg1;
- (void)_updateSelectionProviderSwitcherVisibility;
@property(readonly, nonatomic) NSOrderedSet *structureAreaStructureProviders; // @synthesize structureAreaStructureProviders=_structureAreaStructureProviders;
- (void)populateStructureAreaStructureProviders:(id)arg1;
@property(readonly, nonatomic) NSSet *selectionProviders; // @synthesize selectionProviders=_selectionProviders;
- (void)_ensureSelectionProvidersAreCreated;
- (void)makeAndPopulateSelectionProviders:(id)arg1;
- (void)registerWithDocumentEditor;
- (void)noteUserPreferencesForStructureAreaModeDidChange;
- (void)configureStructureAreaForUserPreferences;
@property(readonly, nonatomic) IDEViewController<IBSelectionProvider> *lastStructureSelectionProvider;
- (id)closedSelectionProvider;
- (id)structureAreaExpansionPreferencesKey;
- (void)editorInstalled;
@property(readonly, nonatomic, getter=isShowingStructureArea) BOOL showingStructureArea;
- (BOOL)supportsTogglingStructureArea;
- (void)toggleStructureArea:(id)arg1;
- (void)selectionProviderDidBecomeActive:(id)arg1;
- (double)constrainContentWidthAndChangeModesIfNeeded:(double)arg1;
- (id)selectionProviderForRevealingMembers:(id)arg1;
@property(readonly, nonatomic) double maximumContentWidth;
@property(readonly, nonatomic) double minimumContentWidth;
@property(readonly, nonatomic) double contentWidth;
@property(readonly, nonatomic) NSSet *highlightProviders;
@property(readonly, nonatomic) NSString *stateSavingIdentifier;
- (void)editedTopLevelObjectsDidChange;
- (void)topLevelObjectsChanged;
- (void)loadView;
- (void)primitiveInvalidate;

@end

