/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBAbstractClassProvider.h>

@class NSDictionary, NSMutableArray;

@interface IBUserDefinedActionClassProvider : IBAbstractClassProvider
{
    NSDictionary *_actionSelectorToTypeMap;
    NSMutableArray *_partialClassDescriptions;
}

- (void).cxx_destruct;
- (id)partialClassDescriptions;
@property(copy) NSDictionary *actionSelectorToTypeMap;
- (void)integrateDocumentDecodedPartialClassDescriptions:(id)arg1;
- (BOOL)shouldPreserveClassDescriptionSourceForEncodedClassDescriptions:(id)arg1;
- (id)additionalNonDocumentReferencedPartialClassDescriptionsForEncoding;
- (id)partialClassDescription;
- (id)init;

@end

