/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IBXMLDecoderParser, NSArray, NSDictionary, NSString;

@interface IBXMLDecoderElement : NSObject
{
    int _retainCountMinusOne;
    struct {
        unsigned char inlineBytes[32];
        char *bytes;
        unsigned long long length;
        unsigned long long capacity;
    } _characterBuffer;
    BOOL _charactersCompleted;
    NSString *_uninterpretedStringValue;
    IBXMLDecoderParser *_parser;
}

+ (id)elementName;
- (void).cxx_destruct;
- (BOOL)acceptNilElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptSetElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptArrayElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptDictionaryElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptStringElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptReferenceElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptObjectElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptBooleanElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptRealElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptIntegerElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptCharactersElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptBytesElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptDoubleElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptFloatElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptIntElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptBoolElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptAbstractObjectElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptAbstractValueElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptNameElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptFallbacksElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptClassElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptClassesElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptDataElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptArchiveElement:(id)arg1 error:(id *)arg2;
- (BOOL)acceptElement:(id)arg1 error:(id *)arg2;
- (void)finishedAddingSubelements;
- (void)finishedInterpretingCharacters;
- (BOOL)interpretDataReturningError:(id *)arg1;
- (void)finishedAcceptingCharacters;
- (void)acceptCharacters:(const char *)arg1 length:(long long)arg2;
- (void)growCharacterBuffer:(long long)arg1;
@property(readonly) NSString *uninterpretedStringValue;
- (BOOL)acceptsData;
- (BOOL)requestInsertionIntoParent:(id)arg1 error:(id *)arg2;
- (BOOL)addElement:(id)arg1 error:(id *)arg2;
- (id)resolvedAbstractObjectElement;
@property(readonly) NSString *referencedIdentifier;
@property(readonly) NSString *identifier;
@property(readonly) NSDictionary *keyedAbstractValueElements;
@property(readonly) NSArray *elements;
@property(readonly) NSString *elementName;
- (id)initWithAttributes:(const char **)arg1 parser:(id)arg2 error:(id *)arg3;
- (Class)elementClassForElementName:(const char *)arg1;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned long long)retainCount;
- (oneway void)release;
- (id)retain;

@end

