/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderKit/IBXMLDecoderElement.h>

@class NSArray, NSMutableArray;

@interface IBXMLDecoderFallbacksElement : IBXMLDecoderElement
{
    NSMutableArray *_nameElements;
}

+ (id)elementName;
- (void).cxx_destruct;
- (id)elements;
@property(readonly) NSArray *nameElements;
- (BOOL)acceptNameElement:(id)arg1 error:(id *)arg2;
- (BOOL)requestInsertionIntoParent:(id)arg1 error:(id *)arg2;

@end

