/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol IDEWorkspaceTabControllerCursorRectInterceptor
- (void)workspaceTabControllerWillInvalidateCursorRectsForViewsWithNoTrackingAreas:(id)arg1;
- (void)workspaceTabController:(id)arg1 willInvalidateCursorRectsForView:(id)arg2;
- (BOOL)workspaceTabController:(id)arg1 interceptAddCursorRect:(struct CGRect)arg2 cursor:(id)arg3 forView:(id)arg4 inWindow:(id)arg5;
- (BOOL)workspaceTabController:(id)arg1 interceptSetCursorForMouseLocation:(struct CGPoint)arg2 inWindow:(id)arg3;
@end

