/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSColor.h"

#import "IBBinaryArchivableColor-Protocol.h"
#import "IBBinaryArchiving-Protocol.h"

@class NSString;

@interface NSColor (IBBinaryArchivingAdditions) <IBBinaryArchiving, IBBinaryArchivableColor>
+ (id)ibColorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)ibColorWithWhite:(double)arg1 alpha:(double)arg2;
+ (id)decodeWithBinaryUnarchiver:(id)arg1;
- (const char *)cStringClassNameForBinaryArchiver:(id)arg1;
- (id)ibArchivedSystemKeyPathForBinaryArchiver:(id)arg1;
- (BOOL)ibGetRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
- (BOOL)ibGetWhite:(double *)arg1 alpha:(double *)arg2;
- (void)encodeWithBinaryArchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

