/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSGraphicsContext.h"

@interface NSGraphicsContext (IBGraphicsContextsAdditions)
+ (void)temporarilyMakeCGContextCurrent:(struct CGContext *)arg1 andDoOperationPerservingState:(id)arg2;
- (void)invokeCommandsWithContextFocusedOnFlippedRect:(struct CGRect)arg1 commands:(id)arg2;
- (void)drawTransparencyLayerWithShadow:(id)arg1 clippedToRect:(struct CGRect)arg2 commands:(id)arg3;
- (void)drawTransparencyLayerWithShadow:(id)arg1 opacity:(double)arg2 clippedToRect:(struct CGRect)arg3 commands:(id)arg4;
@end

