/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSRunLoop.h"

@interface NSRunLoop (IBIDEFoundationRunLoopAdditions)
- (void)spinRunLoopInMode:(id)arg1 waitingForSemaphore:(struct dispatch_semaphore_s *)arg2;
- (void)spinRunLoopInMode:(id)arg1 whileBlockExecutesConcurrently:(id)arg2;
- (void)ib_spinRunLoopInMode:(id)arg1 waitingForSemaphore:(struct dispatch_semaphore_s *)arg2;
- (void)ib_spinRunLoopInMode:(id)arg1 whileBlockExecutesConcurrently:(id)arg2;
@end

