/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDELogNavigator/IDEBotEditorTestDetailRun.h>

@class NSImage, NSString;

@interface IDEBotEditorIntegrationTestDetailRun : IDEBotEditorTestDetailRun
{
    BOOL _isSimulator;
    NSImage *_image;
    NSString *_deviceFamily;
    NSString *_deviceName;
    NSString *_osVersion;
    NSString *_processor;
}

+ (id)propertyForState:(int)arg1;
@property(nonatomic) BOOL isSimulator; // @synthesize isSimulator=_isSimulator;
@property(copy, nonatomic) NSString *processor; // @synthesize processor=_processor;
@property(copy, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(readonly, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
@property(copy, nonatomic) NSString *deviceFamily; // @synthesize deviceFamily=_deviceFamily;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)randomProcessor;
- (id)randomOS;
- (id)randomDeviceName;
- (id)randomDeviceFamily;
- (id)initWithDictionary:(id)arg1;
- (id)initWithIntegrationNumber:(unsigned long long)arg1 runGUID:(id)arg2 timestamp:(id)arg3 image:(id)arg4 deviceFamily:(id)arg5 deviceName:(id)arg6 osVersion:(id)arg7 processor:(id)arg8 failCount:(unsigned long long)arg9 passCount:(unsigned long long)arg10 results:(id)arg11;
- (id)init;

@end

