/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEActivityLogRecord.h"

@class iCloudActivityLogSection;

@interface iCloudActivityLogRecord : IDEActivityLogRecord
{
    double _startTime;
    double _stopTime;
    iCloudActivityLogSection *_logSection;
}

@property(retain, nonatomic) iCloudActivityLogSection *logSection; // @synthesize logSection=_logSection;
@property(nonatomic) double stopTime; // @synthesize stopTime=_stopTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)fullLogIfInMemory;
- (id)fullLogWithError:(id *)arg1;
- (void)removeSelfWithCompletionBlock:(id)arg1;
- (BOOL)isRemoved;
- (BOOL)isRecording;
- (id)highLevelStatus;
- (id)signature;
- (id)documentType;
- (double)timeStoppedRecording;
- (double)timeStartedRecording;
- (id)title;
- (id)domainType;
- (id)uniqueIdentifier;
- (id)init;

@end

