/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEDebugGaugeTrayCell.h"

@class DVTNotificationToken, NSMutableArray, iCloudController;

@interface iCloudDebuggingTrayCell : IDEDebugGaugeTrayCell
{
    DVTNotificationToken *_iCloudNotificationToken;
    NSMutableArray *_currentDisplayedItemStack;
}

@property(retain) NSMutableArray *currentDisplayedItemStack; // @synthesize currentDisplayedItemStack=_currentDisplayedItemStack;
@property(retain) DVTNotificationToken *iCloudNotificationToken; // @synthesize iCloudNotificationToken=_iCloudNotificationToken;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)_observeController:(id)arg1;
- (void)_updateProgressBarWithItem:(id)arg1 itemChangeType:(BOOL)arg2;
- (void)_insertItemIntoDisplayedItemStack:(id)arg1;
@property(readonly, nonatomic) iCloudController *controller;
- (id)initWithController:(id)arg1;

@end

