/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTPlistNode, IDEPlistDocument;

@interface IDEPlistNodeNavigable : NSObject
{
    IDEPlistDocument *_document;
    DVTPlistNode *_node;
}

@property(retain) DVTPlistNode *node; // @synthesize node=_node;
@property(retain) IDEPlistDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_fileReference;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (id)navigableItem_contentDocumentLocation;

@end

