/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DSMQuery, DVTPerformanceMetric, NSArray, NSMutableArray;

@interface IDEDocSearchController : NSObject
{
    NSArray *_frameworkFilteredTokenResults;
    NSArray *_extraTokenResults;
    NSMutableArray *_inflightTextResults;
    NSArray *_finalTextResults;
    NSMutableArray *_tokenResults;
    DSMQuery *_currentQuery;
    DSMQuery *_textQuery;
    BOOL _includeFullText;
    DVTPerformanceMetric *_perfMetric;
    id _completionBlock;
}

@property(copy) id completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)beginSearchingWithSearchString:(id)arg1 useFastTokenCache:(BOOL)arg2 includeFullTextResults:(BOOL)arg3 perfMetric:(id)arg4 completionBlock:(id)arg5;
- (void)_beginQuery:(id)arg1 useFastTokenCache:(BOOL)arg2;
- (void)extractTokenScopeFromSearchString:(id)arg1 completionBlock:(id)arg2;
- (void)beginSearchWithQuery:(id)arg1 useTokenCache:(BOOL)arg2 completionBlock:(id)arg3;
- (void)primeSearchIndexes;
- (void)_prepareSearch;
- (void)docSets:(id)arg1 didFindTextSearchResults:(id)arg2 isFinished:(BOOL)arg3 contextInfo:(void *)arg4;
- (void)docSets:(id)arg1 didFindTokenSearchResults:(id)arg2 isFinished:(BOOL)arg3 contextInfo:(void *)arg4;
- (void)processTokenResults:(id)arg1 updateResults:(BOOL)arg2;
- (void)_updateResultsFinished;
- (id)docSetsForSearch;
- (id)frameworksReferencedInActiveWorkspace;
- (id)_normalizedFamilyIdentifier:(id)arg1;
- (id)activeWorkspaceWindowController;

@end

