/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTViewController.h"

#import "DOMEventListener-Protocol.h"
#import "IDEDocContentView-Protocol.h"
#import "NSPopoverDelegate-Protocol.h"
#import "NSSplitViewDelegate-Protocol.h"

@class DVTBorderedView, DVTObservingToken, DVTReplacementView, DVTSplitView, DVTSplitViewItem, DVTStackBacktrace, IDEDocContentAreaViewController, NSString, NSView, WebView;

@interface IDEDocWebViewContentViewController : DVTViewController <NSPopoverDelegate, DOMEventListener, NSSplitViewDelegate, IDEDocContentView>
{
    double _cumulativeMagnifyDelta;
    short _stickyTextMagnifyGestureDirection;
    float _textSizeMultiplierAtGestureStart;
    id _bookmarksChangedWatcher;
    NSString *_redirectHash;
    DVTObservingToken *_contentOutlineViewWatcher;
    DVTSplitViewItem *_tocSplitViewItem;
    BOOL _tableOfContentsVisible;
    IDEDocContentAreaViewController *_hostContentAreaViewController;
    WebView *_webView;
    DVTReplacementView *_headerReplacementView;
    NSView *_webViewContainerView;
    DVTSplitView *_splitView;
    NSView *_webViewSampleCodeContainerView;
    DVTReplacementView *_tableOfContentsReplacementView;
    DVTBorderedView *_tableOfContentsBorderedView;
}

+ (id)bookmarkOnPressedImage;
+ (id)bookmarkOnOverImage;
+ (id)bookmarkOnImage;
+ (id)bookmarkOffPressedImage;
+ (id)bookmarkOffOverImage;
+ (id)bookmarkOffImage;
+ (id)mainDocumentElementInWebView:(id)arg1;
+ (void)initialize;
+ (id)webViewLoadingLogAspect;
@property(retain) DVTBorderedView *tableOfContentsBorderedView; // @synthesize tableOfContentsBorderedView=_tableOfContentsBorderedView;
@property(retain) DVTReplacementView *tableOfContentsReplacementView; // @synthesize tableOfContentsReplacementView=_tableOfContentsReplacementView;
@property(retain) NSView *webViewSampleCodeContainerView; // @synthesize webViewSampleCodeContainerView=_webViewSampleCodeContainerView;
@property(retain) DVTSplitView *splitView; // @synthesize splitView=_splitView;
@property __weak NSView *webViewContainerView; // @synthesize webViewContainerView=_webViewContainerView;
@property __weak DVTReplacementView *headerReplacementView; // @synthesize headerReplacementView=_headerReplacementView;
@property(getter=isTableOfContentsVisible) BOOL tableOfContentsVisible; // @synthesize tableOfContentsVisible=_tableOfContentsVisible;
@property __weak WebView *webView; // @synthesize webView=_webView;
@property __weak IDEDocContentAreaViewController *hostContentAreaViewController; // @synthesize hostContentAreaViewController=_hostContentAreaViewController;
- (void).cxx_destruct;
- (void)handleEvent:(id)arg1;
- (void)addBookmarkIconsToDocument:(id)arg1;
- (void)updateBookmarksInDocument:(id)arg1;
- (void)setZoomMultiplier:(float)arg1;
- (float)zoomMultiplier;
- (void)magnifyWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)haveWorkspaceOpenOrRevealURL:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForMIMEType:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5;
- (BOOL)_allowURLRequest:(id)arg1 webView:(id)arg2;
- (void)webView:(id)arg1 didReceiveTitle:(id)arg2 forFrame:(id)arg3;
- (id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 didCommitLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 didChangeLocationWithinPageForFrame:(id)arg2;
- (void)_addBookmarkForLoadedURL:(id)arg1;
- (id)bookNodeInFrame:(id)arg1;
- (void)webViewContextMenu_openLinkInNewTab:(id)arg1;
- (void)webViewContextMenu_copyLink:(id)arg1;
- (void)webViewContextMenu_findText:(id)arg1;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (unsigned long long)webView:(id)arg1 dragDestinationActionMaskForDraggingInfo:(id)arg2;
- (void)setTableOfContentsSplitterPosition:(double)arg1;
@property(readonly) double tableOfContentsSplitterPosition;
- (void)toggleTOCVisibility;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (BOOL)splitView:(id)arg1 shouldCollapseSubview:(id)arg2 forDoubleClickOnDividerAtIndex:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
@property(readonly) NSString *selectedStringInWebView;
- (void)updateContentOutlineViewForURLInFrame:(id)arg1;
- (id)nodeInWebFrame:(id)arg1;
- (void)showReferenceHeaderViewForToken:(id)arg1;
- (void)injectSampleCodeDownloadLinkForNode:(id)arg1;
- (void)hideReferenceHeaderView;
- (void)updateHeaderView;
- (void)loadResolvedURL:(id)arg1;
- (void)loadResolvedURLAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)docSetTokenForReferenceDocumentNode:(id)arg1;
- (id)appleRefOfReferenceDocumentInWebView;
- (void)primitiveInvalidate;
- (void)loadView;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

