/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XDInterface/_NSPredicate_RootTypeController.h>

@class NSTextField;

@interface _NSPredicate_StringKeyTypeController : _NSPredicate_RootTypeController
{
    NSTextField *_valueField;
}

- (void)dealloc;
- (void)remove;
- (id)lastKeyView;
- (id)firstKeyView;
- (id)stringToPassOn;
- (BOOL)passInString:(id)arg1;
- (id)leafPredicate;
- (id)setLeafPredicate:(id)arg1;
- (struct CGSize)setPosition:(struct CGPoint)arg1 secondRow:(struct CGPoint)arg2;
- (void)setOperator:(id)arg1;
- (id)possibleOperators;
- (void)_createValueField;
- (double)fieldWidth;
- (id)createFormatter;

@end

