/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSPopUpButton.h"

@class XDDiagramView;

@interface XDDiagramZoomPopUpButton : NSPopUpButton
{
    XDDiagramView *_diagramView;
}

+ (void)initialize;
- (void)_diagramViewDidChangeZoomFactor:(id)arg1;
- (id)diagramView;
- (void)_setDiagramView:(id)arg1;
- (void)_updatePopUpButtonItems;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

