/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XDInterface/XDCreationTool.h>

@interface XDLineGraphicTool : XDCreationTool
{
    struct _XDLineGraphicToolFlags _lgtFlags;
}

+ (Class)graphicClass;
+ (id)defaultIdentifier;
+ (void)initialize;
- (void)mouseDown:(id)arg1 inView:(id)arg2;
- (void)setDelegate:(id)arg1;
- (id)imageForDiagramToolbarItem;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

