/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CATransition.h"

@interface CATransition (IBTransitionsEffectsInspectorAdditions)
+ (id)keyPathsForValuesAffectingIbInspectedSubtype;
+ (id)keyPathsForValuesAffectingIbShadowedFilter;
- (void)setIbInspectedSubtype:(id)arg1;
- (id)ibInspectedSubtype;
- (id)ibShadowedFilter;
@end

