/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderCocoaIntegration/IBToManyCIFilterEffectsInspector.h>

@interface IBBackgroundFiltersEffectsInspector : IBToManyCIFilterEffectsInspector
{
}

- (id)defaultFilterName;
- (id)excludedFilterNamesForFilterChoices;
- (id)excludedCategoriesForFilterChoices;
- (id)localDragPasteboardType;
- (id)noFiltersDisplayString;
- (id)boundFilterKeyPathPrefix;
- (id)inspectedFilterIndexesKeyPath;
- (id)inspectedFilterNameKeyPath;
- (id)bindableFiltersKeyPath;
- (id)nibName;

@end

