/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTBorderedView.h"

@class NSString;

@interface IBBindingsCategoryView : DVTBorderedView
{
    NSString *_stringValue;
}

@property(copy, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
@property BOOL drawsTopBorder;
- (id)initWithFrame:(struct CGRect)arg1;

@end

