/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBTargetRuntime.h"

@interface IBCocoaTargetRuntime : IBTargetRuntime
{
    id <DVTFontTextFieldDataSource> fontDataSource;
}

- (void).cxx_destruct;
- (id)displayNameForPrimaryUserInterface;
- (id)icon;
- (id)operatingSystemName;
@property(readonly) id <DVTFontTextFieldDataSource> fontDataSource;
- (Class)documentClass;
- (id)windowPasteboardType;
- (id)viewPasteboardType;
- (id)objectPasteboardType;
- (id)archiveIdentifier;
- (id)identifier;

@end

