/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBAbstractActionConnection.h"

@interface IBCocoaActionConnection : IBAbstractActionConnection
{
}

+ (BOOL)objectAggregatesAllActions:(id)arg1;
+ (id)normalizeDestination:(id)arg1 withParent:(id)arg2;
+ (BOOL)canObjectFireActions:(id)arg1 inDocument:(id)arg2;
- (void)ibWarnings:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (id)archiveConnection;
- (id)equivalentDestinationInDocument:(id)arg1;
- (Class)classForDocumentArchiver:(id)arg1;
- (Class)classForCoder;

@end

