/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderCocoaIntegration/IBMenuEditorView.h>

@interface IBDropDownMenuEditorView : IBMenuEditorView
{
}

- (void)drawRect:(struct CGRect)arg1;
- (id)createMenuItemEditorViewForMenuItem:(id)arg1;
- (Class)menuItemEditorViewClass;
- (int)layoutDirection;
- (id)distanceToDragToAddItem;
- (double)maxEdgeInset;
- (double)minEdgeInset;
- (double)itemPadding;
- (id)initWithMenu:(id)arg1;

@end

