/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderCocoaIntegration/IBNSStoryboardAbstractTriggeredSegue.h>

@class NSView;

@interface IBNSStoryboardEmbedSegue : IBNSStoryboardAbstractTriggeredSegue
{
    NSView *_containerView;
}

+ (id)ibDefaultImageForInstance:(id)arg1;
+ (id)classIdentifier;
+ (BOOL)isObjectValidSource:(id)arg1;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)ibSetupTriggerForSegueTemplate:(id)arg1 inCompilationUnit:(id)arg2;
- (id)instantiateSegueTemplate;
- (id)badgeImage;

@end

