/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IBAbstractViewController.h"

#import "IBDocumentArchiving-Protocol.h"

@class IBSimulatedMetricsContainer, NSArray, NSDictionary, NSString, NSView;

@interface IBNSViewController : IBAbstractViewController <IBDocumentArchiving>
{
    IBNSViewController *_parentViewController;
    NSView *_view;
    NSString *_explicitStoryboardIdentifier;
    NSArray *_storyboardSegueTemplates;
    IBSimulatedMetricsContainer *_inheritedSimulatedMetrics;
    NSDictionary *_externalObjectsTableForViewLoading;
    NSString *_title;
    NSString *_nibName;
    NSString *_nibBundleIdentifier;
    NSArray *_childViewControllers;
}

+ (id)instantiateWithDocumentUnarchiver:(id)arg1;
+ (Class)ibViewClass;
@property(copy) NSArray *childViewControllers; // @synthesize childViewControllers=_childViewControllers;
@property(copy) NSDictionary *externalObjectsTableForViewLoading; // @synthesize externalObjectsTableForViewLoading=_externalObjectsTableForViewLoading;
@property(copy) NSString *nibBundleIdentifier; // @synthesize nibBundleIdentifier=_nibBundleIdentifier;
@property(copy) NSString *nibName; // @synthesize nibName=_nibName;
@property(copy) NSString *title; // @synthesize title=_title;
- (void)setView:(id)arg1;
- (id)view;
- (void).cxx_destruct;
- (void)setStoryboardSegueTemplates:(id)arg1;
- (id)storyboardSegueTemplates;
- (id)explicitStoryboardIdentifier;
- (void)setExplicitStoryboardIdentifier:(id)arg1;
- (id)effectiveStoryboardIdentifierPrefix;
- (void)setInheritedSimulatedMetrics:(id)arg1;
- (id)inheritedSimulatedMetrics;
- (struct CGSize)effectiveSimulatedContentSize;
- (struct CGSize)effectiveSimulatedViewSize;
- (void)unarchivePlaceholderTable:(id)arg1;
- (void)archivePlaceholderTable:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (Class)classForDocumentArchiver:(id)arg1;
- (Class)classForCoder;
- (id)ibTopLevelWindowTemplateForLayoutEngine:(id)arg1;
- (id)ibWindowWithCopiedViewHierarchySnapshotForLayoutEngine:(id)arg1 returningAddedRepresentedConstraintsForRepresentedViews:(id *)arg2;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;
- (void)ibCaptureDownstreamStoryboardPlaceholderTable:(id)arg1;
- (void)ibPopulateChildRelationOrder:(id)arg1;
- (id)ibWindow:(SEL)arg1 forUpdatingConstraintsInDocument:(id *)arg2;
- (id)ibTopLevelViewForLayoutEngine:(id)arg1;
- (BOOL)ibIsLegalArbitrationUnitRoot;
- (id)ibInheritableMetricsForDownstreamController:(id)arg1 viaSegue:(id)arg2;
- (id)ibEditorViewWithSuggestedSize:(struct CGSize)arg1 forDocument:(id)arg2;
- (id)ibDefaultViewForNewInstances;
- (id)ibEditorCanvasFrameControllerForDocument:(id)arg1;
- (Class)ibEditorClass;
- (id)ibPasteboardTypes;
- (id)ibDocumentationPropertyInfosForKeyPath:(id)arg1;
- (id)ibQualifyingInfoForDefaultLabel;
- (id)ibRuntimeClassName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

