/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEInterfaceBuilderCocoaIntegration/IBNSViewControllerEditor.h>

@class IBNSRelationshipSegueModeledViewControllerView, NSSet;

@interface IBNSRelationshipSegueModeledViewControllerEditor : IBNSViewControllerEditor
{
    IBNSRelationshipSegueModeledViewControllerView *_viewControllerEditorView;
    NSSet *_observers;
}

@property(retain) NSSet *observers; // @synthesize observers=_observers;
@property(retain) IBNSRelationshipSegueModeledViewControllerView *viewControllerEditorView; // @synthesize viewControllerEditorView=_viewControllerEditorView;
- (void).cxx_destruct;
- (void)resizeFrameViewWithEvent:(id)arg1 fromEditorCanvasFrameKnob:(long long)arg2;
- (id)viewEditorFrameController;
- (id)editedView;
- (id)editorView;
- (id)editedNSViewController;
- (void)noteDescendant:(id)arg1 didChangeProperty:(id)arg2 fromValue:(id)arg3;
- (void)willClose;
- (void)didOpen;
- (void)_teardownObservations;
- (void)childViewControllerChanged:(id)arg1 keyPath:(id)arg2 previousValue:(id)arg3;
- (void)_setupObservations;
- (id)editedViewController;
- (void)synchronizeWithEditedViewController;
- (id)initWithEditedObject:(id)arg1 parentEditor:(id)arg2 frameController:(id)arg3;

@end

