/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class NSImage;

@interface NSButtonCell (IBNSButtonCellIntegration)
+ (id)keyPathsForValuesAffectingIbInspectedType;
+ (id)keyPathsForValuesAffectingIbInspectedBehavior;
+ (id)keyPathsForValuesAffectingIbInspectedKeyEquivalent;
+ (id)keyPathsForValuesAffectingIbInspectedTitle;
+ (id)keyPathsForValuesAffectingIbQualifyingInfoForDefaultLabel;
+ (id)keyPathsForValuesAffectingIbWidgetType;
+ (id)keyPathsForValuesAffectingIbInspectedAlternateImage;
+ (id)keyPathsForValuesAffectingIbShadowedAlternateImage;
+ (id)keyPathsForValuesAffectingIbInspectedImage;
+ (id)keyPathsForValuesAffectingIbShadowedImage;
+ (id)keyPathsForValuesAffectingIbInspectedImagePosition;
+ (id)keyPathsForValuesAffectingIbShadowedButtonBehavior;
+ (id)keyPathsForValuesAffectingIbShadowedButtonCellType;
- (void)setIbInspectedType:(long long)arg1;
- (long long)ibInspectedType;
- (void)setIbInspectedBehavior:(long long)arg1;
- (long long)ibInspectedBehavior;
- (id)ibSuggestedKeyEquivalentForUpdatingTitleTo:(id)arg1;
- (id)ibTitlesToTypicalKeyEquivalents;
- (void)setIbInspectedKeyEquivalent:(id)arg1;
- (id)ibInspectedKeyEquivalent;
- (void)setIbInspectedTitle:(id)arg1;
- (id)ibInspectedTitle;
@property long long ibShadowedInset;
- (void)archiveWithDocumentArchiver:(id)arg1;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (id)ibOrderedSnapshotAttributesKeyPaths;
- (Class)ibEditorClass;
- (id)ibInitialConnectionLabelSearchTerm;
- (id)ibQualifyingInfoForDefaultLabel;
- (id)ibAcceptContentsOfPasteboard:(id)arg1 inDocument:(id)arg2 insertionContext:(id)arg3;
- (BOOL)ibCanAcceptContentsOfPasteboard:(id)arg1 inDocument:(id)arg2 targetChildRelation:(id *)arg3;
- (unsigned long long)ibPreferredMatrixMode;
- (Class)ibPreferredControlClass;
- (struct CGSize)ibPreferredSizeForSize:(struct CGSize)arg1;
- (id)ibPreferredSizeForSize:(struct CGSize)arg1 suggestedWidth:(char *)arg2 suggestedHeight:(char *)arg3 scaleAxesIndependently:(char *)arg4;
- (void)ibWarnings:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (BOOL)ibWantsBoundsIndicatorDuringTracking;
- (BOOL)ibIsBaselineAtIndex:(long long)arg1 inMotionWithKnob:(long long)arg2;
- (id)ibBaselineCount;
- (id)ibWidgetType;
- (void)setIbInspectedAlternateImage:(id)arg1;
- (id)ibInspectedAlternateImage;
@property(retain) NSImage *ibShadowedAlternateImage;
- (void)setIbInspectedImage:(id)arg1;
- (id)ibInspectedImage;
@property(retain) NSImage *ibShadowedImage;
- (void)setIbInspectedImagePosition:(unsigned long long)arg1;
- (unsigned long long)ibInspectedImagePosition;
@property unsigned long long ibShadowedImagePosition;
@property long long ibShadowedButtonBehavior;
- (id)ibDefaultFontForCurrentConfiguration;
- (BOOL)ibSwizzledIsAnimatingDefaultCell;
@property long long ibShadowedButtonCellType;
- (id)ibDocumentationPropertyInfosForKeyPath:(id)arg1;
- (void)ibAwakeInDocument:(id)arg1;
- (id)ibLocalConstraintInvalidatingAttributeKeyPaths;
- (id)ibLocalLocalizableStringsAttributeKeyPaths;
- (id)ibLocalAdditionalLocalizableAttributeKeyPaths;
- (id)ibButtonLocalLocalizableStringsAttributeKeyPaths;
- (id)ibLocalAttributeKeyPaths;
- (id)ibButtonLocalAttributesKeyPaths;
@end

