/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSText.h"

@interface NSText (IBNSTextIntegration)
- (void)setIbInspectedMaxSizeHeight:(double)arg1;
- (double)ibInspectedMaxSizeHeight;
- (void)setIbInspectedMaxSizeWidth:(double)arg1;
- (double)ibInspectedMaxSizeWidth;
- (void)setIbInspectedMinSizeHeight:(double)arg1;
- (double)ibInspectedMinSizeHeight;
- (void)setIbInspectedMinSizeWidth:(double)arg1;
- (double)ibInspectedMinSizeWidth;
@end

