/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTokenFieldCell.h"

@interface NSTokenFieldCell (IBNSTokenFieldIntegration)
+ (id)keyPathsForValuesAffectingIbWidgetType;
+ (id)keyPathsForValuesAffectingObjectValue;
- (BOOL)xmlCoder:(id)arg1 shouldEncodeObject:(id *)arg2 forKey:(id)arg3 context:(id)arg4;
- (id)xmlCoderEncodingCallbackContext:(id)arg1;
- (id)ibWidgetType;
- (id)ibOrderedSnapshotAttributesKeyPaths;
@end

