/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSVisualEffectView.h"

@interface NSVisualEffectView (IBNSVisualEffectViewIntegration)
- (void)ibWarnings:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (BOOL)ibIsNSAppearanceContainer;
- (id)ibInspectedAppearancePopupValues;
- (id)ibInspectedAppearancePopupTitles;
- (id)ibDesignableContentView;
- (void)ibCustomizeForInsertionIntoDocument:(id)arg1 withObjects:(id)arg2 fromLibraryOrDifferentTargetRuntime:(BOOL)arg3 andInsertionContext:(id)arg4;
@end

