/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DVTFoundation/DTDKTeamBasedService.h>

@class NSDictionary;

@interface DTDKUpdateAppIDService : DTDKTeamBasedService
{
}

+ (id)keyPathsForValuesAffectingAppID;
+ (id)serviceForTeam:(id)arg1 andPlatform:(id)arg2 appIDID:(id)arg3 appIdName:(id)arg4 andFeatures:(id)arg5;
@property(readonly) NSDictionary *appID;

@end

