/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DVTKVOConditionValidator : NSObject
{
}

+ (BOOL)waitForCondition:(id)arg1 sourceObject:(void)arg2 keyPathAffectingConditionBlock:(id)arg3 timeout:(id)arg4;

@end

