/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DVTStringBuffer : NSObject
{
    unsigned long long bufferLen;
    unsigned long long bufferLoc;
    NSString *string;
    unsigned long long stringLen;
    unsigned long long stringLoc;
    unsigned short buffer[32];
    unsigned short curChar;
    unsigned short _unused;
}

- (void).cxx_destruct;

@end

