/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSError.h"

@interface NSError (DVTDeveloperAccountErrors)
+ (id)dvt_errorForDeveloperAccount:(id)arg1 errorCode:(long long)arg2 message:(id)arg3 recoverySuggestion:(id)arg4 recoveryOptions:(id)arg5 andRecoveryBlock:(id)arg6;
+ (id)dvt_errorForDeveloperAccount:(id)arg1 errorCode:(long long)arg2 userInfo:(id)arg3;
@end

