/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTextView.h"

@class XCIncrementalFinder;

@interface _XCIncrementalFinderTextView : NSTextView
{
    XCIncrementalFinder *_incrementalFinder;
}

@property(nonatomic, setter=_setIncrementalFinder:) XCIncrementalFinder *incrementalFinder; // @synthesize incrementalFinder=_incrementalFinder;
- (void)PBX_showGotoPanel:(id)arg1;
- (void)replaceAll:(id)arg1;
- (void)replaceAndFindPrevious:(id)arg1;
- (void)replaceAndFindNext:(id)arg1;
- (void)replace:(id)arg1;
- (void)findPrevious:(id)arg1;
- (void)findNext:(id)arg1;

@end

