/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsInterface/_XCOQMatcher.h>

@class NSMutableArray;

@interface _XCOQProjectsMatcher : _XCOQMatcher
{
    NSMutableArray *_buildFiles;
}

+ (void)initialize;
- (void)updateMatches;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (void)_takeProjectFilesForContext:(id)arg1;

@end

