/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PBXCompletionStrategy : NSObject
{
}

+ (void)initialize;
- (id)fullStringForPrefixString:(id)arg1 completionString:(id)arg2 isInitialPrefixMatch:(BOOL)arg3 basePath:(id)arg4;
- (id)matchesForPrefixString:(id)arg1 newPrefixString:(id *)arg2 basePath:(id)arg3;

@end

