/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsInterface/PBXEmacsEditorSpecification.h>

@interface PBXXEmacsEditorSpecification : PBXEmacsEditorSpecification
{
}

+ (BOOL)x11ServerIsInstalled;
+ (id)emacsPath;
+ (void)initialize;
- (BOOL)launchEmacs;
- (id)name;

@end

