/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSBrowserCell.h"

@class NSImage, SCMDirectoryEntry;

@interface SCMDirectoryCell : NSBrowserCell
{
    NSImage *_iconImage;
    SCMDirectoryEntry *_directoryEntry;
}

@property SCMDirectoryEntry *directoryEntry; // @synthesize directoryEntry=_directoryEntry;
@property NSImage *iconImage; // @synthesize iconImage=_iconImage;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setObjectValue:(id)arg1;
- (struct CGSize)cellSize;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

