/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet;

@interface XCDataTipsManager : NSObject
{
    NSMutableSet *_participants;
    struct __CFRunLoopObserver *_runLoopObserver;
}

+ (BOOL)mouseOverDataTipContext;
+ (BOOL)mouseOverDataTip:(BOOL)arg1;
+ (BOOL)mouseOverDataTipInWindow:(id)arg1 includeBuffer:(BOOL)arg2;
+ (BOOL)_mouseOverDataTipInWindow:(id)arg1 includeBuffer:(BOOL)arg2 mouseLocation:(struct CGPoint)arg3;
+ (BOOL)mouseOverWindow:(id)arg1;
+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
+ (void)cancelAllDataTips;
+ (void)_notifyEventHandlers;
+ (id)sharedDataTipsManager;
- (BOOL)checkParticipants;
- (void)removeParticipant:(id)arg1;
- (void)addParticipant:(id)arg1;
- (void)_stopRunLoopObserver;
- (void)_createRunLoopObserver;

@end

