/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSSplitViewDelegate-Protocol.h"

@protocol XCDiffComparatorViewDelegate <NSSplitViewDelegate>

@optional
- (void)diffComparatorViewSelectionDidChange:(id)arg1;
- (id)undoManagerForDiffComparatorView:(id)arg1;
- (id)diffComparatorView:(id)arg1 toolTipForDiffDescriptor:(id)arg2 mouseLocation:(struct CGPoint)arg3;
- (BOOL)diffComparatorView:(id)arg1 writeDiffDescriptorInRange:(struct _NSRange)arg2 toPasteboard:(id)arg3;
- (id)diffComparatorView:(id)arg1 writablePasteboardTypesForDiffDescriptorInRange:(struct _NSRange)arg2;
@end

