/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol XCDockableDragSource
- (id)submodules;
- (id)project;
- (id)dragSourceModule;
- (id)owningModuleForView:(id)arg1;
- (void)closeIfAppropriate;
- (id)removeSubmoduleAtIndex:(long long)arg1;
- (struct CGSize)sizeOfSourceModule:(long long)arg1;
- (BOOL)isDockTarget;
@end

