/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsInterface/XCElementViewDisplay.h>

@interface XCElementImageViewDisplay : XCElementViewDisplay
{
}

- (id)dataDelegateDataForDisplayer:(struct NSObject *)arg1;
- (void)displayer:(struct NSObject *)arg1 setDataDelegateData:(id)arg2;
- (BOOL)storesDataForDisplayer:(struct NSObject *)arg1;
- (void)installLocalDataDelegateForDisplayer:(struct NSObject *)arg1;
- (id)newDefaultView;
- (void)configureForControlSize:(unsigned long long)arg1 font:(id)arg2;

@end

