/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsInterface/XCElementDataDelegate.h>

@class NSObject;

@interface XCElementDataDelegateLocal : XCElementDataDelegate
{
    NSObject *_localData;
}

- (void)dealloc;
- (void)displayer:(struct NSObject *)arg1 writeData:(id)arg2;
- (id)readDataForDisplayer:(struct NSObject *)arg1;

@end

