/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsInterface/XCLogSectionAdapter.h>

@interface XCLogTargetHeadingAdapter : XCLogSectionAdapter
{
}

- (BOOL)dataNode:(id)arg1 doubleClickInColumn:(id)arg2;
- (id)targetHeadingBadgeForDataNode:(id)arg1;
- (id)secondRowStringForDataNode:(id)arg1;
- (id)titleFontForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;
- (double)_baseHeightOfRowForDataNode:(id)arg1;
- (BOOL)isTargetHeadingAdapter;

@end

