/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSFormatter.h"

@class NSTextField, XCRefactoringTransformationSetUpModule;

@interface XCRefactoringSetUpInputFormatter : NSFormatter
{
    XCRefactoringTransformationSetUpModule *transformationSetUpModule;
    NSTextField *textField;
}

- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;
- (BOOL)isPartialStringValid:(id *)arg1 proposedSelectedRange:(struct _NSRange *)arg2 originalString:(id)arg3 originalSelectedRange:(struct _NSRange)arg4 errorDescription:(id *)arg5;
- (id)stringForObjectValue:(id)arg1;
- (void)awakeFromNib;

@end

