/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "XCSpecification.h"

@interface XCUserCompletionSpecification : XCSpecification
{
}

+ (id)specificationRegistryName;
+ (id)specificationTypePathExtensions;
+ (id)localizedSpecificationTypeName;
+ (id)specificationType;
+ (Class)specificationTypeBaseClass;
- (id)excludeContexts;
- (id)includeContexts;
- (id)completions;
- (id)initWithPropertyListDictionary:(id)arg1 inDomain:(id)arg2;

@end

