/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDESplitViewDebugArea.h"

#import "DVTReplacementViewDelegate-Protocol.h"
#import "IDEDebuggingAdditionUIControllerLifeCycleObserver-Protocol.h"

@class GPUVariablesViewContentProvider, NSSegmentedControl;

// Not exported
@interface GPUDebugArea : IDESplitViewDebugArea <IDEDebuggingAdditionUIControllerLifeCycleObserver, DVTReplacementViewDelegate>
{
    NSSegmentedControl *_comparisonSelector;
    GPUVariablesViewContentProvider *_leftContentProvider;
    GPUVariablesViewContentProvider *_rightContentProvider;
    BOOL _alreadyAddedDebuggingAdditionUIControllerLifeCycleObserver;
}

- (void).cxx_destruct;
- (void)_comparisonSelectorClicked:(id)arg1;
- (void)_createComparisonSelector;
- (void)debuggingAddtionUIControllerInvalidated:(id)arg1;
- (void)debuggingAddtionUIControllerUpdated:(id)arg1;
- (Class)classOfDebuggingAddtionUIControllerInterestedIn;
- (id)toolTipForShowRightViewButton;
- (id)toolTipForShowLeftViewButton;
- (id)stateSavingIdentifier;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;

@end

