/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DYFrameBufferAttachment <NSObject>
@property(readonly, nonatomic) unsigned int textureLayer;
@property(readonly, nonatomic) unsigned int textureLevel;
@property(readonly, nonatomic) unsigned int internalID;
@property(readonly, nonatomic) unsigned int objectID;
@property(readonly, nonatomic) unsigned int objectType;
@property(readonly, nonatomic) unsigned int location;
@end

