/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTViewController.h"

@class IDEBarGraph;

@interface IDEDebugGaugeReportThroughputGaugeViewController : DVTViewController
{
    IDEBarGraph *_graphView;
}

@property(retain, nonatomic) IDEBarGraph *graphView; // @synthesize graphView=_graphView;
- (void).cxx_destruct;
- (void)loadView;
- (id)init;

@end

