/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DBGLocationAdditionalLabelValuePairProvider-Protocol.h"

@class DBGDataValue;

@interface DBGCLLocationAdditionalLabelValuePairProvider : NSObject <DBGLocationAdditionalLabelValuePairProvider>
{
    DBGDataValue *_dataValue;
    BOOL _wasCancelled;
}

- (void).cxx_destruct;
- (id)blockStartAddress;
- (void)cancel;
- (void)_runExpression:(id)arg1 withFailureHandler:(id)arg2 completionHandler:(void)arg3;
- (void)provideLabelValuePairs:(id)arg1;
- (id)initWithDataValue:(id)arg1;

@end

