/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewController.h"

#import "IDEVariablesViewQuickLookProvider-Protocol.h"
#import "QLPreviewViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, NSURL, NSView, QLPreviewView;

@interface DBGNSURLQuickLookProvider : NSViewController <QLPreviewViewDelegate, IDEVariablesViewQuickLookProvider>
{
    NSURL *_url;
    int _loadedState;
    QLPreviewView *_qlPreviewView;
    NSLayoutConstraint *_qlPreviewViewWidth;
    NSLayoutConstraint *_qlPreviewViewHeight;
}

@property(retain) NSLayoutConstraint *qlPreviewViewHeight; // @synthesize qlPreviewViewHeight=_qlPreviewViewHeight;
@property(retain) NSLayoutConstraint *qlPreviewViewWidth; // @synthesize qlPreviewViewWidth=_qlPreviewViewWidth;
@property(retain) QLPreviewView *qlPreviewView; // @synthesize qlPreviewView=_qlPreviewView;
@property int loadedState; // @synthesize loadedState=_loadedState;
- (void).cxx_destruct;
- (void)previewView:(id)arg1 didLoadPreviewItem:(id)arg2;
@property(readonly) NSURL *existingURLToOpen;
- (void)cancelLoading;
@property(readonly) NSView *quickLookView;
- (void)loadView;
- (id)initWithDataValue:(id)arg1 options:(id)arg2;

// Remaining properties
@property(readonly) NSString *extensionForTemporaryFile;

@end

