/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEEditor.h"

#import "DBGSceneViewControllerDelegate-Protocol.h"

@class DBGSceneViewController, DBGSceneViewRangeSliderCell, DBGViewDebuggerAdditionUIController, DBGViewDebuggerDocument, DBGViewWindow, DVTBorderedView, DVTDelayedInvocation, DVTObservingToken, NSArray, NSButton, NSPopUpButton, NSProgressIndicator, NSSegmentedControl, NSSet, NSSlider, NSView;

@interface DBGViewDebuggerEditor : IDEEditor <DBGSceneViewControllerDelegate>
{
    NSArray *_currentSelectedItems;
    DBGViewWindow *_selectedWindow;
    DBGViewDebuggerAdditionUIController *_viewDebuggerUIController;
    DVTDelayedInvocation *_handleOutputSelectionChangeInvocation;
    DVTObservingToken *_showOnlyInterestingViewObjectsObservingToken;
    DVTObservingToken *_showOnlyVisibleViewObjectsObservingToken;
    DVTObservingToken *_navigatorOutputSelectionObserver;
    id <DVTCancellable> _viewDebuggerAdditionUIControllerObservingToken;
    NSSet *_selectedConstraintSet;
    DBGSceneViewController *_sceneViewController;
    DVTBorderedView *_backgroundView;
    DVTBorderedView *_toolBarView;
    NSSegmentedControl *_zoomSegmentedControl;
    NSPopUpButton *_nodeContentModePopupButton;
    NSButton *_resetViewButton;
    NSSlider *_zDistanceSlider;
    NSButton *_constraintsButton;
    NSSlider *_viewRangeSlider;
    DBGSceneViewRangeSliderCell *_viewRangeSliderCell;
    NSButton *_showClippedContentButton;
    NSView *_percentLoadedView;
    NSProgressIndicator *_percentLoadedIndicator;
}

+ (id)defaultViewNibBundle;
+ (id)defaultViewNibName;
@property __weak NSProgressIndicator *percentLoadedIndicator; // @synthesize percentLoadedIndicator=_percentLoadedIndicator;
@property(retain) NSView *percentLoadedView; // @synthesize percentLoadedView=_percentLoadedView;
@property __weak NSButton *showClippedContentButton; // @synthesize showClippedContentButton=_showClippedContentButton;
@property __weak DBGSceneViewRangeSliderCell *viewRangeSliderCell; // @synthesize viewRangeSliderCell=_viewRangeSliderCell;
@property __weak NSSlider *viewRangeSlider; // @synthesize viewRangeSlider=_viewRangeSlider;
@property __weak NSButton *constraintsButton; // @synthesize constraintsButton=_constraintsButton;
@property __weak NSSlider *zDistanceSlider; // @synthesize zDistanceSlider=_zDistanceSlider;
@property __weak NSButton *resetViewButton; // @synthesize resetViewButton=_resetViewButton;
@property __weak NSPopUpButton *nodeContentModePopupButton; // @synthesize nodeContentModePopupButton=_nodeContentModePopupButton;
@property __weak NSSegmentedControl *zoomSegmentedControl; // @synthesize zoomSegmentedControl=_zoomSegmentedControl;
@property __weak DVTBorderedView *toolBarView; // @synthesize toolBarView=_toolBarView;
@property __weak DVTBorderedView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain) DBGSceneViewController *sceneViewController; // @synthesize sceneViewController=_sceneViewController;
@property(retain) NSSet *selectedConstraintSet; // @synthesize selectedConstraintSet=_selectedConstraintSet;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)_windowForViewObject:(id)arg1;
- (void)_showContextualJumpMenu;
@property(readonly) DBGViewDebuggerDocument *viewDebuggerDocument;
- (void)mouseClickedViewObject:(id)arg1 withEvent:(id)arg2;
- (void)zoomOutCanvas:(id)arg1;
- (void)zoomActualCanvas:(id)arg1;
- (void)zoomInCanvas:(id)arg1;
- (void)toggleClippingOfContent:(id)arg1;
- (void)toggleShowConstraints:(id)arg1;
- (void)resetViewButtonPressed:(id)arg1;
- (void)zoomButtonPressed:(id)arg1;
- (void)zDistanceSliderChanged:(id)arg1;
- (void)_reloadSceneViewController;
@property DBGViewWindow *selectedWindow;
@property(retain) NSArray *currentSelectedItems;
- (void)_setCurrentSelectedItemsFromDocumentLocations:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (id)_documentLocationsFromCurrentSelectedItems;
- (void)selectDocumentLocations:(id)arg1;
- (void)_handleNavigatorOutputSelectionChanged;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)_handleViewDebuggerPercentLoadedChanged;
- (void)_configureNodeContentModePopUp;
- (void)loadView;

@end

