/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface HFByteSliceFileOperationQueueEntry : NSObject
{
    unsigned long long length;
    unsigned long long offset;
    char *bytes;
    unsigned long long source;
}

@end

