/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol DBGDebugSessionBreakpointLifeCycleDelegate
- (void)watchpointEnablementChanged:(id)arg1;
- (void)breakpointLocationEnablementChanged:(id)arg1;
- (void)breakpointLocationIgnoreCount:(id)arg1;
- (void)breakpointLocationConditionChanged:(id)arg1;
- (void)breakpointEnablementChanged:(id)arg1;
- (void)breakpointIgnoreCountChanged:(id)arg1;
- (void)breakpointConditionChanged:(id)arg1;
- (void)deleteWatchpoint:(id)arg1;
- (void)activationStateChanged:(BOOL)arg1 forBreakpoints:(id)arg2;
- (void)deleteBreakpoint:(id)arg1;
- (void)createBreakpointIfNecessary:(id)arg1;
@end

