/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DBGProcess.h"

@class NSMutableArray;

// Not exported
@interface DBGLLDBProcess : DBGProcess
{
    struct SBProcess _lldbProcess;
    NSMutableArray *_previousDBGThreads;
    BOOL _needSharedLibraryUpdate;
    BOOL _isDoingAsyncAttach;
    unsigned long long _addressByteSize;
    BOOL _isCoreFile;
}

@property BOOL isCoreFile; // @synthesize isCoreFile=_isCoreFile;
- (unsigned long long)addressByteSize;
@property BOOL isDoingAsyncAttach; // @synthesize isDoingAsyncAttach=_isDoingAsyncAttach;
@property BOOL needSharedLibraryUpdate; // @synthesize needSharedLibraryUpdate=_needSharedLibraryUpdate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)invalidateUnsuedThreadsAfterCallToSetThreads:(id)arg1;
- (void)_assertIsLLDBSessionThread;
- (void)reflectLLDBSelectedThreadAndFrame;
- (BOOL)_isExceptionBreakpoint:(unsigned long long)arg1;
- (void)_updateDBGThreadStateAndStopReason:(id)arg1 fromLLDBThread:(struct SBThread)arg2 isCurrentThread:(BOOL)arg3;
- (BOOL)isLLDBExceptionFatal:(unsigned long long)arg1;
- (void)clearThreadAndStackStates;
- (id)currentThreadFromLLDB;
- (void)_readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 dataToReadInto:(id)arg3 shouldCancel:(id)arg4 resultHandler:(id)arg5;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (void)rawMemoryDataForAddressExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (id)updateThreadListAndGetCurrentThread:(id *)arg1;
- (struct SBThread)_currentLLDBThread;
- (void)_updateSharedLibraries;
- (id)initWithDebugSession:(id)arg1 lldbProcess:(struct SBProcess)arg2;

@end

