/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DBGStackFrame.h"

#import "DBGLLDBInvalidation-Protocol.h"
#import "DBGStackFrameDelegate-Protocol.h"

@class NSArray, NSMutableSet;

// Not exported
@interface DBGLLDBStackFrame : DBGStackFrame <DBGStackFrameDelegate, DBGLLDBInvalidation>
{
    struct SBFrame _lldbFrame;
    struct SBValueList _lldbVariables;
    struct SBValueList _lldbRegisters;
    NSArray *_variables;
    NSArray *_locals;
    NSArray *_arguments;
    NSArray *_fileStatics;
    NSArray *_registers;
    NSMutableSet *_expressionDataValuesToInvalidate;
    BOOL _markedForInvalidationFromTheSessionThread;
}

@property BOOL markedForInvalidationFromTheSessionThread; // @synthesize markedForInvalidationFromTheSessionThread=_markedForInvalidationFromTheSessionThread;
@property(copy, nonatomic) NSArray *fileStatics; // @synthesize fileStatics=_fileStatics;
@property(copy, nonatomic) NSArray *registers; // @synthesize registers=_registers;
@property(copy, nonatomic) NSArray *arguments; // @synthesize arguments=_arguments;
@property(copy, nonatomic) NSArray *locals; // @synthesize locals=_locals;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)stackFrame:(id)arg1 requestDisassembly:(id)arg2;
- (id)dataValuesToInvalidate;
- (id)_lldbSession;
- (id)disassemble;
- (void)_getRegistersFromLLDBOnSessionThread;
- (void)_getFileStaticsFromLLDBOnSessionThread;
- (void)_getLocalsFromLLDBOnSessionThread;
- (void)_getArgumentsFromLLDBOnSessionThread;
- (id)_evaluateExpressionOnSessionThread:(id)arg1;
- (void)_forceSummaryToLoadAndUpdateSummaryIfNecessary:(id)arg1;
- (void)_getDataValueForExpressionOnSessionThread:(id)arg1 onQueue:(struct dispatch_queue_s *)arg2 withResultBlock:(id)arg3;
- (void)requestDataValueForExpression:(id)arg1 atBlockStartAddress:(id)arg2 onQueue:(struct dispatch_queue_s *)arg3 withResultBlock:(id)arg4;
- (void)requestDataValueForSymbol:(id)arg1 symbolKind:(id)arg2 atLocation:(id)arg3 onQueue:(struct dispatch_queue_s *)arg4 withResultBlock:(id)arg5;
- (id)_findSymbolWithName:(id)arg1 symbolKind:(id)arg2 atLocation:(id)arg3;
- (void)getFrameVariables;
- (void)_addSessionThreadAction:(id)arg1;
- (id)_weakSelf;
- (BOOL)_isSessionThread;
- (void)_assertNotMarkedForInvalidationAndOnSessionThread;
- (void)_setReturnValueFromInitIfNecessary;
- (id)initWithParentThread:(id)arg1 frameNumber:(id)arg2 framePointer:(id)arg3 name:(id)arg4 lldbFrame:(struct SBFrame)arg5;

@end

