/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@interface CSPaginatedResult : NSObject
{
    NSString *guid;
    NSNumber *startIndex;
    NSArray *results;
    NSNumber *total;
}

+ (void)initialize;
@property(retain) NSNumber *total; // @synthesize total;
@property(retain) NSArray *results; // @synthesize results;
@property(retain) NSNumber *startIndex; // @synthesize startIndex;
@property(retain) NSString *guid; // @synthesize guid;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

