/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DYShaderProfilerShaderInfo.h"

@interface DYMTLShaderProfilerShaderInfo : DYShaderProfilerShaderInfo
{
    unsigned long long _libraryId;
}

@property(nonatomic) unsigned long long libraryId; // @synthesize libraryId=_libraryId;
- (id)initWithLibraryId:(unsigned long long)arg1;

@end

