/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTImageAndTextCell.h"

@class NSColor;

@interface GPUNavigatorCompressedDataCell : DVTImageAndTextCell
{
    NSColor *_color;
}

@property(copy) NSColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)init;
- (void)_ide_commonInit;

@end

