/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEModelFoundation/CDMProperty.h>

@class CDMEntity, NSNumber;

@interface CDMRelationship : CDMProperty
{
    CDMEntity *destinationEntity;
    unsigned long long minCount;
    unsigned long long maxCount;
    long long deletionRule;
    CDMRelationship *inverseRelationship;
    BOOL toMany;
    BOOL ordered;
}

+ (id)keyPathsForValuesAffectingInspectedToMany;
+ (id)keyPathsForValuesAffectingInspectedMaxCount;
+ (id)keyPathsForValuesAffectingInspectedMinCount;
+ (id)keyPathsForValuesAffectingInspectedInverseRelationship;
+ (id)keyPathsForValuesAffectingInspectedDestinationEntity;
+ (id)keyPathsForValuesAffectingFilteredRelationshipsWithNoInverse;
+ (id)keyPathsForValuesAffectingPossibleInverseRelationships;
@property(nonatomic) BOOL ordered; // @synthesize ordered;
@property(readonly) BOOL toMany; // @synthesize toMany;
@property(retain, nonatomic) CDMRelationship *inverseRelationship; // @synthesize inverseRelationship;
@property(nonatomic) long long deletionRule; // @synthesize deletionRule;
@property(readonly) unsigned long long maxCount; // @synthesize maxCount;
@property(readonly) unsigned long long minCount; // @synthesize minCount;
@property(retain, nonatomic) CDMEntity *destinationEntity; // @synthesize destinationEntity;
- (void).cxx_destruct;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)xmlElementAttributes;
- (void)stitchToRelatedModelElements;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 inModel:(id)arg2;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (BOOL)mapsDirectlyTo:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property NSNumber *inspectedToMany;
- (unsigned long long)inspectedMaxCountNonNilValue;
- (void)setInspectedMaxCount:(id)arg1;
- (id)inspectedMaxCount;
- (unsigned long long)inspectedMinCountNonNilValue;
- (void)setInspectedMinCount:(id)arg1;
- (id)inspectedMinCount;
@property(retain) CDMRelationship *inspectedInverseRelationship;
- (void)setDestinationEntity:(id)arg1 andInverseRelationship:(id)arg2;
@property(retain) CDMEntity *inspectedDestinationEntity;
- (id)filteredRelationshipsWithNoInverse;
- (id)possibleInverseRelationships;
- (void)setMinCount:(unsigned long long)arg1 maxCount:(unsigned long long)arg2 toMany:(BOOL)arg3;
- (void)primitiveInvalidate;
- (void)cascadeChangesToLegacyRelationships:(id)arg1 givenModernToLegacyEntityMapping:(id)arg2;
- (id)initWithLegacyRelationship:(id)arg1 andEntityMapping:(id)arg2 belongingToEntity:(id)arg3 inModel:(id)arg4;
- (id)initInModel:(id)arg1;
- (void)_registerUndoBlockForFoundRelationship:(id)arg1;
- (id)code_unorderedAccessors;
- (id)code_orderedAccessors;
- (id)code_relationshipDestinationClass;
- (id)code_relationshipSetType;

@end

