/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol XDUMLElement <NSObject>
- (id)elementForName:(id)arg1 inBucketNamed:(id)arg2;
- (id)elementsInAllBuckets;
- (unsigned long long)elementsCountInBucketNamed:(id)arg1;
- (id)elementsInBucketNamed:(id)arg1;
- (unsigned long long)indexForElement:(id)arg1 inBucketNamed:(id)arg2;
- (void)removeElementAtIndex:(unsigned long long)arg1 fromBucketNamed:(id)arg2;
- (void)removeElement:(id)arg1 fromBucketNamed:(id)arg2;
- (void)addElement:(id)arg1 toBucketNamed:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)deleteElementsBucketWithName:(id)arg1;
- (void)createElementsBucketWithName:(id)arg1 allowsDuplicates:(BOOL)arg2 preserveInsertOrder:(BOOL)arg3;
- (void)setUniqueElementID:(id)arg1;
- (id)createUniqueElementID;
- (id)uniqueElementID;
- (id)newStereotypeWithName:(id)arg1;
- (void)removeStereotype:(id)arg1;
- (void)addStereotype:(id)arg1;
- (id)stereotypes;
- (void)removeObjectFromOwnedCommentsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inOwnedCommentsAtIndex:(unsigned long long)arg2;
- (void)setOwner:(id)arg1;
- (id)ownedComments;
- (id)owner;
- (id)ownedElements;
@end

