/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTSourceControlIdentifiable-Protocol.h"

@class DVTSourceControlWorkingCopy, NSMapTable, NSMutableOrderedSet, NSOperationQueue, NSOrderedSet, NSString;

@interface DVTSourceControlWorkspace : NSObject <DVTSourceControlIdentifiable>
{
    NSMutableOrderedSet *_workingCopies;
    NSOperationQueue *_workspaceOperationQueue;
    NSString *__id;
    DVTSourceControlWorkingCopy *_primaryWorkingCopy;
    NSString *_relativePathToProject;
}

@property(copy) NSString *relativePathToProject; // @synthesize relativePathToProject=_relativePathToProject;
@property(retain) DVTSourceControlWorkingCopy *primaryWorkingCopy; // @synthesize primaryWorkingCopy=_primaryWorkingCopy;
@property(copy) NSString *_id; // @synthesize _id=__id;
- (void).cxx_destruct;
- (id)blueprintWithRemoteRepositories:(id)arg1 CompletionBlock:(id)arg2;
- (unsigned long long)compareToBlueprint:(id)arg1;
- (id)blueprintWithCompletionBlock:(id)arg1;
- (id)historySinceRevisionedBlueprint:(id)arg1 maximumLogItems:(long long)arg2 withCompletionBlock:(id)arg3;
- (id)workingCopyForRemoteRepository:(id)arg1 inBlueprint:(id)arg2;
- (id)historyFromRevisions:(id)arg1 toRevisions:(id)arg2 maximumLogItems:(long long)arg3 withCompletionBlock:(id)arg4;
@property(readonly) NSMapTable *initialRevisionsMapTable;
@property(readonly) NSMapTable *baseRevisionsMapTable;
- (id)_revisionTableWithRevison:(id)arg1;
- (id)forceUpdateWorkingCopiesFromBlueprint:(id)arg1 progressBlock:(id)arg2 completionBlock:(void)arg3;
- (id)forceUpdateWorkingCopiesFromRepositories:(id)arg1 progressBlock:(id)arg2 completionBlock:(void)arg3;
- (id)workingCopyForURL:(id)arg1;
- (id)initWithPrimaryWorkingCopy:(id)arg1 relativePathToProject:(id)arg2 workingCopies:(id)arg3;
- (id)initWithWorkingCopies:(id)arg1;
- (id)init;
- (void)sortWorkingCopies;
@property(readonly) NSOrderedSet *workingCopies;
- (BOOL)_isValid;
- (id)__id;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

