/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DVTSourceControl/DVTSourceControlRevisionLocation.h>

@class NSString;

@interface DVTSourceControlBranch : DVTSourceControlRevisionLocation
{
    unsigned long long _options;
    NSString *_identifier;
}

+ (BOOL)supportsSecureCoding;
+ (id)defaultImage;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
@property unsigned long long options; // @synthesize options=_options;
- (void).cxx_destruct;
- (id)description;
@property(readonly, getter=isNewBranch) BOOL newBranch;
@property(readonly, getter=isPrimaryBranch) BOOL primaryBranch;
- (id)pathLocationForBranchAndTagLocations:(id)arg1;
@property(readonly) NSString *name;
- (id)displayName;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)dictionaryRepresentationWithOptions:(unsigned long long)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithNewBranchName:(id)arg1;
- (id)initWithBranchPathLocation:(id)arg1 branchAndTagLocations:(id)arg2;
- (id)initWithBranchName:(id)arg1 primaryBranch:(BOOL)arg2;
- (id)_init;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

