/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTSourceControlIdentifiable-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class DVTSourceControlRemoteRepository, DVTSourceControlRevision, DVTSourceControlSystem, NSArray, NSDictionary, NSString, NSURL;

@interface DVTSourceControlRepository : NSObject <DVTSourceControlIdentifiable, NSSecureCoding, NSCopying>
{
    NSString *__id;
    NSURL *_URL;
    NSString *_identifier;
    DVTSourceControlSystem *_sourceControlSystem;
    NSDictionary *_cachedRemoteRepositories;
    DVTSourceControlRemoteRepository *_primaryRemoteRepository;
    DVTSourceControlRevision *_cachedHeadRevision;
    NSArray *_cahcedBranches;
    NSArray *_cachedTags;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSArray *cachedTags; // @synthesize cachedTags=_cachedTags;
@property(readonly) NSArray *cahcedBranches; // @synthesize cahcedBranches=_cahcedBranches;
@property(readonly) DVTSourceControlRevision *cachedHeadRevision; // @synthesize cachedHeadRevision=_cachedHeadRevision;
@property(readonly) DVTSourceControlRemoteRepository *primaryRemoteRepository; // @synthesize primaryRemoteRepository=_primaryRemoteRepository;
@property(readonly) NSDictionary *cachedRemoteRepositories; // @synthesize cachedRemoteRepositories=_cachedRemoteRepositories;
@property(retain) DVTSourceControlSystem *sourceControlSystem; // @synthesize sourceControlSystem=_sourceControlSystem;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain) NSURL *URL; // @synthesize URL=_URL;
@property(copy) NSString *_id; // @synthesize _id=__id;
- (void).cxx_destruct;
- (id)addRemoteRepository:(id)arg1 withName:(id)arg2 completionBlock:(id)arg3;
- (id)listRemoteRepositoriesWithCompletionBlock:(id)arg1;
- (id)listBranchesForBranchAndTagLocations:(id)arg1 completionBlock:(id)arg2;
- (id)listBranchesWithCompletionBlock:(id)arg1;
- (id)revisionOfLocation:(id)arg1 branchAndTagLocations:(id)arg2 completionBlock:(id)arg3;
- (id)headRevisionWithCompletionBlock:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithURL:(id)arg1 identifier:(id)arg2 sourceControlSystem:(id)arg3;
- (id)initWithURL:(id)arg1 sourceControlSystem:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)__id;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

