/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface TreeSearcher : NSObject
{
    struct patternElement *_pattern;
}

+ (BOOL)searchString:(id)arg1 matchesInTree:(id)arg2;
+ (id)findSearchString:(id)arg1 inTrees:(id)arg2;
+ (id)findSearchString:(id)arg1 inTree:(id)arg2;
+ (id)searcherWithSearchString:(id)arg1;
- (id)findFirstInTree:(id)arg1 withDiscriminator:(void *)arg2;
- (id)findFirstInTree:(id)arg1 withStop:(void *)arg2;
- (id)findFirstInTree:(id)arg1;
- (id)findAllInTree:(id)arg1 withStop:(void *)arg2;
- (id)findAllInTree:(id)arg1 withDiscriminator:(void *)arg2;
- (id)findAllInTree:(id)arg1;
- (id)findAllInTree:(id)arg1 withPattern:(struct patternElement *)arg2 withDiscriminator:(void *)arg3 withStop:(void *)arg4 stopOnMatch:(BOOL)arg5;
- (BOOL)matchInTree:(id)arg1;
- (BOOL)matchInTree:(id)arg1 withPattern:(struct patternElement *)arg2;
- (id)description;
- (id)subDescription:(struct patternElement *)arg1;
- (id)initWithSearchString:(id)arg1;
- (struct patternElement *)parseSearchString:(id)arg1;

@end

