/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDESourceTreeProvider-Protocol.h"

@interface Xcode3SourceTrees : NSObject <IDESourceTreeProvider>
{
}

+ (id)stringByExpandingSourceTreeReferencesInString:(id)arg1;

@end

