/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface Xcode3BuildSettingsDictionary : NSObject
{
}

+ (id)macroDefinitionTableByParsingXcconfigFileAtPath:(id)arg1 baseDirectoryPath:(id)arg2 error:(id *)arg3;

@end

