/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEDevkitRefactoring/DevkitExpression.h>

@class DevkitLocation, NSString;

@interface DevkitConstantExpression : DevkitExpression
{
    NSString *_stringValue;
    DevkitLocation *_stringContentLocation;
}

- (void).cxx_destruct;
- (id)shortDescription;
- (id)prettyPrint;
@property(readonly) DevkitLocation *stringContentLocation; // @synthesize stringContentLocation=_stringContentLocation;
- (id)stringValue;
- (void)setStringValue:(const char *)arg1;
- (id)initWithString:(id)arg1;

@end

