/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DevkitLocation, NSString;

@interface DevkitIncludeFileMapping : NSObject
{
    NSString *_actuallncludeFilename;
    DevkitLocation *_locationOfInclude;
}

@property(readonly) DevkitLocation *locationOfInclude; // @synthesize locationOfInclude=_locationOfInclude;
- (void).cxx_destruct;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)initWithFilename:(id)arg1 location:(id)arg2;

@end

