/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDraggingInfo-Protocol.h"

@protocol DTDraggingInfo <NSDraggingInfo>
- (struct CGPoint)draggingLocationOnScreen;
- (id)draggingSourceContext;
- (void)setDraggedImageStateNeedsUpdate:(BOOL)arg1;
- (struct CGSize)draggingStickiness;
- (void)setDraggingStickiness:(struct CGSize)arg1;
- (id)draggedImageState;
@end

