/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBuildable-Protocol.h"

@class DVTFileDataType, DVTFilePath, NSDictionary, NSString;

@protocol IDEBuildableProduct <IDEBuildable>
@property(readonly) NSDictionary *copiedFilePathsMap;
@property(readonly) BOOL productIsExecutable;
@property(readonly) NSDictionary *productSettings;
@property(readonly) NSString *iconPath;
@property(readonly) DVTFileDataType *fileDataType;
@property(readonly) DVTFilePath *filePath;
- (id)filePathForBuildParameters:(id)arg1;
- (id)productTypeIdentifier;
@end

