/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXBuildRule.h"

@interface PBXBuildRule (_Xcode3BuildRuleViewControllerExtensions)
+ (id)keyPathsForValuesAffectingIsScriptCommandRule;
+ (id)keyPathsForValuesAffectingIsFilePatternRule;
- (BOOL)isScriptCommandRule;
- (BOOL)isFilePatternRule;
- (id)commandExecutablePath;
- (id)commandLocalizedDescription;
@end

