/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Xcode3UI/Xcode3FrameworksBuildPhaseViewController.h>

@interface SummaryTargetFrameworksViewController : Xcode3FrameworksBuildPhaseViewController
{
}

- (double)contentOriginXOffsetForCapsuleView:(id)arg1;
- (double)capsuleView:(id)arg1 preferredContentViewWidthForCapsuleWidth:(double)arg2;
- (BOOL)capsuleViewCanBeRemoved:(id)arg1;
- (id)_draggedInternalItemsForDropOperation:(id)arg1;
- (BOOL)disclosedByDefault;
- (id)footerLabel;
- (id)titleForDisplay;

@end

