/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSFormatter.h"

@class Xcode3AppIDItemIdentifiersItemModelSet;

@interface Xcode3EvaluatedStringFormatter : NSFormatter
{
    Xcode3AppIDItemIdentifiersItemModelSet *_identifiers;
}

@property(readonly) Xcode3AppIDItemIdentifiersItemModelSet *identifiers; // @synthesize identifiers=_identifiers;
- (void).cxx_destruct;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;
- (id)editingStringForObjectValue:(id)arg1;
- (id)stringForObjectValue:(id)arg1;
- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;
- (id)_titleForContainerID:(id)arg1;
- (id)initWithIdentifiers:(id)arg1;

@end

