/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, NSArray, NSString;

@interface Xcode3ProjectTemplateDefinition : NSObject
{
    NSString *_beginning;
    NSString *_end;
    long long _indent;
    NSString *_name;
    NSString *_path;
    DVTFilePath *_filePath;
    NSString *_pathType;
    NSString *_fileType;
    NSString *_textEncoding;
    NSString *_lineEnding;
    id _tabWidth;
    id _indentWidth;
    id _usesTabs;
    id _wrapsLines;
    NSArray *_group;
    NSArray *_targetIndices;
    id _substituteMacros;
    NSArray *_groups;
    long long _sortOrder;
}

@property long long sortOrder; // @synthesize sortOrder=_sortOrder;
@property(retain) id groups; // @synthesize groups=_groups;
@property(retain) id substituteMacros; // @synthesize substituteMacros=_substituteMacros;
@property(retain) NSArray *targetIndices; // @synthesize targetIndices=_targetIndices;
@property(copy) NSArray *group; // @synthesize group=_group;
@property(retain) id wrapsLines; // @synthesize wrapsLines=_wrapsLines;
@property(retain) id usesTabs; // @synthesize usesTabs=_usesTabs;
@property(retain) id indentWidth; // @synthesize indentWidth=_indentWidth;
@property(retain) id tabWidth; // @synthesize tabWidth=_tabWidth;
@property(copy) NSString *lineEnding; // @synthesize lineEnding=_lineEnding;
@property(copy) NSString *textEncoding; // @synthesize textEncoding=_textEncoding;
@property(copy) NSString *fileType; // @synthesize fileType=_fileType;
@property(copy) NSString *pathType; // @synthesize pathType=_pathType;
@property(copy) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(copy) NSString *path; // @synthesize path=_path;
@property(copy) NSString *name; // @synthesize name=_name;
@property long long indent; // @synthesize indent=_indent;
@property(copy) NSString *end; // @synthesize end=_end;
@property(copy) NSString *beginning; // @synthesize beginning=_beginning;
- (void).cxx_destruct;
- (id)addFileReferenceToPath:(id)arg1 rootGroup:(id)arg2 targets:(id)arg3 basedOn:(id)arg4;
- (id)addFileReferenceForPath:(id)arg1 toGroup:(id)arg2 absolute:(BOOL)arg3;
- (void)applyPropertiesToReference:(id)arg1;
- (id)replacementTargetInTargets:(id)arg1;
- (BOOL)isAbsolutePathTypeInRootGroup:(id)arg1;
- (id)initWithPropertyList:(id)arg1 fromPath:(id)arg2 stringValueKey:(id)arg3;
- (id)init;

@end

