/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface Xcode3InfoSliceToInspectorXMLConverter : NSObject
{
    NSMutableDictionary *_cachedConversions;
}

+ (id)sharedConverter;
- (void).cxx_destruct;
- (id)inspectorXMLForSection:(id)arg1 column:(int)arg2;
- (id)_generateColumnnatedInspectorXMLForEntries:(id)arg1;
- (id)_generateInspectorXMLForEntries:(id)arg1;
- (id)init;

@end

