/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSString, PBXTarget, Xcode3Project;

@interface Xcode3TargetWrapper : NSObject
{
    PBXTarget *_pbxTarget;
    Xcode3Project *_project;
    NSString *_name;
    NSImage *_image;
    BOOL _selected;
}

@property(readonly) NSImage *image; // @synthesize image=_image;
@property(readonly) NSString *name; // @synthesize name=_name;
@property BOOL selected; // @synthesize selected=_selected;
@property(readonly) Xcode3Project *project; // @synthesize project=_project;
@property(readonly) PBXTarget *pbxTarget; // @synthesize pbxTarget=_pbxTarget;
- (void).cxx_destruct;
- (id)initWithPBXTarget:(id)arg1 project:(id)arg2;

@end

