/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Xcode3Project.h"

@interface Xcode3Project (Xcode3ProjectNameRefactoring)
- (void)_changeContainerFilePath:(id)arg1 inContext:(id)arg2;
- (void)_renameProjectOldName:(id)arg1 newName:(id)arg2 inContext:(id)arg3;
- (void)_renameProjectSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
@end

