/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface Xcode3SourceTreeDescriptor : NSObject
{
    NSString *_settingName;
    NSString *_displayName;
    NSString *_path;
}

- (void).cxx_destruct;
@property(copy) NSString *path;
- (void)_setPath:(id)arg1;
@property(copy) NSString *displayName;
- (void)_setDisplayName:(id)arg1;
@property(copy) NSString *settingName;
- (void)_setSettingName:(id)arg1;
- (void)didChange;

@end

