/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEProjectItemViewController.h"

@class NSView, Xcode3AppIDItemIdentifiersTableViewController, Xcode3ApplicationGroupsItemModel;

@interface Xcode3ApplicationGroupsItemViewController : IDEProjectItemViewController
{
    NSView *_identifiersSlice;
    Xcode3AppIDItemIdentifiersTableViewController *_identifiersTableViewController;
}

@property(retain) Xcode3AppIDItemIdentifiersTableViewController *identifiersTableViewController; // @synthesize identifiersTableViewController=_identifiersTableViewController;
@property(retain) NSView *identifiersSlice; // @synthesize identifiersSlice=_identifiersSlice;
- (void).cxx_destruct;
- (void)loadView;

// Remaining properties
@property(readonly, nonatomic) Xcode3ApplicationGroupsItemModel *model;

@end

