/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEViewController.h"

@class DVTDisclosureView, DVTInfoPlistValueCell, NSString;

@interface Xcode3InAppPurchaseTargetEditor : IDEViewController
{
    id _targetViewController;
    DVTInfoPlistValueCell *_productIdentifierCell;
    DVTDisclosureView *_disclosureView;
}

+ (id)keyPathsForValuesAffectingContentVersion;
+ (id)keyPathsForValuesAffectingProductIdentifier;
+ (id)keyPathsForValuesAffectingProductName;
@property(retain, nonatomic) id targetViewController; // @synthesize targetViewController=_targetViewController;
- (void).cxx_destruct;
- (id)infoPlistValueCell:(id)arg1 expandedValueForString:(id)arg2;
@property(retain) NSString *contentVersion;
@property(retain) NSString *productIdentifier;
- (void)productIdentifierChanged:(id)arg1;
- (void)refreshProductIdentifier;
@property(retain) NSString *productName;
- (void)loadView;

@end

