/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFileDataType, DVTLocale, Xcode3LocalizationsInspector;

@interface Xcode3LocalizationsInspectorLocale : NSObject
{
    BOOL _localized;
    DVTLocale *_locale;
    DVTFileDataType *_fileDataType;
    Xcode3LocalizationsInspector *_locInspector;
}

+ (id)keyPathsForValuesAffectingImage;
@property(readonly) Xcode3LocalizationsInspector *locInspector; // @synthesize locInspector=_locInspector;
@property BOOL localized; // @synthesize localized=_localized;
@property(retain) DVTFileDataType *fileDataType; // @synthesize fileDataType=_fileDataType;
@property(readonly) DVTLocale *locale; // @synthesize locale=_locale;
- (void).cxx_destruct;
- (id)image;
- (id)initWithLocale:(id)arg1 fileDataType:(id)arg2 localized:(BOOL)arg3 locInspector:(id)arg4;

@end

