/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTMessageBubbleAnnotation.h"

@class DVTDevice, IDETest, NSString;

@interface _IDETestPerformanceMetricAnnotation : DVTMessageBubbleAnnotation
{
    DVTDevice *_targetDevice;
    NSString *_targetArchitecture;
    IDETest *_test;
}

+ (id)locationForTest:(id)arg1 inDocument:(id)arg2;
+ (id)defaultTheme;
@property __weak IDETest *test; // @synthesize test=_test;
@property(copy) NSString *targetArchitecture; // @synthesize targetArchitecture=_targetArchitecture;
@property(retain) DVTDevice *targetDevice; // @synthesize targetDevice=_targetDevice;
- (void).cxx_destruct;
- (BOOL)validateMenuItem:(id)arg1;
- (void)contextMenu_revealInReport:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForPersistentAllocations:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForTotalAllocations:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForTime:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForAllMetrics:(id)arg1;
- (void)contextMenu_performSelector:(SEL)arg1 sender:(id)arg2;
- (void)updateBaselineForPerformanceMetricWithIdentifier:(id)arg1 average:(id)arg2 maxStandardDeviation:(id)arg3;
- (id)baselineRecordAndFilePath:(id *)arg1 error:(id *)arg2;
- (id)initWithTest:(id)arg1;

@end

