/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEGeniusResultNavigableRepresentedObject-Protocol.h"

@class DVTDocumentLocation, DVTFileDataType, NSString, NSURL;

@interface IDESingleFileProcessingItem : NSObject <IDEGeniusResultNavigableRepresentedObject>
{
    NSString *_name;
    DVTDocumentLocation *_location;
    DVTFileDataType *_type;
    NSURL *_fileURL;
}

@property(readonly) DVTFileDataType *type; // @synthesize type=_type;
@property(readonly) DVTDocumentLocation *documentLocation; // @synthesize documentLocation=_location;
@property(readonly) NSURL *originalFileURL; // @synthesize originalFileURL=_fileURL;
- (void).cxx_destruct;
- (id)geniusResult_identifierForManualCategory;
- (id)geniusResult_identifierForGeniusCategory;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (id)initWithName:(id)arg1 originalFileURL:(id)arg2 generatedContentLocation:(id)arg3 type:(id)arg4;

@end

