/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEEditorDocumentPreviewProvider.h"

@class DVTLayoutManager, DVTPointerArray;

@interface IDESourceCodePreviewProvider : IDEEditorDocumentPreviewProvider
{
    DVTPointerArray *_rowHeights;
    DVTLayoutManager *_documentLayoutManager;
    DVTLayoutManager *_previewLayoutManager;
}

- (void).cxx_destruct;
- (id)generateViewWithRect:(struct CGRect)arg1;
- (void)updateSelectedLocation:(id)arg1 forView:(id)arg2 atIndex:(long long)arg3 preview:(BOOL)arg4;
- (void)populateView:(id)arg1 forPreviewAtIndex:(long long)arg2;
- (void)populateView:(id)arg1 forDocumentAtIndex:(long long)arg2;
- (double)minimumHeightForRowAtIndex:(long long)arg1 withWidth:(double)arg2;
- (id)previewViewIdentifier;
- (BOOL)_setupSliceView:(id)arg1 forLocations:(id)arg2 focusOnLocation:(long long)arg3 inDocument:(id)arg4;

@end

