/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTAccessoryViewAnnotation.h"

@class IDESourceCodeBlameItem;

@interface IDESourceCodeBlameAccessoryViewAnnotation : DVTAccessoryViewAnnotation
{
    IDESourceCodeBlameItem *_blameItem;
}

@property(retain) IDESourceCodeBlameItem *blameItem; // @synthesize blameItem=_blameItem;
- (void).cxx_destruct;

@end

