/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (XCPropertyValueAdditions)
- (id)propertyValueDebugDescription;
- (id)valueByApplyingOperator:(id)arg1 inContext:(id)arg2;
- (id)_stringValueByEscapingWhitespace;
- (id)_stringValueByApplyingPathOperator:(id)arg1;
- (id)evaluateAsArrayInContext:(id)arg1;
- (id)evaluateAsArrayInContext:(id)arg1 withNestingState:(const void *)arg2;
- (id)evaluateAsStringInContext:(id)arg1;
- (id)evaluateAsStringInContext:(id)arg1 withNestingState:(const void *)arg2;
@end

