/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCPropertyDefinition.h>

@class XCPropertyValueDefinition;

@interface XCBooleanPropertyDefinition : XCPropertyDefinition
{
    XCPropertyValueDefinition *_valueDefns[2];
}

+ (BOOL)isListType;
+ (id)identifier;
- (id)argumentGenerationInfoProvidersForValue:(id)arg1;
- (id)localizedAllowedValues;
- (id)valueDefinitionForNO;
- (id)valueDefinitionForYES;
- (void)dealloc;
- (id)initFromPListDictionary:(id)arg1;

@end

