/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol XCSCMRequestDelegate
- (void)request:(id)arg1 reportedObject:(id)arg2 forKey:(id)arg3 forReference:(id)arg4;
- (void)request:(id)arg1 wasSuspendedWithCode:(id)arg2 message:(id)arg3;
- (void)request:(id)arg1 reportedError:(id)arg2;
- (void)request:(id)arg1 reportedMessage:(id)arg2;
- (void)request:(id)arg1 hadProgress:(long long)arg2 comment:(id)arg3;
- (void)request:(id)arg1 startedOperation:(id)arg2;
@end

