/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEQuickHelp/IDEQuickHelpController.h>

#import "NSPopoverDelegate-Protocol.h"

@class DVTObservingToken, IDEQuickHelpOneShotWindowContentViewController, NSPopover;

@interface IDEQuickHelpOneShotController : IDEQuickHelpController <NSPopoverDelegate>
{
    DVTObservingToken *_renderedContentSizeObservingToken;
    NSPopover *_popover;
    IDEQuickHelpOneShotWindowContentViewController *_contentViewController;
}

@property(retain) IDEQuickHelpOneShotWindowContentViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)popoverDidClose:(id)arg1;
- (void)closeQuickHelp;
- (void)showQuickHelp;
- (void)_contentDidChange:(id)arg1;
- (void)_configurePlaceholderView;
- (void)showPanelAtPoint:(struct CGPoint)arg1 withContentSize:(struct CGSize)arg2;
- (void)_adjustPlaceholderHeight;
- (id)mode;
- (id)contentCreator;
- (id)sourceExpressionWindow;

@end

