/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (SceneKit_SKEAdditions)
- (BOOL)ske_isRunningOn10_9OrLater;
- (id)ske_displayNameForUndoKVOKeypath:(id)arg1;
- (id)ske_undoKVOKeypaths;
@end

