/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDESceneKitEditor/SKEDocumentEdition.h>

@class SCNNode;

@interface SKEDocumentAddNodeAttributeEdition : SKEDocumentEdition
{
    SCNNode *_node;
    Class _nodeAttributeClass;
}

- (void).cxx_destruct;
- (BOOL)revert;
- (BOOL)apply;
- (BOOL)_edit:(BOOL)arg1;
- (id)initWithDocument:(id)arg1 node:(id)arg2 nodeAttributeClass:(Class)arg3;

@end

