/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class NSImage, NSString;

@interface SKENodeAttributeInfoCell : NSButtonCell
{
    NSString *_nodeAttributeInfo;
    NSImage *_image;
    double _alpha;
    BOOL _hidden;
}

+ (void)initialize;
@property BOOL hidden; // @synthesize hidden=_hidden;
- (void).cxx_destruct;
- (void)setControlViewWorkaround13788386:(id)arg1;
- (void)setControlView:(id)arg1;
@property(copy) NSString *nodeAttributeInfo;
- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawBezelWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSize;

@end

