/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEInspectorViewController.h"

@class DVTTableView, NSArrayController, NSString, SKEStaticTableViewInspectorContainerView;

@interface SKEStaticTableViewInspector : IDEInspectorViewController
{
    SKEStaticTableViewInspectorContainerView *containerView;
    DVTTableView *tableView;
    NSArrayController *arrayController;
    NSString *emptyContentString;
}

@property(copy, nonatomic) NSString *emptyContentString; // @synthesize emptyContentString;
@property(readonly) NSArrayController *arrayController; // @synthesize arrayController;
@property(readonly) DVTTableView *tableView; // @synthesize tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)loadView;
- (void)setContent:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

