/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEEditor.h"

#import "DVTReplacementViewDelegate-Protocol.h"
#import "SCNSceneRendererDelegate-Protocol.h"
#import "SKEContentsPickerPopUpButtonDataSource-Protocol.h"

@class DVTBorderedView, DVTDelayedInvocation, NSArray, NSSegmentedControl, NSString, SCNNode, SCNScene, SCNView, SKPSEDocument;

@interface SKPSEDocumentViewController : IDEEditor <DVTReplacementViewDelegate, SKEContentsPickerPopUpButtonDataSource, SCNSceneRendererDelegate>
{
    SCNView *_sceneView;
    NSSegmentedControl *_playingActionsSegmentedControl;
    NSSegmentedControl *_editingActionsSegmentedControl;
    DVTBorderedView *_backgroundView;
    NSArray *_currentSelectedItems;
    SCNScene *_scene;
    SCNNode *_cameraNode;
    SCNNode *_particleSystemNode;
    DVTDelayedInvocation *_restartInvocation;
    double _watchDogTime;
}

- (void).cxx_destruct;
- (id)suggestedImagesForContentsPicker:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (void)setCurrentSelectedItems:(id)arg1;
- (id)currentSelectedItems;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)scheduleRestartInvocationIfNeeded;
- (void)rightSegmentedControlAction:(id)arg1;
- (void)leftSegmentedControlAction:(id)arg1;
- (void)restartParticleSystem;
- (void)setPaused:(BOOL)arg1;
- (void)changeBackgroundColor:(id)arg1;
- (void)backgroundColorDidChange:(id)arg1;
- (void)renderer:(id)arg1 didRenderScene:(id)arg2 atTime:(double)arg3;
- (void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3;
- (void)resetPOVUsingSystemParticleProperties;
- (void)buildScene;
- (id)particleSystem;
- (BOOL)canBecomeMainViewController;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)primitiveInvalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) SKPSEDocument *document;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

