/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEIndexClassSymbol, NSString;

@interface IDECDDataModelImportItem : NSObject
{
    IDEIndexClassSymbol *_classSymbol;
    BOOL _shouldImport;
}

@property BOOL shouldImport; // @synthesize shouldImport=_shouldImport;
@property(readonly) IDEIndexClassSymbol *classSymbol; // @synthesize classSymbol=_classSymbol;
- (void).cxx_destruct;
@property(readonly) NSString *name;
- (id)initWithClassSymbol:(id)arg1;

@end

