/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDELanguageIdentification : NSObject
{
}

+ (unsigned long long)languageFamilyForFiles:(id)arg1;
+ (unsigned long long)languageFamilyForFile:(id)arg1;
+ (unsigned long long)languageFamilyForFileReferences:(id)arg1;
+ (unsigned long long)languageFamilyForFileReference:(id)arg1;
+ (unsigned long long)languageFamilyForFileDataType:(id)arg1;
+ (unsigned long long)languageFamilyForFileDataUTIs:(id)arg1;
+ (unsigned long long)languageFamilyForFileDataUTI:(id)arg1;

@end

