/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class _XCSUIIntegrationIssueView;

@interface _XCSUIIssueSelectionManager : NSObject
{
    _XCSUIIntegrationIssueView *_currentSelectedIssueView;
}

+ (id)sharedSelectionManager;
- (void).cxx_destruct;
- (void)mouseDownInIssueView:(id)arg1;

@end

