/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton;

@interface _XCSUIIssueSectionView : NSView
{
    NSButton *_sectionTitleButton;
}

@property __weak NSButton *sectionTitleButton; // @synthesize sectionTitleButton=_sectionTitleButton;
- (void).cxx_destruct;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;

@end

