/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEAssistantContext.h"

@class DVTSourceControlWorkspaceBlueprint, IDEScheme, IDEWorkspaceTabController, NSArray, NSError, NSSet, NSString, NSWindow, XCSBot, XCSService, XCSUICreateBotAssistantContextWindowController;

@interface XCSUICreateBotAssistantContext : IDEAssistantContext
{
    XCSBot *_bot;
    BOOL _preserveExistingServerBlueprint;
    BOOL _performsAnalyzeAction;
    BOOL _performsTestAction;
    BOOL _performsArchiveAction;
    BOOL _schemeSupportsDevices;
    BOOL _integrateUponCompletion;
    BOOL _hasSufficientSCMInfoToCreateBot;
    BOOL _creationComplete;
    BOOL _needsCommitAndPushUponCompletion;
    XCSUICreateBotAssistantContextWindowController *_assistantContextWindowController;
    NSString *_botName;
    NSString *_defaultBotName;
    XCSService *_service;
    DVTSourceControlWorkspaceBlueprint *_scmWorkspaceBlueprint;
    DVTSourceControlWorkspaceBlueprint *_existingSCMWorkspaceBlueprint;
    NSString *_existingBotID;
    IDEScheme *_scheme;
    unsigned long long _buildsFromCleanSchedule;
    long long _initialRepositoryAuthenticationStatus;
    long long _preflightRepositoryAuthenticationStatus;
    NSSet *_preflightIgnoredRepositoryIdentifiers;
    NSArray *_triggers;
    unsigned long long _testingDestinationType;
    unsigned long long _scheduleType;
    unsigned long long _periodicScheduleInterval;
    long long _weeklyScheduleDay;
    unsigned long long _hourOfIntegration;
    unsigned long long _minutesAfterHourToIntegrate;
    NSError *_createEditBotError;
    long long _rememberAuthenticationChoice;
    NSArray *_selectedTestingDeviceIDs;
}

+ (id)keyPathsForValuesAffectingSchemeSupportsArchiveAction;
+ (id)keyPathsForValuesAffectingPerformsArchiveAction;
+ (id)keyPathsForValuesAffectingSchemeSupportsTestAction;
+ (id)keyPathsForValuesAffectingPerformsTestAction;
+ (id)keyPathsForValuesAffectingSchemeSupportsAnalyzeAction;
+ (id)keyPathsForValuesAffectingPerformsAnalyzeAction;
+ (id)keyPathsForValuesAffectingDefaultBotName;
@property(copy, nonatomic) NSArray *selectedTestingDeviceIDs; // @synthesize selectedTestingDeviceIDs=_selectedTestingDeviceIDs;
@property(nonatomic) long long rememberAuthenticationChoice; // @synthesize rememberAuthenticationChoice=_rememberAuthenticationChoice;
@property(nonatomic) BOOL needsCommitAndPushUponCompletion; // @synthesize needsCommitAndPushUponCompletion=_needsCommitAndPushUponCompletion;
@property(nonatomic) BOOL creationComplete; // @synthesize creationComplete=_creationComplete;
@property(retain, nonatomic) NSError *createEditBotError; // @synthesize createEditBotError=_createEditBotError;
@property(nonatomic) BOOL hasSufficientSCMInfoToCreateBot; // @synthesize hasSufficientSCMInfoToCreateBot=_hasSufficientSCMInfoToCreateBot;
@property(nonatomic) BOOL integrateUponCompletion; // @synthesize integrateUponCompletion=_integrateUponCompletion;
@property(nonatomic) unsigned long long minutesAfterHourToIntegrate; // @synthesize minutesAfterHourToIntegrate=_minutesAfterHourToIntegrate;
@property(nonatomic) unsigned long long hourOfIntegration; // @synthesize hourOfIntegration=_hourOfIntegration;
@property(nonatomic) long long weeklyScheduleDay; // @synthesize weeklyScheduleDay=_weeklyScheduleDay;
@property(nonatomic) unsigned long long periodicScheduleInterval; // @synthesize periodicScheduleInterval=_periodicScheduleInterval;
@property(nonatomic) unsigned long long scheduleType; // @synthesize scheduleType=_scheduleType;
@property(nonatomic) unsigned long long testingDestinationType; // @synthesize testingDestinationType=_testingDestinationType;
@property(retain, nonatomic) NSArray *triggers; // @synthesize triggers=_triggers;
@property(retain, nonatomic) NSSet *preflightIgnoredRepositoryIdentifiers; // @synthesize preflightIgnoredRepositoryIdentifiers=_preflightIgnoredRepositoryIdentifiers;
@property(nonatomic) long long preflightRepositoryAuthenticationStatus; // @synthesize preflightRepositoryAuthenticationStatus=_preflightRepositoryAuthenticationStatus;
@property(nonatomic) long long initialRepositoryAuthenticationStatus; // @synthesize initialRepositoryAuthenticationStatus=_initialRepositoryAuthenticationStatus;
@property(nonatomic) BOOL schemeSupportsDevices; // @synthesize schemeSupportsDevices=_schemeSupportsDevices;
@property(nonatomic) BOOL performsArchiveAction; // @synthesize performsArchiveAction=_performsArchiveAction;
@property(nonatomic) BOOL performsTestAction; // @synthesize performsTestAction=_performsTestAction;
@property(nonatomic) BOOL performsAnalyzeAction; // @synthesize performsAnalyzeAction=_performsAnalyzeAction;
@property(nonatomic) unsigned long long buildsFromCleanSchedule; // @synthesize buildsFromCleanSchedule=_buildsFromCleanSchedule;
@property(retain, nonatomic) IDEScheme *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *existingBotID; // @synthesize existingBotID=_existingBotID;
@property(nonatomic) BOOL preserveExistingServerBlueprint; // @synthesize preserveExistingServerBlueprint=_preserveExistingServerBlueprint;
@property(retain, nonatomic) DVTSourceControlWorkspaceBlueprint *existingSCMWorkspaceBlueprint; // @synthesize existingSCMWorkspaceBlueprint=_existingSCMWorkspaceBlueprint;
@property(retain, nonatomic) DVTSourceControlWorkspaceBlueprint *scmWorkspaceBlueprint; // @synthesize scmWorkspaceBlueprint=_scmWorkspaceBlueprint;
@property(retain, nonatomic) XCSService *service; // @synthesize service=_service;
@property(copy, nonatomic) NSString *defaultBotName; // @synthesize defaultBotName=_defaultBotName;
@property(copy, nonatomic) NSString *botName; // @synthesize botName=_botName;
@property(retain, nonatomic) XCSUICreateBotAssistantContextWindowController *assistantContextWindowController; // @synthesize assistantContextWindowController=_assistantContextWindowController;
- (void).cxx_destruct;
@property(retain, nonatomic) XCSBot *bot;
- (void)addTestingDeviceID:(id)arg1;
- (void)removeTestingDeviceID:(id)arg1;
- (BOOL)schemeSupportsArchiveAction;
- (BOOL)schemeSupportsTestAction;
- (BOOL)schemeSupportsAnalyzeAction;
- (void)dealloc;
- (id)initWithBot:(id)arg1 workspaceTabController:(id)arg2;
- (id)initWithWorkspaceTabController:(id)arg1;
- (id)init;

// Remaining properties
@property(retain) IDEWorkspaceTabController *workspaceTabController;
@property(retain, nonatomic) NSWindow *workspaceWindow;

@end

