/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableCellView.h"

@class CAShapeLayer, CATextLayer, NSImage, NSString, NSTrackingArea, XCSUIIntegrationSummaryCommitterBadgeButton;

@interface XCSUIIntegrationSummaryCommitterBadgeView : NSTableCellView
{
    BOOL _setupOnce;
    CATextLayer *_committerTextLayer;
    NSTrackingArea *_mouseTracker;
    CAShapeLayer *_badgeLayer;
    CAShapeLayer *_boundingTrack;
    CAShapeLayer *_contributionTrack;
    BOOL _badgeSelected;
    BOOL _isAllCommittersBadge;
    BOOL _drawLeftEdgeVerticalDivider;
    NSString *_committerName;
    NSImage *_committerImage;
    double _commiterContribution;
    XCSUIIntegrationSummaryCommitterBadgeButton *_button;
    id _selectedBadgeCallback;
}

@property BOOL drawLeftEdgeVerticalDivider; // @synthesize drawLeftEdgeVerticalDivider=_drawLeftEdgeVerticalDivider;
@property BOOL isAllCommittersBadge; // @synthesize isAllCommittersBadge=_isAllCommittersBadge;
@property(copy) id selectedBadgeCallback; // @synthesize selectedBadgeCallback=_selectedBadgeCallback;
@property __weak XCSUIIntegrationSummaryCommitterBadgeButton *button; // @synthesize button=_button;
@property double commiterContribution; // @synthesize commiterContribution=_commiterContribution;
@property(copy) NSImage *committerImage; // @synthesize committerImage=_committerImage;
@property(copy) NSString *committerName; // @synthesize committerName=_committerName;
- (void).cxx_destruct;
- (void)updateLayer;
- (void)viewDidChangeBackingProperties;
- (id)polishedCommitterName;
- (BOOL)wantsUpdateLayer;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (struct CGColor *)contributorTrackMouseDownStrokeColor;
- (struct CGColor *)contributorTrackRolloverStrokeColor;
- (struct CGColor *)contributorTrackDefaultStrokeColor;
- (struct CGColor *)boundingTrackMouseDownStrokeColor;
- (struct CGColor *)boundingTrackRolloverStrokeColor;
- (struct CGColor *)boundingTrackDefaultStrokeColor;
- (void)clickBadge:(id)arg1;
- (void)awakeFromNib;

@end

