/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewController.h"

#import "XCSUICreateBotTriggerChildViewController-Protocol.h"

@class NSButton, NSTokenField, XCSTrigger;

@interface XCSUICreateBotEmailNotificationsViewController : NSViewController <XCSUICreateBotTriggerChildViewController>
{
    XCSTrigger *_trigger;
    NSButton *_sendToCommittersCheckbox;
    NSTokenField *_emailTokenField;
    NSButton *_includeIssueBreakdownsCheckbox;
    NSButton *_includeCommitMessagesCheckbox;
}

@property(nonatomic) __weak NSButton *includeCommitMessagesCheckbox; // @synthesize includeCommitMessagesCheckbox=_includeCommitMessagesCheckbox;
@property(nonatomic) __weak NSButton *includeIssueBreakdownsCheckbox; // @synthesize includeIssueBreakdownsCheckbox=_includeIssueBreakdownsCheckbox;
@property(nonatomic) __weak NSTokenField *emailTokenField; // @synthesize emailTokenField=_emailTokenField;
@property(nonatomic) __weak NSButton *sendToCommittersCheckbox; // @synthesize sendToCommittersCheckbox=_sendToCommittersCheckbox;
- (void).cxx_destruct;
- (void)controlTextDidChange:(id)arg1;
- (BOOL)tokenField:(id)arg1 hasMenuForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 menuForRepresentedObject:(id)arg2;
- (void)_showEmailContactCard:(id)arg1;
- (BOOL)tokenField:(id)arg1 writeRepresentedObjects:(id)arg2 toPasteboard:(id)arg3;
- (id)tokenField:(id)arg1 representedObjectForEditingString:(id)arg2;
- (id)tokenField:(id)arg1 editingStringForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 displayStringForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 completionsForSubstring:(id)arg2 indexOfToken:(long long)arg3 indexOfSelectedItem:(long long *)arg4;
- (id)_quoteDisplayNameIfNeeded:(id)arg1;
- (id)_displayNameFromProperties:(id)arg1;
- (id)_personForEmailString:(id)arg1;
- (id)_personForEmailAddress:(id)arg1;
- (id)_emailAddressFromString:(id)arg1;
- (void)commitChanges:(id)arg1;
- (void)saveTrigger;
@property(retain) XCSTrigger *trigger;
- (id)titleForDisplay;

@end

