/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEAssistantWindowController.h"

#import "IDEContinuousIntegrationCreateEditBotWindowController-Protocol.h"

@class NSMutableArray, NSString;

@interface XCSUICreateBotAssistantContextWindowController : IDEAssistantWindowController <IDEContinuousIntegrationCreateEditBotWindowController>
{
    id _createBotCompletionBlockCopy;
    NSMutableArray *_completionPreprocessors;
    NSMutableArray *_completionPreprocessorExecutionStack;
}

@property(retain) NSMutableArray *completionPreprocessorExecutionStack; // @synthesize completionPreprocessorExecutionStack=_completionPreprocessorExecutionStack;
@property(retain) NSMutableArray *completionPreprocessors; // @synthesize completionPreprocessors=_completionPreprocessors;
- (void).cxx_destruct;
- (void)drainPreprocessorOrContinueWithSender:(id)arg1;
- (void)goNextOrFinish:(id)arg1;
- (void)addGoForwardPreprocessor:(id)arg1;
- (void)doneLoadingSourceControlBlueprint:(id)arg1;
- (void)beginSessionModalForWorkspaceTabController:(id)arg1 hostWindow:(id)arg2 editingBot:(id)arg3 withCompletionBlock:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

