/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DBGDisassemblyURLParts : NSObject
{
    int _processID;
    unsigned long long _threadID;
    unsigned long long _frameID;
}

+ (id)urlParts:(id)arg1;
+ (BOOL)isDisassemblyURL:(id)arg1;
@property(readonly) unsigned long long frameID; // @synthesize frameID=_frameID;
@property(readonly) unsigned long long threadID; // @synthesize threadID=_threadID;
@property(readonly) int processID; // @synthesize processID=_processID;
- (id)_initWithProcessID:(int)arg1 threadID:(unsigned long long)arg2 frameID:(unsigned long long)arg3;

@end

