/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTInvalidation-Protocol.h"

@class DBGViewExpressionManager, NSString;

@protocol DBGViewDescriber <DVTInvalidation>
+ (BOOL)shouldInstantiateInLaunchSession:(id)arg1;
+ (id)viewDebuggingDylibPathForLaunchSession:(id)arg1;
@property(readonly) NSString *classNameForDefaultViewIcon;
@property(readonly) DBGViewExpressionManager *expressionManager;
- (id)collectLayerViewsFromPlistArray:(id)arg1;
- (void)fetchViewInfo:(id)arg1 resultHandler:(void)arg2;
- (id)launchSession;
- (id)associatedProcessUUID;
- (void)getDataValueForExpression:(id)arg1 handler:(id)arg2;
- (id)constraintsReferencingViewObject:(id)arg1;
- (id)constraintsAffectingViewObject:(id)arg1;
- (BOOL)isViewObjectInteresting:(id)arg1;
- (id)classHierarchyForClass:(id)arg1;
- (id)propertyKeysForClassName:(id)arg1;
- (id)targetPlatformFamilyIdentifier;
- (void)populatePropertyList:(id)arg1 forObject:(id)arg2 notify:(id)arg3;
@end

