/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEFoundation/IDELocalizationData.h>

@interface _IDELocalizationDataMap : IDELocalizationData
{
    BOOL _shouldComplete;
    id <IDELocalizationDataPublisher> _publisher;
    id _work;
    unsigned long long _outstandingWork;
}

+ (id)withPublisher:(id)arg1 withWork:(id)arg2;
@property BOOL shouldComplete; // @synthesize shouldComplete=_shouldComplete;
@property unsigned long long outstandingWork; // @synthesize outstandingWork=_outstandingWork;
@property(copy) id work; // @synthesize work=_work;
@property(retain) id <IDELocalizationDataPublisher> publisher; // @synthesize publisher=_publisher;
- (void).cxx_destruct;
- (void)onCompleted;
- (void)onError:(id)arg1;
- (void)onNext:(id)arg1;
- (id)subscribe:(id)arg1;

@end

