/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEFoundation/IDEExecutionTracker.h>

@class DVTObservingToken, DVTOperation;

@interface IDEExecutionOperationTracker : IDEExecutionTracker
{
    DVTOperation *_operation;
    DVTObservingToken *_isFinishedObservingToken;
    BOOL _operationFinished;
}

@property(nonatomic) BOOL operationFinished; // @synthesize operationFinished=_operationFinished;
@property(retain) DVTOperation *operation; // @synthesize operation=_operation;
- (void).cxx_destruct;
- (BOOL)isFinished;
- (void)cancelWithReason:(int)arg1;
- (id)initWithOperation:(id)arg1;

@end

