/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IDEFoundation/IDEContainerItemCore.h>

#import <IDEFoundation/IDEFileReferenceCore-Protocol.h>

@class DVTFileDataType, NSString;

@interface IDEFileReferenceCore : IDEContainerItemCore <IDEFileReferenceCore>
{
    DVTFileDataType *_assignedDataType;
}

@property(copy) DVTFileDataType *assignedDataType; // @synthesize assignedDataType=_assignedDataType;
- (void).cxx_destruct;

// Remaining properties
@property(readonly) id <IDEContainerCore> parentContainer;
@property(retain) id <IDEGroupCore> parentGroup;
@property(copy) NSString *path;

@end

