/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, IDEEntityIdentifier, IDELocationScenarioReference, IDESchemeOptionReference, NSArray, NSDictionary, NSNumber, NSSet, NSString;

@interface IDELaunchParametersSnapshot : NSObject
{
    BOOL _askOnLaunchChangedRunnable;
    BOOL _allowLocationSimulation;
    BOOL _showNonLocalizedStrings;
    BOOL _debugAsAService;
    BOOL _usingCommandLineUnitTesting;
    BOOL _debugXPCServices;
    BOOL _viewDebuggingEnabled;
    BOOL _shouldGenerateOptimizationProfile;
    int _launchStyle;
    int _launchAutomaticallySubstyle;
    int _runnableType;
    unsigned int _debugProcessAsUID;
    int _enableOpenGLFrameCaptureMode;
    int _enableOpenGLPerformanceAnalysisMode;
    int _debugServiceFD;
    int _internalIOSLaunchStyle;
    NSDictionary *_environmentVariables;
    NSArray *_commandLineArgs;
    DVTFilePath *_runnableLocation;
    DVTFilePath *_filePathToBinary;
    IDEEntityIdentifier *_schemeIdentifier;
    NSString *_selectedLauncherIdentifier;
    NSString *_selectedDebuggerIdentifier;
    NSString *_runnableBundleIdentifier;
    NSDictionary *_appExtensionBuiltPaths;
    DVTFilePath *_replacementRunnableLocation;
    DVTFilePath *_workingDirectory;
    NSString *_architecture;
    IDELocationScenarioReference *_locationScenarioReference;
    NSString *_language;
    NSString *_region;
    IDESchemeOptionReference *_routingCoverageFileReference;
    NSNumber *_simulatorIPhoneDisplay;
    NSNumber *_simulatorIPadDisplay;
    NSString *_sdkPath;
    NSString *_remoteInstallPath;
    id _debugServiceObject;
    id _deviceArbitrationObject;
    NSString *_platformIdentifier;
    NSString *_buildConfiguration;
    id <IDEBuildableProduct> _buildableProduct;
    NSSet *_additionalInstallations;
    NSSet *_buildProductDirectories;
    NSDictionary *_testingEnvironmentVariables;
    NSArray *_testingCommandLineArgs;
    NSDictionary *_additionalDeviceSubstitutionPaths;
    NSString *_deviceAppDataPackage;
    NSArray *_additionalXPCServicesToDebug;
    NSString *_optimizationProfilePathString;
    NSString *_internalIOSSubstitutionApp;
    NSString *_customLaunchCommand;
}

+ (id)environmentVariablesToMergeFromTestingEnvironmentVariables;
+ (id)launchParametersWithSchemeIdentifier:(id)arg1 launcherIdentifier:(id)arg2 debuggerIdentifier:(id)arg3 launchStyle:(int)arg4 runnableLocation:(id)arg5 debugProcessAsUID:(unsigned int)arg6 workingDirectory:(id)arg7 commandLineArgs:(id)arg8 environmentVariables:(id)arg9 architecture:(id)arg10 platformIdentifier:(id)arg11 buildConfiguration:(id)arg12 buildableProduct:(id)arg13 deviceAppDataPackage:(id)arg14 allowLocationSimulation:(BOOL)arg15 locationScenarioReference:(id)arg16 showNonLocalizedStrings:(BOOL)arg17 language:(id)arg18 region:(id)arg19 routingCoverageFileReference:(id)arg20 enableOpenGLFrameCaptureMode:(int)arg21 enableOpenGLPerformanceAnalysisMode:(int)arg22 simulatorIPhoneDisplay:(id)arg23 simulatorIPadDisplay:(id)arg24 debugXPCServices:(BOOL)arg25 additionalXPCServicesToDebug:(id)arg26 internalIOSLaunchStyle:(int)arg27 internalIOSSubstitutionApp:(id)arg28 launchAutomaticallySubstyle:(int)arg29;
+ (id)launchParametersWithSchemeIdentifier:(id)arg1 launcherIdentifier:(id)arg2 debuggerIdentifier:(id)arg3 launchStyle:(int)arg4 runnableLocation:(id)arg5 debugProcessAsUID:(unsigned int)arg6 workingDirectory:(id)arg7 commandLineArgs:(id)arg8 environmentVariables:(id)arg9 architecture:(id)arg10 platformIdentifier:(id)arg11 buildConfiguration:(id)arg12 buildableProduct:(id)arg13 deviceAppDataPackage:(id)arg14 allowLocationSimulation:(BOOL)arg15 locationScenarioReference:(id)arg16 showNonLocalizedStrings:(BOOL)arg17 language:(id)arg18 region:(id)arg19 routingCoverageFileReference:(id)arg20 enableOpenGLFrameCaptureMode:(int)arg21 enableOpenGLPerformanceAnalysisMode:(int)arg22 simulatorIPhoneDisplay:(id)arg23 simulatorIPadDisplay:(id)arg24 debugXPCServices:(BOOL)arg25 additionalXPCServicesToDebug:(id)arg26;
+ (id)launchParametersWithSchemeIdentifier:(id)arg1 launcherIdentifier:(id)arg2 debuggerIdentifier:(id)arg3 launchStyle:(int)arg4 runnableLocation:(id)arg5 debugProcessAsUID:(unsigned int)arg6 workingDirectory:(id)arg7 commandLineArgs:(id)arg8 environmentVariables:(id)arg9 architecture:(id)arg10 platformIdentifier:(id)arg11 buildConfiguration:(id)arg12 buildableProduct:(id)arg13 deviceAppDataPackage:(id)arg14 allowLocationSimulation:(BOOL)arg15 locationScenarioReference:(id)arg16 showNonLocalizedStrings:(BOOL)arg17 locale:(id)arg18 region:(id)arg19 routingCoverageFileReference:(id)arg20 enableOpenGLFrameCaptureMode:(int)arg21 enableOpenGLPerformanceAnalysisMode:(int)arg22 simulatorIPhoneDisplay:(id)arg23 simulatorIPadDisplay:(id)arg24 debugXPCServices:(BOOL)arg25 additionalXPCServicesToDebug:(id)arg26 internalIOSLaunchStyle:(int)arg27 internalIOSSubstitutionApp:(id)arg28 launchAutomaticallySubstyle:(int)arg29;
+ (id)launchParametersWithSchemeIdentifier:(id)arg1 launcherIdentifier:(id)arg2 debuggerIdentifier:(id)arg3 launchStyle:(int)arg4 runnableLocation:(id)arg5 debugProcessAsUID:(unsigned int)arg6 workingDirectory:(id)arg7 commandLineArgs:(id)arg8 environmentVariables:(id)arg9 architecture:(id)arg10 platformIdentifier:(id)arg11 buildConfiguration:(id)arg12 buildableProduct:(id)arg13 deviceAppDataPackage:(id)arg14 allowLocationSimulation:(BOOL)arg15 locationScenarioReference:(id)arg16 showNonLocalizedStrings:(BOOL)arg17 locale:(id)arg18 region:(id)arg19 routingCoverageFileReference:(id)arg20 enableOpenGLFrameCaptureMode:(int)arg21 enableOpenGLPerformanceAnalysisMode:(int)arg22 simulatorIPhoneDisplay:(id)arg23 simulatorIPadDisplay:(id)arg24 debugXPCServices:(BOOL)arg25 additionalXPCServicesToDebug:(id)arg26;
+ (id)launchParametersWithSchemeIdentifier:(id)arg1 schemeName:(id)arg2 launcherIdentifier:(id)arg3 debuggerIdentifier:(id)arg4 launchStyle:(int)arg5 runnableLocation:(id)arg6 debugProcessAsUID:(unsigned int)arg7 workingDirectory:(id)arg8 commandLineArgs:(id)arg9 environmentVariables:(id)arg10 architecture:(id)arg11 platformIdentifier:(id)arg12 buildConfiguration:(id)arg13 buildableProduct:(id)arg14 deviceAppDataPackage:(id)arg15 allowLocationSimulation:(BOOL)arg16 locationScenarioReference:(id)arg17 showNonLocalizedStrings:(BOOL)arg18 language:(id)arg19 region:(id)arg20 routingCoverageFileReference:(id)arg21 enableOpenGLFrameCaptureMode:(int)arg22 enableOpenGLPerformanceAnalysisMode:(int)arg23 simulatorIPhoneDisplay:(id)arg24 simulatorIPadDisplay:(id)arg25 debugXPCServices:(BOOL)arg26 additionalXPCServicesToDebug:(id)arg27 launchAutomaticallySubstyle:(int)arg28;
@property(copy) NSString *customLaunchCommand; // @synthesize customLaunchCommand=_customLaunchCommand;
@property(copy) NSString *internalIOSSubstitutionApp; // @synthesize internalIOSSubstitutionApp=_internalIOSSubstitutionApp;
@property(copy, nonatomic) NSString *optimizationProfilePathString; // @synthesize optimizationProfilePathString=_optimizationProfilePathString;
@property BOOL shouldGenerateOptimizationProfile; // @synthesize shouldGenerateOptimizationProfile=_shouldGenerateOptimizationProfile;
@property BOOL viewDebuggingEnabled; // @synthesize viewDebuggingEnabled=_viewDebuggingEnabled;
@property int internalIOSLaunchStyle; // @synthesize internalIOSLaunchStyle=_internalIOSLaunchStyle;
@property(copy) NSArray *additionalXPCServicesToDebug; // @synthesize additionalXPCServicesToDebug=_additionalXPCServicesToDebug;
@property(readonly) BOOL debugXPCServices; // @synthesize debugXPCServices=_debugXPCServices;
@property(readonly) NSString *deviceAppDataPackage; // @synthesize deviceAppDataPackage=_deviceAppDataPackage;
@property(copy) NSDictionary *additionalDeviceSubstitutionPaths; // @synthesize additionalDeviceSubstitutionPaths=_additionalDeviceSubstitutionPaths;
@property(getter=isUsingCommandLineUnitTesting) BOOL usingCommandLineUnitTesting; // @synthesize usingCommandLineUnitTesting=_usingCommandLineUnitTesting;
@property(copy) NSArray *testingCommandLineArgs; // @synthesize testingCommandLineArgs=_testingCommandLineArgs;
@property(copy) NSDictionary *testingEnvironmentVariables; // @synthesize testingEnvironmentVariables=_testingEnvironmentVariables;
@property(copy) NSSet *buildProductDirectories; // @synthesize buildProductDirectories=_buildProductDirectories;
@property(copy) NSSet *additionalInstallations; // @synthesize additionalInstallations=_additionalInstallations;
@property(readonly) id <IDEBuildableProduct> buildableProduct; // @synthesize buildableProduct=_buildableProduct;
@property(readonly) NSString *buildConfiguration; // @synthesize buildConfiguration=_buildConfiguration;
@property(readonly) NSString *platformIdentifier; // @synthesize platformIdentifier=_platformIdentifier;
@property(retain) id deviceArbitrationObject; // @synthesize deviceArbitrationObject=_deviceArbitrationObject;
@property(retain) id debugServiceObject; // @synthesize debugServiceObject=_debugServiceObject;
@property int debugServiceFD; // @synthesize debugServiceFD=_debugServiceFD;
@property BOOL debugAsAService; // @synthesize debugAsAService=_debugAsAService;
@property(copy) NSString *remoteInstallPath; // @synthesize remoteInstallPath=_remoteInstallPath;
@property(copy) NSString *sdkPath; // @synthesize sdkPath=_sdkPath;
@property(readonly) int enableOpenGLPerformanceAnalysisMode; // @synthesize enableOpenGLPerformanceAnalysisMode=_enableOpenGLPerformanceAnalysisMode;
@property(readonly) int enableOpenGLFrameCaptureMode; // @synthesize enableOpenGLFrameCaptureMode=_enableOpenGLFrameCaptureMode;
@property(readonly) NSNumber *simulatorIPadDisplay; // @synthesize simulatorIPadDisplay=_simulatorIPadDisplay;
@property(readonly) NSNumber *simulatorIPhoneDisplay; // @synthesize simulatorIPhoneDisplay=_simulatorIPhoneDisplay;
@property(readonly) IDESchemeOptionReference *routingCoverageFileReference; // @synthesize routingCoverageFileReference=_routingCoverageFileReference;
@property(copy, nonatomic) NSString *region; // @synthesize region=_region;
@property(copy, nonatomic) NSString *language; // @synthesize language=_language;
@property BOOL showNonLocalizedStrings; // @synthesize showNonLocalizedStrings=_showNonLocalizedStrings;
@property(readonly) IDELocationScenarioReference *locationScenarioReference; // @synthesize locationScenarioReference=_locationScenarioReference;
@property BOOL allowLocationSimulation; // @synthesize allowLocationSimulation=_allowLocationSimulation;
@property(readonly, copy) NSString *architecture; // @synthesize architecture=_architecture;
@property(readonly) DVTFilePath *workingDirectory; // @synthesize workingDirectory=_workingDirectory;
@property(readonly) unsigned int debugProcessAsUID; // @synthesize debugProcessAsUID=_debugProcessAsUID;
@property(copy) DVTFilePath *replacementRunnableLocation; // @synthesize replacementRunnableLocation=_replacementRunnableLocation;
@property BOOL askOnLaunchChangedRunnable; // @synthesize askOnLaunchChangedRunnable=_askOnLaunchChangedRunnable;
@property(copy) NSDictionary *appExtensionBuiltPaths; // @synthesize appExtensionBuiltPaths=_appExtensionBuiltPaths;
@property int runnableType; // @synthesize runnableType=_runnableType;
@property(copy) NSString *runnableBundleIdentifier; // @synthesize runnableBundleIdentifier=_runnableBundleIdentifier;
@property(readonly) int launchAutomaticallySubstyle; // @synthesize launchAutomaticallySubstyle=_launchAutomaticallySubstyle;
@property(readonly) int launchStyle; // @synthesize launchStyle=_launchStyle;
@property(readonly) NSString *selectedDebuggerIdentifier; // @synthesize selectedDebuggerIdentifier=_selectedDebuggerIdentifier;
@property(readonly) NSString *selectedLauncherIdentifier; // @synthesize selectedLauncherIdentifier=_selectedLauncherIdentifier;
@property(readonly) IDEEntityIdentifier *schemeIdentifier; // @synthesize schemeIdentifier=_schemeIdentifier;
- (void).cxx_destruct;
- (id)launchParametersByAppendingPath:(id)arg1 toSearchPathEnvironmentVariable:(id)arg2;
- (id)launchParametersByPrependingPath:(id)arg1 toSearchPathEnvironmentVariable:(id)arg2;
- (id)launchParametersByReplacingEnvironmentVariablesWithDictionary:(id)arg1;
- (id)launchParametersByReplacingCommandLineArgsWithArray:(id)arg1;
@property(readonly) DVTFilePath *filePathToBinary; // @synthesize filePathToBinary=_filePathToBinary;
@property(readonly) DVTFilePath *originalRunnableLocation;
@property(readonly) DVTFilePath *runnableLocation; // @synthesize runnableLocation=_runnableLocation;
@property(readonly, copy) NSArray *commandLineArgs; // @synthesize commandLineArgs=_commandLineArgs;
@property(readonly, copy) NSDictionary *environmentVariables; // @synthesize environmentVariables=_environmentVariables;

@end

