/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTCancellable-Protocol.h"

@class IDESourceControlRequest;

@interface IDESourceControlMultipleStepInvalidationToken : NSObject <DVTCancellable>
{
    IDESourceControlRequest *_currentRequest;
    BOOL _isCancelled;
}

@property __weak IDESourceControlRequest *currentRequest; // @synthesize currentRequest=_currentRequest;
- (void).cxx_destruct;
- (void)cancel;
@property(readonly, getter=isCancelled) BOOL cancelled;
- (id)init;

@end

