/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GPUToolsAnalysis/DYAnalyzerHeuristic.h>

@class DYAnalyzerSharegroupObjectCoverage, NSMutableDictionary;

@interface DYAnalyzerHeuristic_DataInitialization : DYAnalyzerHeuristic
{
    int currCaptureBlockMode;
    int currTextureType;
    int currTextureBinding;
    int currBufferBinding;
    int attachmentObjectType;
    int attachmentObjectID;
    DYAnalyzerSharegroupObjectCoverage *coverage;
    NSMutableDictionary *_transformFeedbackBufferByteCounts;
}

+ (id)identifier;
- (void).cxx_destruct;
- (void)_reportDataCompletelyUpdated:(int)arg1 objectType:(unsigned int)arg2 function:(const struct Function *)arg3;
- (void)reportTransformFeedbackIsOverflowingBuffer:(const struct Function *)arg1 bufferID:(int)arg2;
- (void)reportClearWithRasterizerDiscard:(const struct Function *)arg1;
- (void)reportBlitFramebufferReadOnUninitializedAttachment:(const struct Function *)arg1 attachment:(const struct TypedFramebufferAttachment *)arg2;
- (void)reportPresentNonExistentRenderbuffer:(const struct Function *)arg1 renderbufferID:(int)arg2;
- (void)reportPresentNonLayerBackedRenderbuffer:(const struct Function *)arg1 renderbufferID:(int)arg2;
- (void)reportMSAAResolveOfUninitializedColorAttachment:(const struct Function *)arg1;
- (void)reportReadPixelsOnUninitializedColorAttachment:(const struct Function *)arg1;
- (void)reportUninitializedColorAttachmentOnFrameBoundary:(const struct Function *)arg1;
- (void)reportUninitializedTextureUsage:(const struct Function *)arg1;
- (void)_reportEmptyBufferUsage:(const struct Function *)arg1;
- (void)reportUninitializedBufferUsage:(const struct Function *)arg1;
- (void)addRenderbufferUpdateFunctionIndices:(int)arg1 finding:(id)arg2;
- (void)addTextureUpdateFunctionIndices:(int)arg1 finding:(id)arg2;
- (void)addBufferCoveredFunctionIndices:(int)arg1 finding:(id)arg2;
- (void)addBufferUpdateFunctionIndices:(int)arg1 finding:(id)arg2;
- (void)_addFunctionIndices:(id)arg1 toFinding:(id)arg2;
- (void)endBlock:(int)arg1;
- (void)startBlock:(int)arg1;
- (void)_transformFeedbackProvideCoverage:(const struct Function *)arg1 context:(const ContextStateMirror_efb9dfa5 *)arg2 numVertices:(int)arg3;
- (DYSpanList_ddb2e64e)_subImageSpansForPackUnpack:(const ContextStateMirror_efb9dfa5 *)arg1 format:(int)arg2 type:(int)arg3 x:(int)arg4 y:(int)arg5 z:(int)arg6 width:(int)arg7 height:(int)arg8 depth:(int)arg9 offset:(long long)arg10 useUnpackState:(BOOL)arg11;
- (const TextureLayer_be4f88f0 *)_texLayerOfAttachment:(const FramebufferAttachment_85593ca2 *)arg1 context:(ContextStateMirror_efb9dfa5 *)arg2;
- (void)_determineBlitFBDestRect:(ContextStateMirror_efb9dfa5 *)arg1 x0:(int)arg2 y0:(int)arg3 x1:(int)arg4 y1:(int)arg5 attachments:(vector_590fc35f *)arg6 outRect:(struct DYRegionRect *)arg7;
- (void)_determineBlitFBRect:(ContextStateMirror_efb9dfa5 *)arg1 x0:(int)arg2 y0:(int)arg3 x1:(int)arg4 y1:(int)arg5 attachments:(vector_590fc35f *)arg6 outRect:(struct DYRegionRect *)arg7;
- (void)_getBlitFBDestAttachmentsForContext:(const ContextStateMirror_efb9dfa5 *)arg1 outAttachments:(vector_590fc35f *)arg2 mask:(unsigned int)arg3;
- (void)_getBlitFBSourceAttachmentsForContext:(const ContextStateMirror_efb9dfa5 *)arg1 outAttachments:(vector_590fc35f *)arg2 mask:(unsigned int)arg3;
- (unsigned int)getWriteMask;
- (unsigned int)getWriteMaskUsingClearMaskBits:(unsigned int)arg1;
- (struct DYRegionRect)getCurrentScissorRect;
- (struct DYRegionRect)getCurrentDrawRect;
- (void)clearFBOAttachmentCoverage:(int)arg1 attachment:(int)arg2 inRect:(const struct DYRegionRect *)arg3;
- (void)_updateFBOAttachment:(const FramebufferAttachment_85593ca2 *)arg1 attachmentType:(int)arg2 region:(const struct DYRegionRect *)arg3 writeMask:(unsigned int)arg4 function:(const struct Function *)arg5;
- (void)updateFBOAttachmentsForClearBuffer:(int)arg1 drawBuffer:(int)arg2 function:(const struct Function *)arg3;
- (void)updateDrawFBOAttachmentsForRegion:(const struct DYRegionRect *)arg1 writeMask:(unsigned int)arg2 function:(const struct Function *)arg3;
- (void)updateDrawFBOColor0AttachmentForRegion:(const struct DYRegionRect *)arg1 writeMask:(unsigned int)arg2 function:(const struct Function *)arg3;
- (BOOL)_isAttachmentCovered:(const FramebufferAttachment_85593ca2 *)arg1 inRect:(const struct DYRegionRect *)arg2 channelBits:(unsigned int)arg3;
- (BOOL)_isAttachmentCovered:(const FramebufferAttachment_85593ca2 *)arg1 channelBits:(unsigned int)arg2;
- (BOOL)isReadFBOAttachmentCovered:(int)arg1 channelBits:(unsigned int)arg2;
- (void)checkTexturesInUse:(const struct Function *)arg1;
- (void)checkUniformBuffersInUse:(const struct Function *)arg1 context:(ContextStateMirror_efb9dfa5 *)arg2;
- (void)_checkElementArrayBufferInUse:(const struct Function *)arg1;
- (void)checkVBOsInUseES20:(const struct Function *)arg1 vertexAttribIndex:(int)arg2;
- (void)checkVBOsInUseES11:(const struct Function *)arg1 arrayEnum:(int)arg2 arrayBindingEnum:(int)arg3 usingTextureUnit:(int)arg4;
- (void)_checkBufferInUse:(int)arg1 context:(ContextStateMirror_efb9dfa5 *)arg2 function:(const struct Function *)arg3;
- (void)processVBOsInUse:(const struct Function *)arg1;
- (void)processFunction:(const struct Function *)arg1 stateMirrorRetCode:(unsigned int)arg2;
- (void)_tagTextureAsCovered:(int)arg1 target:(int)arg2 level:(int)arg3 coverageMask:(unsigned int)arg4 bottom:(long long)arg5 top:(long long)arg6 left:(long long)arg7 right:(long long)arg8 lowLayer:(long long)arg9 highLayer:(long long)arg10 function:(const struct Function *)arg11;
- (void)_tagTextureAsCovered:(int)arg1 target:(int)arg2 level:(int)arg3 coverageMask:(unsigned int)arg4 bottom:(long long)arg5 top:(long long)arg6 left:(long long)arg7 right:(long long)arg8 function:(const struct Function *)arg9;
- (void)_tagTextureAsCovered:(int)arg1 target:(int)arg2 level:(int)arg3 coverageMask:(unsigned int)arg4 function:(const struct Function *)arg5;
- (void)_tagBufferAsCovered:(int)arg1 start:(long long)arg2 end:(long long)arg3 function:(const struct Function *)arg4;
- (id)init;

@end

