/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface XCSBlockStep : NSObject
{
}

+ (void)stepWithBlocks:(id)arg1 timeout:(double)arg2 completionHandler:(id)arg3;

@end

