/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DVTAssetDetailViewDelegate <NSObject>
- (void)assetDetailView:(id)arg1 userDidSelectTab:(id)arg2;
- (void)assetDetailView:(id)arg1 didInstallDetailController:(id)arg2;
- (void)assetDetailView:(id)arg1 sizeViewController:(id)arg2 toFitSuggestedSize:(struct CGSize)arg3;
- (void)assetDetailView:(id)arg1 wasDoubleClickedInHeader:(id)arg2;
- (void)assetDetailView:(id)arg1 beginDraggingWithMouseDownEvent:(id)arg2 andMouseDraggedEvent:(id)arg3;
@end

