/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSApplication.h"

@class DVTHashTable;

@interface DVTApplication : NSApplication
{
    DVTHashTable *_actionMonitors;
}

- (void).cxx_destruct;
- (BOOL)presentError:(id)arg1;
- (void)presentError:(id)arg1 modalForWindow:(id)arg2 delegate:(id)arg3 didPresentSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (id)massageErrorForInternalMessage:(id)arg1;
- (void)errorPresentationDidCompleteWithResultCode:(long long)arg1 context:(void *)arg2;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3;
- (id)addActionMonitorWithHandlerBlock:(id)arg1;
- (void)_enableMainThreadLatencyCheckerWithMilliSecondsThreshholdBeforeSPOD:(unsigned long long)arg1 milliSecondsThreshholdBeforeUNSPOD:(unsigned long long)arg2 milliSecondsBetweenPings:(unsigned long long)arg3;
- (void)_really_enableMainThreadLatencyCheckerWithMilliSecondsThreshholdBeforeSPOD:(unsigned long long)arg1 milliSecondsThreshholdBeforeUNSPOD:(unsigned long long)arg2 milliSecondsBetweenPings:(unsigned long long)arg3;

@end

