/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface DVTColorPickerChooserViewColorSwatch : NSView
{
    NSColor *color;
    BOOL highlighted;
    id target;
    SEL action;
}

@property(retain) NSColor *color; // @synthesize color;
- (void).cxx_destruct;
- (id)description;
- (void)drawRect:(struct CGRect)arg1;
@property BOOL highlighted;
- (void)mouseUp:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setAction:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)initWithColor:(id)arg1 andFrame:(struct CGRect)arg2;
- (void)setupTrackingArea;
- (BOOL)isFlipped;

@end

