/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDiffDescriptor.h"

@class _DVTFileMergeDiffVitalStats;

@interface DVTDiffDescriptor (FileMergeCompat_ReallyInternal)
@property(readonly) int fmc_operation;
- (struct CGRect)fmc_displayRect:(id)arg1 forSide:(int)arg2 ensureLayout:(BOOL)arg3;
@property(readonly) _DVTFileMergeDiffVitalStats *fmc_vitals;
@end

