/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DVTKit/DVTLibraryDetailController.h>

@class NSImageView;

@interface DVTImageLibraryDetailController : DVTLibraryDetailController
{
    NSImageView *_imageView;
}

- (void).cxx_destruct;
- (void)sizeToFitSuggestedSize:(struct CGSize)arg1 forAsset:(id)arg2;
- (void)refreshWithAsset:(id)arg1 representedObject:(id)arg2;

@end

