/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DVTLineOffsetAwareStringWrapper : NSObject
{
    struct _DVTTextLineOffsetTable _lineOffsets;
    NSString *_string;
}

@property(readonly, copy) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
- (void)dealloc;
- (struct _NSRange)characterRangeFromDocumentLocation:(id)arg1;
- (id)convertLocationToUTF8EncodedLocation:(id)arg1;
- (id)convertLocationToNativeNSStringEncodedLocation:(id)arg1;
- (struct _NSRange)lineRangeForCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)characterRangeForLineRange:(struct _NSRange)arg1;
- (id)initWithString:(id)arg1;

@end

