/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DVTKit/DVTViewController.h>

#import "NSPopoverDelegate-Protocol.h"

@class NSPopover;

@interface DVTPopoverContentViewController : DVTViewController <NSPopoverDelegate>
{
    id _didCloseBlock;
    NSPopover *_popover;
}

+ (id)configuredPopoverWithViewController:(id)arg1 didCloseBlock:(id)arg2;
- (void).cxx_destruct;
- (void)_popoverDidClose:(id)arg1;
- (void)_popoverWillClose:(id)arg1;
- (void)_setDidCloseBlock:(id)arg1;
- (void)_setPopover:(id)arg1;
- (void)primitiveInvalidate;
- (void)closePopover:(id)arg1;
- (id)popover;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

