/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTabViewItem.h"

#import "DVTInvalidation-Protocol.h"

@class DVTBarBackground, DVTObservingToken, DVTStackBacktrace, DVTViewController<DVTTabbedWindowTabContentControlling>, NSButton, NSString;

@interface DVTTabbedWindowTabViewItem : NSTabViewItem <DVTInvalidation>
{
    DVTObservingToken *_tabLabelObservingToken;
    BOOL _isEditingTabName;
    BOOL _tabNameEditable;
    DVTViewController<DVTTabbedWindowTabContentControlling> *_tabContentController;
    DVTBarBackground *_tabBarView;
    NSButton *_tabButton;
    NSString *_searchFieldText;
}

+ (void)initialize;
@property(copy, nonatomic) NSString *searchFieldText; // @synthesize searchFieldText=_searchFieldText;
@property(getter=isTabNameEditable) BOOL tabNameEditable; // @synthesize tabNameEditable=_tabNameEditable;
@property(nonatomic) BOOL isEditingTabName; // @synthesize isEditingTabName=_isEditingTabName;
@property(nonatomic) __weak NSButton *tabButton; // @synthesize tabButton=_tabButton;
@property(nonatomic) __weak DVTBarBackground *tabBarView; // @synthesize tabBarView=_tabBarView;
@property(retain, nonatomic) DVTViewController<DVTTabbedWindowTabContentControlling> *tabContentController; // @synthesize tabContentController=_tabContentController;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)_computeTabLabel;
- (void)updateLabelSoon;
- (void)updateLabelNow;
@property(readonly) BOOL canBeClosed;
- (void)setLabel:(id)arg1;
- (void)setView:(id)arg1;
- (void)setEditingTabName:(BOOL)arg1;
- (id)initWithTabBarView:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

