/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (FindPatternAdditions)
+ (id)dvt_attributedStringFromPasteboardPropertyList:(id)arg1 inField:(id)arg2;
- (id)dvt_stringByDeletingPatterns;
- (id)dvt_replacementExpression;
- (id)dvt_regularExpressionWithRange:(struct _NSRange)arg1 escapingStrings:(BOOL)arg2 usingBackreferences:(BOOL)arg3;
- (id)dvt_regularExpression;
- (id)dvt_findPatternArrayWithRange:(struct _NSRange)arg1 includingStrings:(BOOL)arg2;
- (id)dvt_findPatternArray;
- (BOOL)dvt_isEqualFindPatternAttributedString:(id)arg1;
- (BOOL)dvt_hasValidFindPattern;
- (BOOL)dvt_hasFindPattern;
- (id)dvt_pasteboardPropertyListFromRange:(struct _NSRange)arg1;
@end

