/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSClipView.h"

@interface NSClipView (DVTNSClipViewAdditions)
- (BOOL)dvt_autoscrollWithExternalDragEvent:(id)arg1 animate:(BOOL)arg2;
- (struct CGSize)dvt_effectiveAutoscrollDelta;
- (void)setDvt_autoscrollDelta:(id)arg1;
- (id)dvt_autoscrollDelta;
- (struct CGSize)dvt_defaultAutoscrollDelta;
@end

