/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IBFoundation/IBAbstractPlatformTool-Protocol.h>

@protocol IBAbstractInterfaceBuilderTool <IBAbstractPlatformTool>
- (id)renderImagesForRequests:(id)arg1;
- (id)loadLiveViewBundlesAtPaths:(id)arg1 withProjectSourceDirectoryPaths:(id)arg2;
@end

