/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IBFoundation/IBICMultipartImageRepSlotComponent.h>

#import "NSCoding-Protocol.h"

@interface IBICPlatform : IBICMultipartImageRepSlotComponent <NSCoding>
{
}

+ (id)contentsJSONKey;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqualToSchemaImageRepIDComponent:(id)arg1;
- (BOOL)isEqualToPlatform:(id)arg1;

@end

