/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <IBFoundation/IBICFolder.h>

@interface IBICCatalog : IBICFolder
{
}

- (void)replaceChildrenWithDiskContent:(id)arg1;
- (BOOL)canBeEmbeddedInFolder;
- (BOOL)canHaveChildren;
- (id)displayName;
- (id)allIconSets;
- (id)allImageSets;
- (id)catalog;
- (id)descriptionShortClassName;

@end

