/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GPUToolsServices/DYCaptureArchiveTracer.h>

@class NSFileHandle;

@interface DYCaptureArchiveTraceToFile : DYCaptureArchiveTracer
{
    NSFileHandle *_fileHandle;
}

- (void).cxx_destruct;
- (void)newTraceString:(id)arg1;
- (void)closeFile;
- (id)initWithCaptureArchive:(id)arg1 withFilePath:(id)arg2 withFunctionTracer:(id)arg3;

@end

