/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class DYDeviceInfo, DYInvestigatorStatistics, DYOverviewMeasurementsPerSample, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface DYInvestigatorCaseConfigData : NSObject <NSCopying, NSCoding>
{
    NSMutableArray *_overviewSamples;
    NSMutableDictionary *_reportData;
    DYOverviewMeasurementsPerSample *_overviewSamplePrev;
    NSMutableArray *_frameRateOverTimeArray;
    NSMutableDictionary *_reportDataNew;
    int _reportLock;
    unsigned long long _overviewSampleCount;
    unsigned long long _overviewSamplePeriod;
    unsigned long long _overviewDuration;
    BOOL _overviewSamplesAreReady;
    NSString *_appName;
    NSArray *_appArguments;
    DYDeviceInfo *_captureDeviceInfo;
    NSMutableArray *_displayLinks;
    NSArray *_analyzerFindings;
    NSNumber *_originalCaptureFrameTime;
    DYInvestigatorStatistics *_overviewFrameTime;
    DYInvestigatorStatistics *_overviewCAWaitTime;
}

@property(readonly, nonatomic) NSDictionary *reportData; // @synthesize reportData=_reportData;
@property(retain, nonatomic) DYInvestigatorStatistics *overviewCAWaitTime; // @synthesize overviewCAWaitTime=_overviewCAWaitTime;
@property(retain, nonatomic) DYInvestigatorStatistics *overviewFrameTime; // @synthesize overviewFrameTime=_overviewFrameTime;
@property(retain, nonatomic) NSNumber *originalCaptureFrameTime; // @synthesize originalCaptureFrameTime=_originalCaptureFrameTime;
@property(nonatomic) BOOL overviewSamplesAreReady; // @synthesize overviewSamplesAreReady=_overviewSamplesAreReady;
@property(retain, nonatomic) NSArray *analyzerFindings; // @synthesize analyzerFindings=_analyzerFindings;
@property(retain, nonatomic) NSMutableArray *displayLinks; // @synthesize displayLinks=_displayLinks;
@property(readonly, nonatomic) NSArray *overviewSamples; // @synthesize overviewSamples=_overviewSamples;
@property(retain, nonatomic) DYDeviceInfo *captureDeviceInfo; // @synthesize captureDeviceInfo=_captureDeviceInfo;
@property(retain, nonatomic) NSArray *appArguments; // @synthesize appArguments=_appArguments;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (void).cxx_destruct;
- (void)reportDataClearProjections;
- (void)reportDataClear;
- (void)reportDataCommit;
- (void)reportDataRemoveObjectForKey:(id)arg1;
- (void)reportDataSetObject:(id)arg1 forKey:(id)arg2;
- (void)debugPrintFormatted;
- (id)totalFrameRateArray;
- (void)addDisplayLinks:(id)arg1;
- (void)addOverviewSamples:(id)arg1;
- (void)_addOverviewSample:(id)arg1;
- (void)addTraceProfileData:(id)arg1;
- (id)_createSample:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCaptureDeviceInfo:(id)arg1 appName:(id)arg2 appArguments:(id)arg3 analyzerFindings:(id)arg4;
- (id)init;

@end

