/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GPUToolsServices/DYDevice.h>

@interface DYLocalHostDevice : DYDevice
{
}

+ (id)sharedLocalHostDevice;
- (id)createDeferredLaunchGuestAppSession:(id)arg1;
- (id)createGuestAppSession:(id)arg1;
- (id)iconDataForApplicationIdentifiers:(id)arg1;
- (id)guestAppWithURL:(id)arg1;
- (id)gputoolsServiceAvailabilityError;
- (BOOL)gputoolsServiceAvailable;
- (id)_init;
- (id)init;

@end

