/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DYTransport;

@interface DYResourceStreamer : NSObject
{
    DYTransport *_transport;
    struct dispatch_queue_s *_outputQueue;
    struct dispatch_queue_s *_replyQueue;
}

+ (id)processRealizeResourceMessages:(id)arg1 resourceObject:(id)arg2 tempDict:(id)arg3;
+ (id)_createResource:(id)arg1 funcStreamData:(id)arg2 objectCache:(id)arg3;
+ (id)findDataForURL:(const char *)arg1 inCache:(id)arg2;
- (void).cxx_destruct;
- (id)updateResource:(id)arg1;
- (id)fetchState;
- (id)realizeResource:(id)arg1 functionIndex:(unsigned int)arg2;
- (id)fetchResourceList:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithTransport:(id)arg1;
- (id)init;

@end

