/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface DYSymbolicator : NSObject
{
    NSArray *_rootPaths;
    BOOL _removeTopGPUTools;
    id _ownerFilter;
    id _stackFrameAllocator;
    struct _CSTypeRef _coreSymbolicator;
}

+ (id)dysmURLForUUIDBytes:(const CDStruct_bd2f613f *)arg1 roots:(id)arg2;
@property(copy, nonatomic) id stackFrameAllocator; // @synthesize stackFrameAllocator=_stackFrameAllocator;
@property(copy, nonatomic) id ownerFilter; // @synthesize ownerFilter=_ownerFilter;
@property(nonatomic) BOOL removeTopGPUTools; // @synthesize removeTopGPUTools=_removeTopGPUTools;
@property(readonly, nonatomic) struct _CSTypeRef coreSymbolicator; // @synthesize coreSymbolicator=_coreSymbolicator;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)enumerateStackFrames:(id)arg1 usingBlock:(id)arg2;
- (void)enumerateStackFrames:(unsigned long long *)arg1 count:(unsigned long long)arg2 usingBlock:(id)arg3;
- (id)_createStackFrame;
- (void)dealloc;
- (id)initWithSignature:(id)arg1 rootPaths:(id)arg2 device:(id)arg3 error:(id *)arg4;
- (id)initWithCoreSymbolicator:(struct _CSTypeRef)arg1 rootPaths:(id)arg2 device:(id)arg3;
- (id)init;
- (void)_fixSymbolOwnerPaths;

@end

