/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <SceneKit/_SCNExportOperation.h>

// Not exported
@interface SCNCOLLADAExportOperation : _SCNExportOperation
{
}

- (void)main;
- (id)initWithScene:(id)arg1 attributes:(id)arg2 outputURL:(id)arg3;

@end

