/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class SCNNode, SCNScene, SKScene;

@protocol SCNSceneRenderer <NSObject>
@property(nonatomic) double currentTime;
@property(readonly, nonatomic) void *context;
@property(retain, nonatomic) SKScene *overlaySKScene;
@property(nonatomic) BOOL showsStatistics;
@property(nonatomic, getter=isJitteringEnabled) BOOL jitteringEnabled;
@property(nonatomic) BOOL autoenablesDefaultLighting;
@property(retain, nonatomic) SCNNode *pointOfView;
@property(nonatomic) BOOL loops;
@property(getter=isPlaying) BOOL playing;
@property(nonatomic) id <SCNSceneRendererDelegate> delegate;
@property(nonatomic) double sceneTime;
@property(retain, nonatomic) SCNScene *scene;
- (void)prepareObjects:(id)arg1 withCompletionHandler:(id)arg2;
- (BOOL)prepareObject:(id)arg1 shouldAbortBlock:(id)arg2;
- (struct SCNVector3)unprojectPoint:(struct SCNVector3)arg1;
- (struct SCNVector3)projectPoint:(struct SCNVector3)arg1;
- (BOOL)isNodeInsideFrustum:(id)arg1 withPointOfView:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 options:(id)arg2;
@end

