/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTTableView.h"

@interface DTDKTableView : DVTTableView
{
    unsigned int _delegateImplements_deleteRows:1;
    unsigned int _delegateImplements_contextMenu:1;
    unsigned int _reserved2:30;
}

- (void)keyDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)setDelegate:(id)arg1;

@end

