/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DTXConnectionServices/DTXTransport.h>

@interface DTXFileDescriptorTransport : DTXTransport
{
    int _inFD;
    int _outFD;
    struct dispatch_queue_s *_inputQueue;
    struct dispatch_queue_s *_outputQueue;
    int _outputWaitKQ;
    struct dispatch_source_s *_inputSource;
    BOOL _assumingOwnershipOfFDs;
}

- (void)disconnect;
- (unsigned long long)transmit:(const void *)arg1 ofLength:(unsigned long long)arg2;
- (void)setupWithIncomingDescriptor:(int)arg1 outgoingDescriptor:(int)arg2 assumingOwnership:(BOOL)arg3;
- (int)_createWriteKQueue:(int)arg1;
- (struct dispatch_source_s *)_createReadSource:(int)arg1;
- (void)dealloc;
- (id)initWithIncomingFilePath:(id)arg1 outgoingFilePath:(id)arg2 error:(id *)arg3;
- (id)initWithIncomingFilePath:(id)arg1 outgoingFilePath:(id)arg2;
- (id)init;

@end

