/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DSADocSet, NSArray;

// Not exported
@interface DSAQueuedTextSearchResults : NSObject
{
    DSADocSet *_docSet;
    NSArray *_fullTextResults;
    NSArray *_nodeTextResults;
    float _maximumFullTextRelevance;
}

@property float maximumFullTextRelevance; // @synthesize maximumFullTextRelevance=_maximumFullTextRelevance;
@property(retain) NSArray *nodeTextResults; // @synthesize nodeTextResults=_nodeTextResults;
@property(retain) NSArray *fullTextResults; // @synthesize fullTextResults=_fullTextResults;
- (void).cxx_destruct;
- (void)prefetchNodes;
- (id)mergedResults;
- (BOOL)isComplete;
- (id)initForDocSet:(id)arg1;

@end

