/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTDeveloperProfile.h"

@interface IDEiPhoneDeveloperProfile : DVTDeveloperProfile
{
}

- (void)_passwordSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_showPasswordSheetForDeveloperProfileAtURL:(id)arg1 accountProviders:(id)arg2 window:(id)arg3 completionHandler:(id)arg4;
- (void)importDeveloperProfileWithAccountProviders:(id)arg1 window:(id)arg2 completionHandler:(id)arg3;
- (void)importDeveloperProfileFromFilePath:(id)arg1 withAccountProviders:(id)arg2 window:(id)arg3 completionHandler:(id)arg4;
- (void)exportDeveloperProfileWithAccountProviders:(id)arg1 window:(id)arg2 completionHandler:(id)arg3;

@end

