/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSImage.h"

@interface NSImage (IDEImageComparisonExtensions)
+ (id)combineImages:(id)arg1;
+ (id)compareImages:(id)arg1 tolerance:(double)arg2;
+ (BOOL)canCompareImages:(id)arg1;
- (id)compareWithImage:(id)arg1 tolerance:(double)arg2;
- (id)createCIImage;
@end

