/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface XCRemoteIPhone_SharedScreenshots : NSObject
{
    NSArray *_screenshots;
}

+ (id)sharedScreenshots;
@property(retain) NSArray *screenshots; // @synthesize screenshots=_screenshots;
- (void).cxx_destruct;
- (id)init;
- (BOOL)removeScreenshotForDictionary:(id)arg1;
- (void)addScreenshotForPath:(id)arg1;
- (void)readImageDictionaryArrayFromDisk;
- (void *)deviceForIdentifier:(id)arg1;
- (BOOL)deviceListenerAvailable;
- (void)applicationWillTerminate:(id)arg1;

@end

