/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DYFunctionTracerDelegate <NSObject>

@optional
- (id)rewriteContext:(unsigned long long)arg1;
- (id)rewriteURL:(const char *)arg1;
- (id)rewriteVariable:(const char *)arg1 context:(unsigned long long)arg2;
@end

