/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DYFramebufferObject, DYResourceObject, NSMutableDictionary;

// Not exported
@interface GPUTraceFramebuffer : NSObject
{
    DYFramebufferObject *_framebufferObject;
    NSMutableDictionary *_colorResourceObjects;
    DYResourceObject *_depthResourceObject;
    DYResourceObject *_stencilResourceObject;
    DYResourceObject *_wireframeRenderbuffer;
}

@property(retain) DYResourceObject *wireframeRenderbuffer; // @synthesize wireframeRenderbuffer=_wireframeRenderbuffer;
@property(retain) DYResourceObject *stencilResourceObject; // @synthesize stencilResourceObject=_stencilResourceObject;
@property(retain) DYResourceObject *depthResourceObject; // @synthesize depthResourceObject=_depthResourceObject;
@property(readonly) NSMutableDictionary *colorResourceObjects; // @synthesize colorResourceObjects=_colorResourceObjects;
@property(readonly) DYFramebufferObject *framebufferObject; // @synthesize framebufferObject=_framebufferObject;
- (void).cxx_destruct;
- (id)attachments;
- (id)attachmentForEnum:(unsigned int)arg1;
- (id)initWithFBO:(id)arg1;

@end

