/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DYContinuation, DYDevice, DYDeviceInfo, DYGuestAppSession, GPUDebuggerController, NSObject<OS_dispatch_queue>;

@interface GPUTraceReplayController : NSObject
{
    DYDevice *_device;
    BOOL _replayerReady;
    DYGuestAppSession *_replaySession;
    NSObject<OS_dispatch_queue> *_queue;
    GPUDebuggerController *_controller;
    DYContinuation *_invalidTerminationHandler;
    unsigned int _currentFunctionIndex;
    unsigned int _lastFunctionIndex;
}

@property(readonly) unsigned int currentFunctionIndex; // @synthesize currentFunctionIndex=_currentFunctionIndex;
@property(readonly) DYGuestAppSession *replaySession; // @synthesize replaySession=_replaySession;
@property BOOL replayerReady; // @synthesize replayerReady=_replayerReady;
@property(readonly) GPUDebuggerController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)removeCaptureArchivesFromReplayDevice:(id)arg1;
- (void)replayWithExperiment:(id)arg1 baseCaptureArchivePath:(id)arg2 playbackMessageHandler:(id)arg3;
- (void)setReplayDeviceBackgroundImage:(id)arg1;
- (id)initiateDebuggerReplaySession:(BOOL)arg1;
- (id)_deleteArchivesFromDeviceIfNeeded:(BOOL)arg1;
- (id)initiateReplaySession:(id)arg1;
- (id)prepareCaptureArchive:(id)arg1 withDestinationName:(id)arg2;
- (id)launchReplayerWithMessageHandler:(id)arg1;
- (id)endDebuggerReplaySession;
- (id)endReplaySession;
- (void)sendDebugBeginMessage:(id)arg1;
- (void)toggleDeviceSideDrawPresenting:(BOOL)arg1 withFuture:(id)arg2;
- (void)setWireframeLineWidth:(float)arg1 withFuture:(id)arg2;
- (void)toggleDeviceSideWireframePresenting:(BOOL)arg1 withFuture:(id)arg2;
- (void)replayToFunctionIndex:(unsigned int)arg1 withFutureResult:(id)arg2;
- (void)invalidate;
- (id)setupDevice;
@property(readonly) DYDeviceInfo *playbackDeviceInfo; // @dynamic playbackDeviceInfo;
- (id)initWithController:(id)arg1 lastFunctionIndex:(unsigned int)arg2;

@end

