/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DYContinuation, NSString;

// Not exported
@interface JobInfo : NSObject
{
    NSString *_jobId;
    DYContinuation *_job;
}

@property(readonly, nonatomic) DYContinuation *job; // @synthesize job=_job;
@property(readonly, nonatomic) NSString *jobId; // @synthesize jobId=_jobId;
- (void).cxx_destruct;
- (id)initWithId:(id)arg1 job:(id)arg2;
- (id)init;

@end

