/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "QTMovieView.h"

@class NSString;

@interface QTMovieView (IBQTMovieViewIntegration)
+ (id)keyPathsForValuesAffectingIbInspectedMoviePath;
+ (id)keyPathsForValuesAffectingDesignableMovieURLString;
- (void)setIbInspectedMoviePath:(id)arg1;
- (id)ibInspectedMoviePath;
@property(retain) NSString *designableMovieURLString;
- (void)setDesignableZoomButtonsVisible:(BOOL)arg1;
- (void)setDesignableStepButtonsVisible:(BOOL)arg1;
- (BOOL)designableZoomButtonsVisible;
- (BOOL)designableStepButtonsVisible;
@end

