/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSBundle, NSObject<OS_dispatch_semaphore>;

// Not exported
@interface GPUResourceThumbnailFactory : NSObject
{
    NSBundle *_assetBundle;
    NSObject<OS_dispatch_semaphore> *_renderersSema;
    struct {
        void *opaque1;
        long long opaque2;
    } _freeRenderers;
    struct ImageRenderer *_renderers[8];
}

+ (id)sharedThumbnailFactory;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)thumbnailWithResourceItem:(id)arg1 scale:(double)arg2;
- (id)defaultImageForResourceItem:(id)arg1;
- (id)_generateThumbnailForImage:(id)arg1 scale:(double)arg2;
- (void)dealloc;
- (id)init;

@end

