/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTPopoverContentViewController.h"

#import "NSTextFieldDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class DYRangeSlider, DYRenderingAttributes, NSBox, NSButton, NSSlider, NSString, NSTextField, NSView;

@interface GPUTraceResourceSettingsBubble : DVTPopoverContentViewController <NSWindowDelegate, NSTextFieldDelegate>
{
    NSView *_parentView;
    id <DYResource> _resource;
    DYRenderingAttributes *_dispAttr;
    id <GPUTraceBubbleOwner> _owner;
    NSButton *_redButton;
    NSButton *_grnButton;
    NSButton *_bluButton;
    NSButton *_alfButton;
    NSBox *_visibleRangeBox;
    NSSlider *_dummySlider;
    NSTextField *_rangeEditMin;
    NSTextField *_rangeEditMax;
    DYRangeSlider *_visibleRangeSlider;
    BOOL _showDepth;
    BOOL _isLuminance;
    BOOL _hasRed;
    BOOL _hasGreen;
    BOOL _hasBlue;
    BOOL _hasAlpha;
    unsigned int _channelCount;
    unsigned int _alphaChannelIndex;
}

@property(nonatomic) BOOL hasAlpha; // @synthesize hasAlpha=_hasAlpha;
@property(nonatomic) BOOL hasBlue; // @synthesize hasBlue=_hasBlue;
@property(nonatomic) BOOL hasGreen; // @synthesize hasGreen=_hasGreen;
@property(nonatomic) BOOL hasRed; // @synthesize hasRed=_hasRed;
@property(nonatomic) BOOL isLuminance; // @synthesize isLuminance=_isLuminance;
@property(nonatomic) unsigned int alphaChannelIndex; // @synthesize alphaChannelIndex=_alphaChannelIndex;
@property(nonatomic) unsigned int channelCount; // @synthesize channelCount=_channelCount;
@property(readonly, nonatomic) BOOL showDepth; // @synthesize showDepth=_showDepth;
- (void).cxx_destruct;
- (void)updateToneMapRangeFields:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)updateToneMapRange:(id)arg1;
- (void)_setupVisibleRangeSlider;
- (void)_resetChannelToolTips;
- (void)_resetButtonState;
- (void)_setupChannelEnableControl;
- (void)viewDidInstall;
- (void)toggleChannelEnable:(id)arg1;
- (void)updateChannelEnableImages;
- (void)setButtonToolTipText:(id)arg1 withChannel:(id)arg2;
- (void)close;
- (void)_cleanUpAfterClosingPopupWindow;
- (void)showAtPoint:(struct CGPoint)arg1;
- (id)getAlphaButton;
- (id)initWithResource:(id)arg1 withDisplayAttributes:(id)arg2 withShowDepth:(BOOL)arg3 parentView:(id)arg4 owner:(id)arg5;
- (int)numChannelsSelectedInImage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

