/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEEditorDocument.h"

#import "IDEDocumentStructureProviding-Protocol.h"

@class DVTObservingToken, GPUSharedTabUIState, GPUTraceOutline, NSArray, NSString;

// Not exported
@interface GPUTraceResourcesDocument : IDEEditorDocument <IDEDocumentStructureProviding>
{
    DVTObservingToken *_uiModeObservation;
    NSArray *_topLevelObjects;
    GPUSharedTabUIState *_sharedTabUIState;
    GPUTraceOutline *_outline;
    NSString *_resourceGroup;
    NSString *_resourceSubGroup;
}

+ (BOOL)autosavesInPlace;
+ (id)keyPathsForValuesAffectingNavigableItem_name;
@property(readonly) NSString *resourceSubGroup; // @synthesize resourceSubGroup=_resourceSubGroup;
@property(readonly) NSString *resourceGroup; // @synthesize resourceGroup=_resourceGroup;
@property(retain) GPUTraceOutline *outline; // @synthesize outline=_outline;
@property(readonly) GPUSharedTabUIState *sharedTabUIState; // @synthesize sharedTabUIState=_sharedTabUIState;
- (void).cxx_destruct;
- (id)displayName;
- (id)writableTypesForSaveOperation:(unsigned long long)arg1;
- (BOOL)prepareSavePanel:(id)arg1;
- (BOOL)canExportDocument;
- (BOOL)canSave;
- (BOOL)writeSafelyToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 error:(id *)arg4;
@property(readonly) NSArray *ideTopLevelStructureObjects;
- (int)readOnlyStatus;
- (void)editorDocumentWillClose;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)refreshTopLevelObjects;
- (id)_refresh_MainEditorTopLevelGroup;
- (id)_refresh_AssistantTopLevelGroup;
- (id)_topLevelGroupForItem:(id)arg1;

@end

