/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol NSCollectionViewDelegate <NSObject>

@optional
- (void)collectionView:(id)arg1 updateDraggingItemsForDrag:(id)arg2;
- (void)collectionView:(id)arg1 draggingSession:(id)arg2 endedAtPoint:(struct CGPoint)arg3 dragOperation:(unsigned long long)arg4;
- (void)collectionView:(id)arg1 draggingSession:(id)arg2 willBeginAtPoint:(struct CGPoint)arg3 forItemsAtIndexes:(id)arg4;
- (id)collectionView:(id)arg1 pasteboardWriterForItemAtIndex:(unsigned long long)arg2;
- (BOOL)collectionView:(id)arg1 acceptDrop:(id)arg2 index:(long long)arg3 dropOperation:(long long)arg4;
- (unsigned long long)collectionView:(id)arg1 validateDrop:(id)arg2 proposedIndex:(long long *)arg3 dropOperation:(long long *)arg4;
- (id)collectionView:(id)arg1 draggingImageForItemsAtIndexes:(id)arg2 withEvent:(id)arg3 offset:(struct CGPoint *)arg4;
- (id)collectionView:(id)arg1 namesOfPromisedFilesDroppedAtDestination:(id)arg2 forDraggedItemsAtIndexes:(id)arg3;
- (BOOL)collectionView:(id)arg1 writeItemsAtIndexes:(id)arg2 toPasteboard:(id)arg3;
- (BOOL)collectionView:(id)arg1 canDragItemsAtIndexes:(id)arg2 withEvent:(id)arg3;
@end

