/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DSMFullTextResultsUtilities : NSObject
{
}

+ (id)_trimToTopHits:(id)arg1 givenMaxRelevance:(float)arg2;
+ (id)filteredAndSortedFullTextResults:(id)arg1 maxRelevance:(double)arg2;

@end

