/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DSMQuery, DVTPerformanceMetric, NSArray, NSMutableArray;

@interface DSMQueryRunner : NSObject
{
    id _completionBlock;
    NSArray *_textResults;
    NSMutableArray *_APIResults;
    BOOL _textQueryCompleted;
    BOOL _APIQueryCompleted;
    NSMutableArray *_temporaryFullTextSearchResults;
    DSMQuery *_query;
    BOOL _isCancelling;
    DVTPerformanceMetric *_docSetQueriesPerformanceMetric;
}

@property(retain) DSMQuery *query; // @synthesize query=_query;
@property(retain) NSMutableArray *temporaryFullTextSearchResults; // @synthesize temporaryFullTextSearchResults=_temporaryFullTextSearchResults;
- (void).cxx_destruct;
- (void)cancel;
- (void)runTokenQuery;
- (void)runFullTextQuery;
- (void)docSets:(id)arg1 didFindTextSearchResults:(id)arg2 isFinished:(BOOL)arg3 contextInfo:(void *)arg4;
- (void)docSets:(id)arg1 didFindTokenSearchResults:(id)arg2 isFinished:(BOOL)arg3 contextInfo:(void *)arg4;
- (void)updateResults;
- (void)executeQuery:(id)arg1;
- (id)initWithQuery:(id)arg1;

@end

